// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ABIREPORT", Schema = "TESTPROD")]
    [Index(nameof(Cod0), Name = "ABIREPORT_ABO0", IsUnique = true)]
    [Index(nameof(Repcod0), nameof(Cod0), Name = "ABIREPORT_ABO1", IsUnique = true)]
    [Index(nameof(Datam0), nameof(Cod0), Name = "ABIREPORT_ABO2")]
    public partial class Abireport
    {
        [Required]
        [Column("COD_0")]
        [StringLength(10)]
        public string Cod0 { get; set; }
        [Column("DES_0")]
        public int Des0 { get; set; }
        [Column("SHO_0")]
        public int Sho0 { get; set; }
        [Column("ENAFLG_0")]
        public byte Enaflg0 { get; set; }
        [Required]
        [Column("ACV_0")]
        [StringLength(5)]
        public string Acv0 { get; set; }
        [Column("MODULE_0")]
        public byte Module0 { get; set; }
        [Required]
        [Column("ACS_0")]
        [StringLength(10)]
        public string Acs0 { get; set; }
        [Required]
        [Column("REPCOD_0")]
        [StringLength(50)]
        public string Repcod0 { get; set; }
        [Required]
        [Column("DATAM_0")]
        [StringLength(10)]
        public string Datam0 { get; set; }
        [Column("DES1_0")]
        public int Des10 { get; set; }
        [Column("DES2_0")]
        public int Des20 { get; set; }
        [Column("DES3_0")]
        public int Des30 { get; set; }
        [Column("ETAREF_0")]
        public byte Etaref0 { get; set; }
        [Required]
        [Column("LANREF_0")]
        [StringLength(3)]
        public string Lanref0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}