// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ABITABFLD", Schema = "TESTPROD")]
    [Index(nameof(Codabf0), nameof(Numfld0), nameof(Codfld0), Name = "ABITABFLD_ABZ0", IsUnique = true)]
    [Index(nameof(Codabf0), nameof(Codfld0), Name = "ABITABFLD_ABZ1", IsUnique = true)]
    [Index(nameof(Codfld0), Name = "ABITABFLD_DICO")]
    public partial class Abitabfld
    {
        [Required]
        [Column("CODABF_0")]
        [StringLength(10)]
        public string Codabf0 { get; set; }
        [Column("NUMFLD_0")]
        public short Numfld0 { get; set; }
        [Required]
        [Column("CODFLD_0")]
        [StringLength(12)]
        public string Codfld0 { get; set; }
        [Column("INTFLD_0")]
        public int Intfld0 { get; set; }
        [Required]
        [Column("INTVALFLD_0")]
        [StringLength(60)]
        public string Intvalfld0 { get; set; }
        [Required]
        [Column("CODTYP_0")]
        [StringLength(3)]
        public string Codtyp0 { get; set; }
        [Required]
        [Column("TYPDAT_0")]
        [StringLength(10)]
        public string Typdat0 { get; set; }
        [Column("LNGFLD_0", TypeName = "numeric(7, 3)")]
        public decimal Lngfld0 { get; set; }
        [Column("MENLOC_0")]
        public short Menloc0 { get; set; }
        [Column("TABDIV_0")]
        public short Tabdiv0 { get; set; }
        [Required]
        [Column("ACTFLD_0")]
        [StringLength(5)]
        public string Actfld0 { get; set; }
        [Column("TYPFLD_0")]
        public byte Typfld0 { get; set; }
        [Column("TYPOPE_0")]
        public byte Typope0 { get; set; }
        [Column("TUNNEL_0")]
        public byte Tunnel0 { get; set; }
        [Column("INTSSC_0")]
        public int Intssc0 { get; set; }
        [Required]
        [Column("INTVALSSC_0")]
        [StringLength(60)]
        public string Intvalssc0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}