// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ACLOB", Schema = "TESTPROD")]
    [Index(nameof(Codblb0), nameof(Ident10), nameof(Ident20), nameof(Ident30), Name = "ACLOB_ACB0", IsUnique = true)]
    public partial class Aclob
    {
        [Required]
        [Column("CODBLB_0")]
        [StringLength(10)]
        public string Codblb0 { get; set; }
        [Required]
        [Column("IDENT1_0")]
        [StringLength(80)]
        public string Ident10 { get; set; }
        [Required]
        [Column("IDENT2_0")]
        [StringLength(80)]
        public string Ident20 { get; set; }
        [Required]
        [Column("IDENT3_0")]
        [StringLength(10)]
        public string Ident30 { get; set; }
        [Required]
        [Column("NAMBLB_0")]
        [StringLength(30)]
        public string Namblb0 { get; set; }
        [Required]
        [Column("TYPDOC_0")]
        [StringLength(20)]
        public string Typdoc0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("CLOB_0")]
        public string Clob0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}