// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ACTL", Schema = "TESTPROD")]
    [Index(nameof(Ctl0), Name = "ACTL_ACL0", IsUnique = true)]
    public partial class Actl
    {
        [Required]
        [Column("CTL_0")]
        [StringLength(10)]
        public string Ctl0 { get; set; }
        [Column("TYPCTL_0")]
        public byte Typctl0 { get; set; }
        [Required]
        [Column("DEPCTL_0")]
        [StringLength(10)]
        public string Depctl0 { get; set; }
        [Column("NBRVAL_0")]
        public short Nbrval0 { get; set; }
        [Required]
        [Column("LSTVAL_0")]
        [StringLength(15)]
        public string Lstval0 { get; set; }
        [Required]
        [Column("LSTVAL_1")]
        [StringLength(15)]
        public string Lstval1 { get; set; }
        [Required]
        [Column("LSTVAL_2")]
        [StringLength(15)]
        public string Lstval2 { get; set; }
        [Required]
        [Column("LSTVAL_3")]
        [StringLength(15)]
        public string Lstval3 { get; set; }
        [Required]
        [Column("LSTVAL_4")]
        [StringLength(15)]
        public string Lstval4 { get; set; }
        [Required]
        [Column("LSTVAL_5")]
        [StringLength(15)]
        public string Lstval5 { get; set; }
        [Required]
        [Column("LSTVAL_6")]
        [StringLength(15)]
        public string Lstval6 { get; set; }
        [Required]
        [Column("LSTVAL_7")]
        [StringLength(15)]
        public string Lstval7 { get; set; }
        [Required]
        [Column("LSTVAL_8")]
        [StringLength(15)]
        public string Lstval8 { get; set; }
        [Required]
        [Column("LSTVAL_9")]
        [StringLength(15)]
        public string Lstval9 { get; set; }
        [Required]
        [Column("LSTVAL_10")]
        [StringLength(15)]
        public string Lstval10 { get; set; }
        [Required]
        [Column("LSTVAL_11")]
        [StringLength(15)]
        public string Lstval11 { get; set; }
        [Required]
        [Column("LSTVAL_12")]
        [StringLength(15)]
        public string Lstval12 { get; set; }
        [Required]
        [Column("LSTVAL_13")]
        [StringLength(15)]
        public string Lstval13 { get; set; }
        [Required]
        [Column("LSTVAL_14")]
        [StringLength(15)]
        public string Lstval14 { get; set; }
        [Required]
        [Column("LSTVAL_15")]
        [StringLength(15)]
        public string Lstval15 { get; set; }
        [Required]
        [Column("LSTVAL_16")]
        [StringLength(15)]
        public string Lstval16 { get; set; }
        [Required]
        [Column("LSTVAL_17")]
        [StringLength(15)]
        public string Lstval17 { get; set; }
        [Required]
        [Column("LSTVAL_18")]
        [StringLength(15)]
        public string Lstval18 { get; set; }
        [Required]
        [Column("LSTVAL_19")]
        [StringLength(15)]
        public string Lstval19 { get; set; }
        [Required]
        [Column("LSTVAL_20")]
        [StringLength(15)]
        public string Lstval20 { get; set; }
        [Required]
        [Column("LSTVAL_21")]
        [StringLength(15)]
        public string Lstval21 { get; set; }
        [Required]
        [Column("LSTVAL_22")]
        [StringLength(15)]
        public string Lstval22 { get; set; }
        [Required]
        [Column("LSTVAL_23")]
        [StringLength(15)]
        public string Lstval23 { get; set; }
        [Required]
        [Column("LSTVAL_24")]
        [StringLength(15)]
        public string Lstval24 { get; set; }
        [Required]
        [Column("LSTVAL_25")]
        [StringLength(15)]
        public string Lstval25 { get; set; }
        [Required]
        [Column("LSTVAL_26")]
        [StringLength(15)]
        public string Lstval26 { get; set; }
        [Required]
        [Column("LSTVAL_27")]
        [StringLength(15)]
        public string Lstval27 { get; set; }
        [Required]
        [Column("LSTVAL_28")]
        [StringLength(15)]
        public string Lstval28 { get; set; }
        [Required]
        [Column("LSTVAL_29")]
        [StringLength(15)]
        public string Lstval29 { get; set; }
        [Required]
        [Column("DEPVAL_0")]
        [StringLength(15)]
        public string Depval0 { get; set; }
        [Required]
        [Column("DEPVAL_1")]
        [StringLength(15)]
        public string Depval1 { get; set; }
        [Required]
        [Column("DEPVAL_2")]
        [StringLength(15)]
        public string Depval2 { get; set; }
        [Required]
        [Column("DEPVAL_3")]
        [StringLength(15)]
        public string Depval3 { get; set; }
        [Required]
        [Column("DEPVAL_4")]
        [StringLength(15)]
        public string Depval4 { get; set; }
        [Required]
        [Column("DEPVAL_5")]
        [StringLength(15)]
        public string Depval5 { get; set; }
        [Required]
        [Column("DEPVAL_6")]
        [StringLength(15)]
        public string Depval6 { get; set; }
        [Required]
        [Column("DEPVAL_7")]
        [StringLength(15)]
        public string Depval7 { get; set; }
        [Required]
        [Column("DEPVAL_8")]
        [StringLength(15)]
        public string Depval8 { get; set; }
        [Required]
        [Column("DEPVAL_9")]
        [StringLength(15)]
        public string Depval9 { get; set; }
        [Required]
        [Column("DEPVAL_10")]
        [StringLength(15)]
        public string Depval10 { get; set; }
        [Required]
        [Column("DEPVAL_11")]
        [StringLength(15)]
        public string Depval11 { get; set; }
        [Required]
        [Column("DEPVAL_12")]
        [StringLength(15)]
        public string Depval12 { get; set; }
        [Required]
        [Column("DEPVAL_13")]
        [StringLength(15)]
        public string Depval13 { get; set; }
        [Required]
        [Column("DEPVAL_14")]
        [StringLength(15)]
        public string Depval14 { get; set; }
        [Required]
        [Column("DEPVAL_15")]
        [StringLength(15)]
        public string Depval15 { get; set; }
        [Required]
        [Column("DEPVAL_16")]
        [StringLength(15)]
        public string Depval16 { get; set; }
        [Required]
        [Column("DEPVAL_17")]
        [StringLength(15)]
        public string Depval17 { get; set; }
        [Required]
        [Column("DEPVAL_18")]
        [StringLength(15)]
        public string Depval18 { get; set; }
        [Required]
        [Column("DEPVAL_19")]
        [StringLength(15)]
        public string Depval19 { get; set; }
        [Required]
        [Column("DEPVAL_20")]
        [StringLength(15)]
        public string Depval20 { get; set; }
        [Required]
        [Column("DEPVAL_21")]
        [StringLength(15)]
        public string Depval21 { get; set; }
        [Required]
        [Column("DEPVAL_22")]
        [StringLength(15)]
        public string Depval22 { get; set; }
        [Required]
        [Column("DEPVAL_23")]
        [StringLength(15)]
        public string Depval23 { get; set; }
        [Required]
        [Column("DEPVAL_24")]
        [StringLength(15)]
        public string Depval24 { get; set; }
        [Required]
        [Column("DEPVAL_25")]
        [StringLength(15)]
        public string Depval25 { get; set; }
        [Required]
        [Column("DEPVAL_26")]
        [StringLength(15)]
        public string Depval26 { get; set; }
        [Required]
        [Column("DEPVAL_27")]
        [StringLength(15)]
        public string Depval27 { get; set; }
        [Required]
        [Column("DEPVAL_28")]
        [StringLength(15)]
        public string Depval28 { get; set; }
        [Required]
        [Column("DEPVAL_29")]
        [StringLength(15)]
        public string Depval29 { get; set; }
        [Column("OBL_0")]
        public byte Obl0 { get; set; }
        [Required]
        [Column("MSG_0")]
        [StringLength(50)]
        public string Msg0 { get; set; }
        [Required]
        [Column("FRM_0")]
        [StringLength(80)]
        public string Frm0 { get; set; }
        [Column("TYPCTL2_0")]
        public byte Typctl20 { get; set; }
        [Required]
        [Column("DEPCTL2_0")]
        [StringLength(10)]
        public string Depctl20 { get; set; }
        [Column("NBRVAL2_0")]
        public short Nbrval20 { get; set; }
        [Required]
        [Column("LSTVAL2_0")]
        [StringLength(15)]
        public string Lstval201 { get; set; }
        [Required]
        [Column("LSTVAL2_1")]
        [StringLength(15)]
        public string Lstval211 { get; set; }
        [Required]
        [Column("LSTVAL2_2")]
        [StringLength(15)]
        public string Lstval221 { get; set; }
        [Required]
        [Column("LSTVAL2_3")]
        [StringLength(15)]
        public string Lstval231 { get; set; }
        [Required]
        [Column("LSTVAL2_4")]
        [StringLength(15)]
        public string Lstval241 { get; set; }
        [Required]
        [Column("LSTVAL2_5")]
        [StringLength(15)]
        public string Lstval251 { get; set; }
        [Required]
        [Column("LSTVAL2_6")]
        [StringLength(15)]
        public string Lstval261 { get; set; }
        [Required]
        [Column("LSTVAL2_7")]
        [StringLength(15)]
        public string Lstval271 { get; set; }
        [Required]
        [Column("LSTVAL2_8")]
        [StringLength(15)]
        public string Lstval281 { get; set; }
        [Required]
        [Column("LSTVAL2_9")]
        [StringLength(15)]
        public string Lstval291 { get; set; }
        [Required]
        [Column("LSTVAL2_10")]
        [StringLength(15)]
        public string Lstval210 { get; set; }
        [Required]
        [Column("LSTVAL2_11")]
        [StringLength(15)]
        public string Lstval2111 { get; set; }
        [Required]
        [Column("LSTVAL2_12")]
        [StringLength(15)]
        public string Lstval212 { get; set; }
        [Required]
        [Column("LSTVAL2_13")]
        [StringLength(15)]
        public string Lstval213 { get; set; }
        [Required]
        [Column("LSTVAL2_14")]
        [StringLength(15)]
        public string Lstval214 { get; set; }
        [Required]
        [Column("LSTVAL2_15")]
        [StringLength(15)]
        public string Lstval215 { get; set; }
        [Required]
        [Column("LSTVAL2_16")]
        [StringLength(15)]
        public string Lstval216 { get; set; }
        [Required]
        [Column("LSTVAL2_17")]
        [StringLength(15)]
        public string Lstval217 { get; set; }
        [Required]
        [Column("LSTVAL2_18")]
        [StringLength(15)]
        public string Lstval218 { get; set; }
        [Required]
        [Column("LSTVAL2_19")]
        [StringLength(15)]
        public string Lstval219 { get; set; }
        [Required]
        [Column("LSTVAL2_20")]
        [StringLength(15)]
        public string Lstval220 { get; set; }
        [Required]
        [Column("LSTVAL2_21")]
        [StringLength(15)]
        public string Lstval2211 { get; set; }
        [Required]
        [Column("LSTVAL2_22")]
        [StringLength(15)]
        public string Lstval222 { get; set; }
        [Required]
        [Column("LSTVAL2_23")]
        [StringLength(15)]
        public string Lstval223 { get; set; }
        [Required]
        [Column("LSTVAL2_24")]
        [StringLength(15)]
        public string Lstval224 { get; set; }
        [Required]
        [Column("LSTVAL2_25")]
        [StringLength(15)]
        public string Lstval225 { get; set; }
        [Required]
        [Column("LSTVAL2_26")]
        [StringLength(15)]
        public string Lstval226 { get; set; }
        [Required]
        [Column("LSTVAL2_27")]
        [StringLength(15)]
        public string Lstval227 { get; set; }
        [Required]
        [Column("LSTVAL2_28")]
        [StringLength(15)]
        public string Lstval228 { get; set; }
        [Required]
        [Column("LSTVAL2_29")]
        [StringLength(15)]
        public string Lstval229 { get; set; }
        [Required]
        [Column("DEPVAL2_0")]
        [StringLength(15)]
        public string Depval201 { get; set; }
        [Required]
        [Column("DEPVAL2_1")]
        [StringLength(15)]
        public string Depval211 { get; set; }
        [Required]
        [Column("DEPVAL2_2")]
        [StringLength(15)]
        public string Depval221 { get; set; }
        [Required]
        [Column("DEPVAL2_3")]
        [StringLength(15)]
        public string Depval231 { get; set; }
        [Required]
        [Column("DEPVAL2_4")]
        [StringLength(15)]
        public string Depval241 { get; set; }
        [Required]
        [Column("DEPVAL2_5")]
        [StringLength(15)]
        public string Depval251 { get; set; }
        [Required]
        [Column("DEPVAL2_6")]
        [StringLength(15)]
        public string Depval261 { get; set; }
        [Required]
        [Column("DEPVAL2_7")]
        [StringLength(15)]
        public string Depval271 { get; set; }
        [Required]
        [Column("DEPVAL2_8")]
        [StringLength(15)]
        public string Depval281 { get; set; }
        [Required]
        [Column("DEPVAL2_9")]
        [StringLength(15)]
        public string Depval291 { get; set; }
        [Required]
        [Column("DEPVAL2_10")]
        [StringLength(15)]
        public string Depval210 { get; set; }
        [Required]
        [Column("DEPVAL2_11")]
        [StringLength(15)]
        public string Depval2111 { get; set; }
        [Required]
        [Column("DEPVAL2_12")]
        [StringLength(15)]
        public string Depval212 { get; set; }
        [Required]
        [Column("DEPVAL2_13")]
        [StringLength(15)]
        public string Depval213 { get; set; }
        [Required]
        [Column("DEPVAL2_14")]
        [StringLength(15)]
        public string Depval214 { get; set; }
        [Required]
        [Column("DEPVAL2_15")]
        [StringLength(15)]
        public string Depval215 { get; set; }
        [Required]
        [Column("DEPVAL2_16")]
        [StringLength(15)]
        public string Depval216 { get; set; }
        [Required]
        [Column("DEPVAL2_17")]
        [StringLength(15)]
        public string Depval217 { get; set; }
        [Required]
        [Column("DEPVAL2_18")]
        [StringLength(15)]
        public string Depval218 { get; set; }
        [Required]
        [Column("DEPVAL2_19")]
        [StringLength(15)]
        public string Depval219 { get; set; }
        [Required]
        [Column("DEPVAL2_20")]
        [StringLength(15)]
        public string Depval220 { get; set; }
        [Required]
        [Column("DEPVAL2_21")]
        [StringLength(15)]
        public string Depval2211 { get; set; }
        [Required]
        [Column("DEPVAL2_22")]
        [StringLength(15)]
        public string Depval222 { get; set; }
        [Required]
        [Column("DEPVAL2_23")]
        [StringLength(15)]
        public string Depval223 { get; set; }
        [Required]
        [Column("DEPVAL2_24")]
        [StringLength(15)]
        public string Depval224 { get; set; }
        [Required]
        [Column("DEPVAL2_25")]
        [StringLength(15)]
        public string Depval225 { get; set; }
        [Required]
        [Column("DEPVAL2_26")]
        [StringLength(15)]
        public string Depval226 { get; set; }
        [Required]
        [Column("DEPVAL2_27")]
        [StringLength(15)]
        public string Depval227 { get; set; }
        [Required]
        [Column("DEPVAL2_28")]
        [StringLength(15)]
        public string Depval228 { get; set; }
        [Required]
        [Column("DEPVAL2_29")]
        [StringLength(15)]
        public string Depval229 { get; set; }
        [Required]
        [Column("MSG2_0")]
        [StringLength(50)]
        public string Msg20 { get; set; }
        [Required]
        [Column("FRM2_0")]
        [StringLength(80)]
        public string Frm20 { get; set; }
        [Column("TYPCTL3_0")]
        public byte Typctl30 { get; set; }
        [Required]
        [Column("DEPCTL3_0")]
        [StringLength(10)]
        public string Depctl30 { get; set; }
        [Column("NBRVAL3_0")]
        public short Nbrval30 { get; set; }
        [Required]
        [Column("LSTVAL3_0")]
        [StringLength(15)]
        public string Lstval30 { get; set; }
        [Required]
        [Column("LSTVAL3_1")]
        [StringLength(15)]
        public string Lstval31 { get; set; }
        [Required]
        [Column("LSTVAL3_2")]
        [StringLength(15)]
        public string Lstval32 { get; set; }
        [Required]
        [Column("LSTVAL3_3")]
        [StringLength(15)]
        public string Lstval33 { get; set; }
        [Required]
        [Column("LSTVAL3_4")]
        [StringLength(15)]
        public string Lstval34 { get; set; }
        [Required]
        [Column("LSTVAL3_5")]
        [StringLength(15)]
        public string Lstval35 { get; set; }
        [Required]
        [Column("LSTVAL3_6")]
        [StringLength(15)]
        public string Lstval36 { get; set; }
        [Required]
        [Column("LSTVAL3_7")]
        [StringLength(15)]
        public string Lstval37 { get; set; }
        [Required]
        [Column("LSTVAL3_8")]
        [StringLength(15)]
        public string Lstval38 { get; set; }
        [Required]
        [Column("LSTVAL3_9")]
        [StringLength(15)]
        public string Lstval39 { get; set; }
        [Required]
        [Column("LSTVAL3_10")]
        [StringLength(15)]
        public string Lstval310 { get; set; }
        [Required]
        [Column("LSTVAL3_11")]
        [StringLength(15)]
        public string Lstval311 { get; set; }
        [Required]
        [Column("LSTVAL3_12")]
        [StringLength(15)]
        public string Lstval312 { get; set; }
        [Required]
        [Column("LSTVAL3_13")]
        [StringLength(15)]
        public string Lstval313 { get; set; }
        [Required]
        [Column("LSTVAL3_14")]
        [StringLength(15)]
        public string Lstval314 { get; set; }
        [Required]
        [Column("LSTVAL3_15")]
        [StringLength(15)]
        public string Lstval315 { get; set; }
        [Required]
        [Column("LSTVAL3_16")]
        [StringLength(15)]
        public string Lstval316 { get; set; }
        [Required]
        [Column("LSTVAL3_17")]
        [StringLength(15)]
        public string Lstval317 { get; set; }
        [Required]
        [Column("LSTVAL3_18")]
        [StringLength(15)]
        public string Lstval318 { get; set; }
        [Required]
        [Column("LSTVAL3_19")]
        [StringLength(15)]
        public string Lstval319 { get; set; }
        [Required]
        [Column("LSTVAL3_20")]
        [StringLength(15)]
        public string Lstval320 { get; set; }
        [Required]
        [Column("LSTVAL3_21")]
        [StringLength(15)]
        public string Lstval321 { get; set; }
        [Required]
        [Column("LSTVAL3_22")]
        [StringLength(15)]
        public string Lstval322 { get; set; }
        [Required]
        [Column("LSTVAL3_23")]
        [StringLength(15)]
        public string Lstval323 { get; set; }
        [Required]
        [Column("LSTVAL3_24")]
        [StringLength(15)]
        public string Lstval324 { get; set; }
        [Required]
        [Column("LSTVAL3_25")]
        [StringLength(15)]
        public string Lstval325 { get; set; }
        [Required]
        [Column("LSTVAL3_26")]
        [StringLength(15)]
        public string Lstval326 { get; set; }
        [Required]
        [Column("LSTVAL3_27")]
        [StringLength(15)]
        public string Lstval327 { get; set; }
        [Required]
        [Column("LSTVAL3_28")]
        [StringLength(15)]
        public string Lstval328 { get; set; }
        [Required]
        [Column("LSTVAL3_29")]
        [StringLength(15)]
        public string Lstval329 { get; set; }
        [Required]
        [Column("DEPVAL3_0")]
        [StringLength(15)]
        public string Depval30 { get; set; }
        [Required]
        [Column("DEPVAL3_1")]
        [StringLength(15)]
        public string Depval31 { get; set; }
        [Required]
        [Column("DEPVAL3_2")]
        [StringLength(15)]
        public string Depval32 { get; set; }
        [Required]
        [Column("DEPVAL3_3")]
        [StringLength(15)]
        public string Depval33 { get; set; }
        [Required]
        [Column("DEPVAL3_4")]
        [StringLength(15)]
        public string Depval34 { get; set; }
        [Required]
        [Column("DEPVAL3_5")]
        [StringLength(15)]
        public string Depval35 { get; set; }
        [Required]
        [Column("DEPVAL3_6")]
        [StringLength(15)]
        public string Depval36 { get; set; }
        [Required]
        [Column("DEPVAL3_7")]
        [StringLength(15)]
        public string Depval37 { get; set; }
        [Required]
        [Column("DEPVAL3_8")]
        [StringLength(15)]
        public string Depval38 { get; set; }
        [Required]
        [Column("DEPVAL3_9")]
        [StringLength(15)]
        public string Depval39 { get; set; }
        [Required]
        [Column("DEPVAL3_10")]
        [StringLength(15)]
        public string Depval310 { get; set; }
        [Required]
        [Column("DEPVAL3_11")]
        [StringLength(15)]
        public string Depval311 { get; set; }
        [Required]
        [Column("DEPVAL3_12")]
        [StringLength(15)]
        public string Depval312 { get; set; }
        [Required]
        [Column("DEPVAL3_13")]
        [StringLength(15)]
        public string Depval313 { get; set; }
        [Required]
        [Column("DEPVAL3_14")]
        [StringLength(15)]
        public string Depval314 { get; set; }
        [Required]
        [Column("DEPVAL3_15")]
        [StringLength(15)]
        public string Depval315 { get; set; }
        [Required]
        [Column("DEPVAL3_16")]
        [StringLength(15)]
        public string Depval316 { get; set; }
        [Required]
        [Column("DEPVAL3_17")]
        [StringLength(15)]
        public string Depval317 { get; set; }
        [Required]
        [Column("DEPVAL3_18")]
        [StringLength(15)]
        public string Depval318 { get; set; }
        [Required]
        [Column("DEPVAL3_19")]
        [StringLength(15)]
        public string Depval319 { get; set; }
        [Required]
        [Column("DEPVAL3_20")]
        [StringLength(15)]
        public string Depval320 { get; set; }
        [Required]
        [Column("DEPVAL3_21")]
        [StringLength(15)]
        public string Depval321 { get; set; }
        [Required]
        [Column("DEPVAL3_22")]
        [StringLength(15)]
        public string Depval322 { get; set; }
        [Required]
        [Column("DEPVAL3_23")]
        [StringLength(15)]
        public string Depval323 { get; set; }
        [Required]
        [Column("DEPVAL3_24")]
        [StringLength(15)]
        public string Depval324 { get; set; }
        [Required]
        [Column("DEPVAL3_25")]
        [StringLength(15)]
        public string Depval325 { get; set; }
        [Required]
        [Column("DEPVAL3_26")]
        [StringLength(15)]
        public string Depval326 { get; set; }
        [Required]
        [Column("DEPVAL3_27")]
        [StringLength(15)]
        public string Depval327 { get; set; }
        [Required]
        [Column("DEPVAL3_28")]
        [StringLength(15)]
        public string Depval328 { get; set; }
        [Required]
        [Column("DEPVAL3_29")]
        [StringLength(15)]
        public string Depval329 { get; set; }
        [Required]
        [Column("MSG3_0")]
        [StringLength(50)]
        public string Msg30 { get; set; }
        [Required]
        [Column("FRM3_0")]
        [StringLength(80)]
        public string Frm30 { get; set; }
        [Column("EXEACT_0")]
        public byte Exeact0 { get; set; }
        [Required]
        [Column("CTLOBL_0")]
        [StringLength(80)]
        public string Ctlobl0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}