// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("AFCTFCY", Schema = "TESTPROD")]
    [Index(nameof(Fcy0), nameof(Prfcod0), nameof(Fnc0), Name = "AFCTFCY_AFF0", IsUnique = true)]
    [Index(nameof(Prfcod0), nameof(Fnc0), Name = "AFCTFCY_AFF1")]
    public partial class Afctfcy
    {
        [Required]
        [Column("FCY_0")]
        [StringLength(5)]
        public string Fcy0 { get; set; }
        [Required]
        [Column("PRFCOD_0")]
        [StringLength(5)]
        public string Prfcod0 { get; set; }
        [Required]
        [Column("FNC_0")]
        [StringLength(10)]
        public string Fnc0 { get; set; }
        [Required]
        [Column("OPT_0")]
        [StringLength(23)]
        public string Opt0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}