// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("APROMEN", Schema = "TESTPROD")]
    [Index(nameof(Codmen0), Name = "APROMEN_APO0", IsUnique = true)]
    public partial class Aproman
    {
        [Required]
        [Column("CODMEN_0")]
        [StringLength(10)]
        public string Codmen0 { get; set; }
        [Required]
        [Column("INTIT_0")]
        [StringLength(30)]
        public string Intit0 { get; set; }
        [Required]
        [Column("DESCR_0")]
        [StringLength(200)]
        public string Descr0 { get; set; }
        [Column("NBPROC_0")]
        public short Nbproc0 { get; set; }
        [Required]
        [Column("PROCESSUS_0")]
        [StringLength(10)]
        public string Processus0 { get; set; }
        [Required]
        [Column("PROCESSUS_1")]
        [StringLength(10)]
        public string Processus1 { get; set; }
        [Required]
        [Column("PROCESSUS_2")]
        [StringLength(10)]
        public string Processus2 { get; set; }
        [Required]
        [Column("PROCESSUS_3")]
        [StringLength(10)]
        public string Processus3 { get; set; }
        [Required]
        [Column("PROCESSUS_4")]
        [StringLength(10)]
        public string Processus4 { get; set; }
        [Required]
        [Column("PROCESSUS_5")]
        [StringLength(10)]
        public string Processus5 { get; set; }
        [Required]
        [Column("PROCESSUS_6")]
        [StringLength(10)]
        public string Processus6 { get; set; }
        [Required]
        [Column("PROCESSUS_7")]
        [StringLength(10)]
        public string Processus7 { get; set; }
        [Required]
        [Column("PROCESSUS_8")]
        [StringLength(10)]
        public string Processus8 { get; set; }
        [Required]
        [Column("PROCESSUS_9")]
        [StringLength(10)]
        public string Processus9 { get; set; }
        [Required]
        [Column("PROCESSUS_10")]
        [StringLength(10)]
        public string Processus10 { get; set; }
        [Required]
        [Column("PROCESSUS_11")]
        [StringLength(10)]
        public string Processus11 { get; set; }
        [Required]
        [Column("PROCESSUS_12")]
        [StringLength(10)]
        public string Processus12 { get; set; }
        [Required]
        [Column("PROCESSUS_13")]
        [StringLength(10)]
        public string Processus13 { get; set; }
        [Required]
        [Column("PROCESSUS_14")]
        [StringLength(10)]
        public string Processus14 { get; set; }
        [Required]
        [Column("PROCESSUS_15")]
        [StringLength(10)]
        public string Processus15 { get; set; }
        [Required]
        [Column("PROCESSUS_16")]
        [StringLength(10)]
        public string Processus16 { get; set; }
        [Required]
        [Column("PROCESSUS_17")]
        [StringLength(10)]
        public string Processus17 { get; set; }
        [Required]
        [Column("PROCESSUS_18")]
        [StringLength(10)]
        public string Processus18 { get; set; }
        [Required]
        [Column("PROCESSUS_19")]
        [StringLength(10)]
        public string Processus19 { get; set; }
        [Required]
        [Column("PROCESSUS_20")]
        [StringLength(10)]
        public string Processus20 { get; set; }
        [Required]
        [Column("PROCESSUS_21")]
        [StringLength(10)]
        public string Processus21 { get; set; }
        [Required]
        [Column("PROCESSUS_22")]
        [StringLength(10)]
        public string Processus22 { get; set; }
        [Required]
        [Column("PROCESSUS_23")]
        [StringLength(10)]
        public string Processus23 { get; set; }
        [Required]
        [Column("PROCESSUS_24")]
        [StringLength(10)]
        public string Processus24 { get; set; }
        [Required]
        [Column("PROCESSUS_25")]
        [StringLength(10)]
        public string Processus25 { get; set; }
        [Required]
        [Column("PROCESSUS_26")]
        [StringLength(10)]
        public string Processus26 { get; set; }
        [Required]
        [Column("PROCESSUS_27")]
        [StringLength(10)]
        public string Processus27 { get; set; }
        [Required]
        [Column("PROCESSUS_28")]
        [StringLength(10)]
        public string Processus28 { get; set; }
        [Required]
        [Column("PROCESSUS_29")]
        [StringLength(10)]
        public string Processus29 { get; set; }
        [Required]
        [Column("PROCESSUS_30")]
        [StringLength(10)]
        public string Processus30 { get; set; }
        [Required]
        [Column("PROCESSUS_31")]
        [StringLength(10)]
        public string Processus31 { get; set; }
        [Required]
        [Column("PROCESSUS_32")]
        [StringLength(10)]
        public string Processus32 { get; set; }
        [Required]
        [Column("PROCESSUS_33")]
        [StringLength(10)]
        public string Processus33 { get; set; }
        [Required]
        [Column("PROCESSUS_34")]
        [StringLength(10)]
        public string Processus34 { get; set; }
        [Required]
        [Column("PROCESSUS_35")]
        [StringLength(10)]
        public string Processus35 { get; set; }
        [Required]
        [Column("PROCESSUS_36")]
        [StringLength(10)]
        public string Processus36 { get; set; }
        [Required]
        [Column("PROCESSUS_37")]
        [StringLength(10)]
        public string Processus37 { get; set; }
        [Required]
        [Column("PROCESSUS_38")]
        [StringLength(10)]
        public string Processus38 { get; set; }
        [Required]
        [Column("PROCESSUS_39")]
        [StringLength(10)]
        public string Processus39 { get; set; }
        [Required]
        [Column("PROCESSUS_40")]
        [StringLength(10)]
        public string Processus40 { get; set; }
        [Required]
        [Column("PROCESSUS_41")]
        [StringLength(10)]
        public string Processus41 { get; set; }
        [Required]
        [Column("PROCESSUS_42")]
        [StringLength(10)]
        public string Processus42 { get; set; }
        [Required]
        [Column("PROCESSUS_43")]
        [StringLength(10)]
        public string Processus43 { get; set; }
        [Required]
        [Column("PROCESSUS_44")]
        [StringLength(10)]
        public string Processus44 { get; set; }
        [Required]
        [Column("PROCESSUS_45")]
        [StringLength(10)]
        public string Processus45 { get; set; }
        [Required]
        [Column("PROCESSUS_46")]
        [StringLength(10)]
        public string Processus46 { get; set; }
        [Required]
        [Column("PROCESSUS_47")]
        [StringLength(10)]
        public string Processus47 { get; set; }
        [Required]
        [Column("PROCESSUS_48")]
        [StringLength(10)]
        public string Processus48 { get; set; }
        [Required]
        [Column("PROCESSUS_49")]
        [StringLength(10)]
        public string Processus49 { get; set; }
        [Column("NIVEAU_0")]
        public byte Niveau0 { get; set; }
        [Column("NIVEAU_1")]
        public byte Niveau1 { get; set; }
        [Column("NIVEAU_2")]
        public byte Niveau2 { get; set; }
        [Column("NIVEAU_3")]
        public byte Niveau3 { get; set; }
        [Column("NIVEAU_4")]
        public byte Niveau4 { get; set; }
        [Column("NIVEAU_5")]
        public byte Niveau5 { get; set; }
        [Column("NIVEAU_6")]
        public byte Niveau6 { get; set; }
        [Column("NIVEAU_7")]
        public byte Niveau7 { get; set; }
        [Column("NIVEAU_8")]
        public byte Niveau8 { get; set; }
        [Column("NIVEAU_9")]
        public byte Niveau9 { get; set; }
        [Column("NIVEAU_10")]
        public byte Niveau10 { get; set; }
        [Column("NIVEAU_11")]
        public byte Niveau11 { get; set; }
        [Column("NIVEAU_12")]
        public byte Niveau12 { get; set; }
        [Column("NIVEAU_13")]
        public byte Niveau13 { get; set; }
        [Column("NIVEAU_14")]
        public byte Niveau14 { get; set; }
        [Column("NIVEAU_15")]
        public byte Niveau15 { get; set; }
        [Column("NIVEAU_16")]
        public byte Niveau16 { get; set; }
        [Column("NIVEAU_17")]
        public byte Niveau17 { get; set; }
        [Column("NIVEAU_18")]
        public byte Niveau18 { get; set; }
        [Column("NIVEAU_19")]
        public byte Niveau19 { get; set; }
        [Column("NIVEAU_20")]
        public byte Niveau20 { get; set; }
        [Column("NIVEAU_21")]
        public byte Niveau21 { get; set; }
        [Column("NIVEAU_22")]
        public byte Niveau22 { get; set; }
        [Column("NIVEAU_23")]
        public byte Niveau23 { get; set; }
        [Column("NIVEAU_24")]
        public byte Niveau24 { get; set; }
        [Column("NIVEAU_25")]
        public byte Niveau25 { get; set; }
        [Column("NIVEAU_26")]
        public byte Niveau26 { get; set; }
        [Column("NIVEAU_27")]
        public byte Niveau27 { get; set; }
        [Column("NIVEAU_28")]
        public byte Niveau28 { get; set; }
        [Column("NIVEAU_29")]
        public byte Niveau29 { get; set; }
        [Column("NIVEAU_30")]
        public byte Niveau30 { get; set; }
        [Column("NIVEAU_31")]
        public byte Niveau31 { get; set; }
        [Column("NIVEAU_32")]
        public byte Niveau32 { get; set; }
        [Column("NIVEAU_33")]
        public byte Niveau33 { get; set; }
        [Column("NIVEAU_34")]
        public byte Niveau34 { get; set; }
        [Column("NIVEAU_35")]
        public byte Niveau35 { get; set; }
        [Column("NIVEAU_36")]
        public byte Niveau36 { get; set; }
        [Column("NIVEAU_37")]
        public byte Niveau37 { get; set; }
        [Column("NIVEAU_38")]
        public byte Niveau38 { get; set; }
        [Column("NIVEAU_39")]
        public byte Niveau39 { get; set; }
        [Column("NIVEAU_40")]
        public byte Niveau40 { get; set; }
        [Column("NIVEAU_41")]
        public byte Niveau41 { get; set; }
        [Column("NIVEAU_42")]
        public byte Niveau42 { get; set; }
        [Column("NIVEAU_43")]
        public byte Niveau43 { get; set; }
        [Column("NIVEAU_44")]
        public byte Niveau44 { get; set; }
        [Column("NIVEAU_45")]
        public byte Niveau45 { get; set; }
        [Column("NIVEAU_46")]
        public byte Niveau46 { get; set; }
        [Column("NIVEAU_47")]
        public byte Niveau47 { get; set; }
        [Column("NIVEAU_48")]
        public byte Niveau48 { get; set; }
        [Column("NIVEAU_49")]
        public byte Niveau49 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}