// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ATEXTE", Schema = "TESTPROD")]
    [Index(nameof(Lan0), nameof(Clerec0), Name = "ATEXTE_CLEREC")]
    [Index(nameof(Numero0), nameof(Lan0), Name = "ATEXTE_DERNUM", IsUnique = true)]
    [Index(nameof(Lan0), nameof(Numero0), Name = "ATEXTE_NUMERO", IsUnique = true)]
    [Index(nameof(Lan0), nameof(Texte0), Name = "ATEXTE_TEXTE")]
    public partial class Atexte
    {
        [Required]
        [Column("CLEREC_0")]
        [StringLength(20)]
        public string Clerec0 { get; set; }
        [Column("LONG_0")]
        public short Long0 { get; set; }
        [Required]
        [Column("NOMOBJ_0")]
        [StringLength(10)]
        public string Nomobj0 { get; set; }
        [Required]
        [Column("NOMZON_0")]
        [StringLength(10)]
        public string Nomzon0 { get; set; }
        [Column("NUMERO_0")]
        public int Numero0 { get; set; }
        [Required]
        [Column("TEXTE_0")]
        [StringLength(80)]
        public string Texte0 { get; set; }
        [Column("TYPOBJ_0")]
        public byte Typobj0 { get; set; }
        [Required]
        [Column("LAN_0")]
        [StringLength(3)]
        public string Lan0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("COMMENT_0")]
        [StringLength(40)]
        public string Comment0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}