// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("AWRKPARH", Schema = "TESTPROD")]
    [Index(nameof(Code0), Name = "AWRKPARH_AWH0", IsUnique = true)]
    public partial class Awrkparh
    {
        [Required]
        [Column("CODE_0")]
        [StringLength(10)]
        public string Code0 { get; set; }
        [Column("NBDEST_0")]
        public short Nbdest0 { get; set; }
        [Column("TYPDES_0")]
        public byte Typdes0 { get; set; }
        [Column("TYPDES_1")]
        public byte Typdes1 { get; set; }
        [Column("TYPDES_2")]
        public byte Typdes2 { get; set; }
        [Column("TYPDES_3")]
        public byte Typdes3 { get; set; }
        [Column("TYPDES_4")]
        public byte Typdes4 { get; set; }
        [Column("TYPDES_5")]
        public byte Typdes5 { get; set; }
        [Column("TYPDES_6")]
        public byte Typdes6 { get; set; }
        [Column("TYPDES_7")]
        public byte Typdes7 { get; set; }
        [Column("TYPDES_8")]
        public byte Typdes8 { get; set; }
        [Column("TYPDES_9")]
        public byte Typdes9 { get; set; }
        [Column("FNCDES_0")]
        public byte Fncdes0 { get; set; }
        [Column("FNCDES_1")]
        public byte Fncdes1 { get; set; }
        [Column("FNCDES_2")]
        public byte Fncdes2 { get; set; }
        [Column("FNCDES_3")]
        public byte Fncdes3 { get; set; }
        [Column("FNCDES_4")]
        public byte Fncdes4 { get; set; }
        [Column("FNCDES_5")]
        public byte Fncdes5 { get; set; }
        [Column("FNCDES_6")]
        public byte Fncdes6 { get; set; }
        [Column("FNCDES_7")]
        public byte Fncdes7 { get; set; }
        [Column("FNCDES_8")]
        public byte Fncdes8 { get; set; }
        [Column("FNCDES_9")]
        public byte Fncdes9 { get; set; }
        [Required]
        [Column("DESTIN_0")]
        [StringLength(80)]
        public string Destin0 { get; set; }
        [Required]
        [Column("DESTIN_1")]
        [StringLength(80)]
        public string Destin1 { get; set; }
        [Required]
        [Column("DESTIN_2")]
        [StringLength(80)]
        public string Destin2 { get; set; }
        [Required]
        [Column("DESTIN_3")]
        [StringLength(80)]
        public string Destin3 { get; set; }
        [Required]
        [Column("DESTIN_4")]
        [StringLength(80)]
        public string Destin4 { get; set; }
        [Required]
        [Column("DESTIN_5")]
        [StringLength(80)]
        public string Destin5 { get; set; }
        [Required]
        [Column("DESTIN_6")]
        [StringLength(80)]
        public string Destin6 { get; set; }
        [Required]
        [Column("DESTIN_7")]
        [StringLength(80)]
        public string Destin7 { get; set; }
        [Required]
        [Column("DESTIN_8")]
        [StringLength(80)]
        public string Destin8 { get; set; }
        [Required]
        [Column("DESTIN_9")]
        [StringLength(80)]
        public string Destin9 { get; set; }
        [Required]
        [Column("NATURE_0")]
        [StringLength(20)]
        public string Nature0 { get; set; }
        [Required]
        [Column("NATURE_1")]
        [StringLength(20)]
        public string Nature1 { get; set; }
        [Required]
        [Column("NATURE_2")]
        [StringLength(20)]
        public string Nature2 { get; set; }
        [Required]
        [Column("NATURE_3")]
        [StringLength(20)]
        public string Nature3 { get; set; }
        [Required]
        [Column("NATURE_4")]
        [StringLength(20)]
        public string Nature4 { get; set; }
        [Required]
        [Column("NATURE_5")]
        [StringLength(20)]
        public string Nature5 { get; set; }
        [Required]
        [Column("NATURE_6")]
        [StringLength(20)]
        public string Nature6 { get; set; }
        [Required]
        [Column("NATURE_7")]
        [StringLength(20)]
        public string Nature7 { get; set; }
        [Required]
        [Column("NATURE_8")]
        [StringLength(20)]
        public string Nature8 { get; set; }
        [Required]
        [Column("NATURE_9")]
        [StringLength(20)]
        public string Nature9 { get; set; }
        [Column("OPTDEL_0")]
        public byte Optdel0 { get; set; }
        [Column("OPTDEL_1")]
        public byte Optdel1 { get; set; }
        [Column("OPTDEL_2")]
        public byte Optdel2 { get; set; }
        [Column("OPTDEL_3")]
        public byte Optdel3 { get; set; }
        [Column("OPTDEL_4")]
        public byte Optdel4 { get; set; }
        [Column("OPTDEL_5")]
        public byte Optdel5 { get; set; }
        [Column("OPTDEL_6")]
        public byte Optdel6 { get; set; }
        [Column("OPTDEL_7")]
        public byte Optdel7 { get; set; }
        [Column("OPTDEL_8")]
        public byte Optdel8 { get; set; }
        [Column("OPTDEL_9")]
        public byte Optdel9 { get; set; }
        [Column("ENVOI_0")]
        public byte Envoi0 { get; set; }
        [Column("ENVOI_1")]
        public byte Envoi1 { get; set; }
        [Column("ENVOI_2")]
        public byte Envoi2 { get; set; }
        [Column("ENVOI_3")]
        public byte Envoi3 { get; set; }
        [Column("ENVOI_4")]
        public byte Envoi4 { get; set; }
        [Column("ENVOI_5")]
        public byte Envoi5 { get; set; }
        [Column("ENVOI_6")]
        public byte Envoi6 { get; set; }
        [Column("ENVOI_7")]
        public byte Envoi7 { get; set; }
        [Column("ENVOI_8")]
        public byte Envoi8 { get; set; }
        [Column("ENVOI_9")]
        public byte Envoi9 { get; set; }
        [Column("SUIVI_0")]
        public byte Suivi0 { get; set; }
        [Column("SUIVI_1")]
        public byte Suivi1 { get; set; }
        [Column("SUIVI_2")]
        public byte Suivi2 { get; set; }
        [Column("SUIVI_3")]
        public byte Suivi3 { get; set; }
        [Column("SUIVI_4")]
        public byte Suivi4 { get; set; }
        [Column("SUIVI_5")]
        public byte Suivi5 { get; set; }
        [Column("SUIVI_6")]
        public byte Suivi6 { get; set; }
        [Column("SUIVI_7")]
        public byte Suivi7 { get; set; }
        [Column("SUIVI_8")]
        public byte Suivi8 { get; set; }
        [Column("SUIVI_9")]
        public byte Suivi9 { get; set; }
        [Required]
        [Column("CNDDES_0")]
        [StringLength(80)]
        public string Cnddes0 { get; set; }
        [Required]
        [Column("CNDDES_1")]
        [StringLength(80)]
        public string Cnddes1 { get; set; }
        [Required]
        [Column("CNDDES_2")]
        [StringLength(80)]
        public string Cnddes2 { get; set; }
        [Required]
        [Column("CNDDES_3")]
        [StringLength(80)]
        public string Cnddes3 { get; set; }
        [Required]
        [Column("CNDDES_4")]
        [StringLength(80)]
        public string Cnddes4 { get; set; }
        [Required]
        [Column("CNDDES_5")]
        [StringLength(80)]
        public string Cnddes5 { get; set; }
        [Required]
        [Column("CNDDES_6")]
        [StringLength(80)]
        public string Cnddes6 { get; set; }
        [Required]
        [Column("CNDDES_7")]
        [StringLength(80)]
        public string Cnddes7 { get; set; }
        [Required]
        [Column("CNDDES_8")]
        [StringLength(80)]
        public string Cnddes8 { get; set; }
        [Required]
        [Column("CNDDES_9")]
        [StringLength(80)]
        public string Cnddes9 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}