// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("BANRECD", Schema = "TESTPROD")]
    [Index(nameof(Rbknum0), nameof(Accnum0), Name = "BANRECD_BED0", IsUnique = true)]
    [Index(nameof(Accnum0), Name = "BANRECD_BED1", IsUnique = true)]
    public partial class Banrecd
    {
        [Required]
        [Column("RBKNUM_0")]
        [StringLength(20)]
        public string Rbknum0 { get; set; }
        [Column("ACCNUM_0")]
        public int Accnum0 { get; set; }
        [Required]
        [Column("ADJREA_0")]
        [StringLength(20)]
        public string Adjrea0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}