// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("BP1099PRN", Schema = "TESTPROD")]
    [Index(nameof(Yr10990), nameof(Cpy0), nameof(Bpsnum0), Name = "BP1099PRN_B9R0", IsUnique = true)]
    public partial class Bp1099prn
    {
        [Required]
        [Column("USR_0")]
        [StringLength(5)]
        public string Usr0 { get; set; }
        [Required]
        [Column("RPTCOD_0")]
        [StringLength(15)]
        public string Rptcod0 { get; set; }
        [Column("NUMREQ_0")]
        public int Numreq0 { get; set; }
        [Column("NUMLIG_0")]
        public int Numlig0 { get; set; }
        [Column("SEQREQ_0")]
        public int Seqreq0 { get; set; }
        [Required]
        [Column("BPSNUM_0")]
        [StringLength(15)]
        public string Bpsnum0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Column("YR1099_0")]
        public short Yr10990 { get; set; }
        [Column("FRM1099_0")]
        public byte Frm10990 { get; set; }
        [Column("AMT1099_0", TypeName = "numeric(27, 13)")]
        public decimal Amt10990 { get; set; }
        [Column("AMT1099_1", TypeName = "numeric(27, 13)")]
        public decimal Amt10991 { get; set; }
        [Column("AMT1099_2", TypeName = "numeric(27, 13)")]
        public decimal Amt10992 { get; set; }
        [Column("AMT1099_3", TypeName = "numeric(27, 13)")]
        public decimal Amt10993 { get; set; }
        [Column("AMT1099_4", TypeName = "numeric(27, 13)")]
        public decimal Amt10994 { get; set; }
        [Column("AMT1099_5", TypeName = "numeric(27, 13)")]
        public decimal Amt10995 { get; set; }
        [Column("AMT1099_6", TypeName = "numeric(27, 13)")]
        public decimal Amt10996 { get; set; }
        [Column("AMT1099_7", TypeName = "numeric(27, 13)")]
        public decimal Amt10997 { get; set; }
        [Column("AMT1099_8", TypeName = "numeric(27, 13)")]
        public decimal Amt10998 { get; set; }
        [Column("AMT1099_9", TypeName = "numeric(27, 13)")]
        public decimal Amt10999 { get; set; }
        [Column("AMT1099_10", TypeName = "numeric(27, 13)")]
        public decimal Amt109910 { get; set; }
        [Column("AMT1099_11", TypeName = "numeric(27, 13)")]
        public decimal Amt109911 { get; set; }
        [Column("AMT1099_12", TypeName = "numeric(27, 13)")]
        public decimal Amt109912 { get; set; }
        [Column("AMT1099_13", TypeName = "numeric(27, 13)")]
        public decimal Amt109913 { get; set; }
        [Column("AMT1099_14", TypeName = "numeric(27, 13)")]
        public decimal Amt109914 { get; set; }
        [Column("AMT1099_15", TypeName = "numeric(27, 13)")]
        public decimal Amt109915 { get; set; }
        [Column("AMT1099_16", TypeName = "numeric(27, 13)")]
        public decimal Amt109916 { get; set; }
        [Column("AMT1099_17", TypeName = "numeric(27, 13)")]
        public decimal Amt109917 { get; set; }
        [Column("AMT1099_18", TypeName = "numeric(27, 13)")]
        public decimal Amt109918 { get; set; }
        [Column("AMT1099_19", TypeName = "numeric(27, 13)")]
        public decimal Amt109919 { get; set; }
        [Required]
        [Column("BOXALPHA_0")]
        [StringLength(1)]
        public string Boxalpha0 { get; set; }
        [Required]
        [Column("BOXALPHA_1")]
        [StringLength(1)]
        public string Boxalpha1 { get; set; }
        [Required]
        [Column("BOXALPHA_2")]
        [StringLength(1)]
        public string Boxalpha2 { get; set; }
        [Required]
        [Column("BOXALPHA_3")]
        [StringLength(1)]
        public string Boxalpha3 { get; set; }
        [Required]
        [Column("BOXALPHA_4")]
        [StringLength(1)]
        public string Boxalpha4 { get; set; }
        [Required]
        [Column("BOXALPHA_5")]
        [StringLength(1)]
        public string Boxalpha5 { get; set; }
        [Required]
        [Column("BOXALPHA_6")]
        [StringLength(1)]
        public string Boxalpha6 { get; set; }
        [Required]
        [Column("BOXALPHA_7")]
        [StringLength(1)]
        public string Boxalpha7 { get; set; }
        [Required]
        [Column("BOXALPHA_8")]
        [StringLength(1)]
        public string Boxalpha8 { get; set; }
        [Required]
        [Column("BOXALPHA_9")]
        [StringLength(1)]
        public string Boxalpha9 { get; set; }
        [Required]
        [Column("BOXALPHA_10")]
        [StringLength(1)]
        public string Boxalpha10 { get; set; }
        [Required]
        [Column("BOXALPHA_11")]
        [StringLength(1)]
        public string Boxalpha11 { get; set; }
        [Required]
        [Column("BOXALPHA_12")]
        [StringLength(1)]
        public string Boxalpha12 { get; set; }
        [Required]
        [Column("BOXALPHA_13")]
        [StringLength(1)]
        public string Boxalpha13 { get; set; }
        [Required]
        [Column("BOXALPHA_14")]
        [StringLength(1)]
        public string Boxalpha14 { get; set; }
        [Required]
        [Column("BOXALPHA_15")]
        [StringLength(1)]
        public string Boxalpha15 { get; set; }
        [Required]
        [Column("BOXALPHA_16")]
        [StringLength(1)]
        public string Boxalpha16 { get; set; }
        [Required]
        [Column("BOXALPHA_17")]
        [StringLength(1)]
        public string Boxalpha17 { get; set; }
        [Required]
        [Column("BOXALPHA_18")]
        [StringLength(1)]
        public string Boxalpha18 { get; set; }
        [Required]
        [Column("BOXALPHA_19")]
        [StringLength(1)]
        public string Boxalpha19 { get; set; }
        [Required]
        [Column("STATEID_0")]
        [StringLength(15)]
        public string Stateid0 { get; set; }
        [Required]
        [Column("RESALE_0")]
        [StringLength(10)]
        public string Resale0 { get; set; }
        [Column("CLED1_0", TypeName = "datetime")]
        public DateTime Cled10 { get; set; }
        [Column("CLED2_0", TypeName = "datetime")]
        public DateTime Cled20 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}