// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("BPMISCCGF", Schema = "TESTPROD")]
    [Index(nameof(Bprtyp0), nameof(Lan0), Name = "BPMISCCGF_BPG0")]
    public partial class Bpmisccgf
    {
        [Required]
        [Column("BPRTYP_0")]
        [StringLength(10)]
        public string Bprtyp0 { get; set; }
        [Required]
        [Column("LAN_0")]
        [StringLength(10)]
        public string Lan0 { get; set; }
        [Required]
        [Column("TTRALH_0")]
        [StringLength(30)]
        public string Ttralh0 { get; set; }
        [Required]
        [Column("TTRALH_1")]
        [StringLength(30)]
        public string Ttralh1 { get; set; }
        [Required]
        [Column("TTRALH_2")]
        [StringLength(30)]
        public string Ttralh2 { get; set; }
        [Required]
        [Column("TTRALH_3")]
        [StringLength(30)]
        public string Ttralh3 { get; set; }
        [Required]
        [Column("TTRALH_4")]
        [StringLength(30)]
        public string Ttralh4 { get; set; }
        [Required]
        [Column("TTRDAT_0")]
        [StringLength(30)]
        public string Ttrdat0 { get; set; }
        [Required]
        [Column("TTRDAT_1")]
        [StringLength(30)]
        public string Ttrdat1 { get; set; }
        [Required]
        [Column("TTRDAT_2")]
        [StringLength(30)]
        public string Ttrdat2 { get; set; }
        [Required]
        [Column("TTRDAT_3")]
        [StringLength(30)]
        public string Ttrdat3 { get; set; }
        [Required]
        [Column("TTRDAT_4")]
        [StringLength(30)]
        public string Ttrdat4 { get; set; }
        [Required]
        [Column("TTRINT_0")]
        [StringLength(30)]
        public string Ttrint0 { get; set; }
        [Required]
        [Column("TTRINT_1")]
        [StringLength(30)]
        public string Ttrint1 { get; set; }
        [Required]
        [Column("TTRINT_2")]
        [StringLength(30)]
        public string Ttrint2 { get; set; }
        [Required]
        [Column("TTRINT_3")]
        [StringLength(30)]
        public string Ttrint3 { get; set; }
        [Required]
        [Column("TTRINT_4")]
        [StringLength(30)]
        public string Ttrint4 { get; set; }
        [Required]
        [Column("TTRDCB_0")]
        [StringLength(30)]
        public string Ttrdcb0 { get; set; }
        [Required]
        [Column("TTRDCB_1")]
        [StringLength(30)]
        public string Ttrdcb1 { get; set; }
        [Required]
        [Column("TTRDCB_2")]
        [StringLength(30)]
        public string Ttrdcb2 { get; set; }
        [Required]
        [Column("TTRDCB_3")]
        [StringLength(30)]
        public string Ttrdcb3 { get; set; }
        [Required]
        [Column("TTRDCB_4")]
        [StringLength(30)]
        public string Ttrdcb4 { get; set; }
        [Required]
        [Column("TTRBLC_0")]
        [StringLength(30)]
        public string Ttrblc0 { get; set; }
        [Required]
        [Column("TTRBLC_1")]
        [StringLength(30)]
        public string Ttrblc1 { get; set; }
        [Required]
        [Column("TTRBLC_2")]
        [StringLength(30)]
        public string Ttrblc2 { get; set; }
        [Required]
        [Column("TTRBLC_3")]
        [StringLength(30)]
        public string Ttrblc3 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}