// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("BUDFORCAL", Schema = "TESTPROD")]
    [Index(nameof(Budfor0), nameof(Lin0), Name = "BUDFORCAL_BUC0", IsUnique = true)]
    public partial class Budforcal
    {
        [Required]
        [Column("BUDFOR_0")]
        [StringLength(10)]
        public string Budfor0 { get; set; }
        [Required]
        [Column("DES_0")]
        [StringLength(30)]
        public string Des0 { get; set; }
        [Required]
        [Column("DESSHO_0")]
        [StringLength(10)]
        public string Dessho0 { get; set; }
        [Column("FLGDSP_0")]
        public byte Flgdsp0 { get; set; }
        [Required]
        [Column("CLCFOR_0")]
        [StringLength(250)]
        public string Clcfor0 { get; set; }
        [Column("LIN_0")]
        public short Lin0 { get; set; }
        [Column("TYP_0")]
        public byte Typ0 { get; set; }
        [Required]
        [Column("BUD_0")]
        [StringLength(3)]
        public string Bud0 { get; set; }
        [Required]
        [Column("ACC_0")]
        [StringLength(15)]
        public string Acc0 { get; set; }
        [Required]
        [Column("CCE_0")]
        [StringLength(15)]
        public string Cce0 { get; set; }
        [Required]
        [Column("CCE_1")]
        [StringLength(15)]
        public string Cce1 { get; set; }
        [Required]
        [Column("CCE_2")]
        [StringLength(15)]
        public string Cce2 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Required]
        [Column("FCY_0")]
        [StringLength(5)]
        public string Fcy0 { get; set; }
        [Column("LEDTYP_0")]
        public byte Ledtyp0 { get; set; }
        [Required]
        [Column("VER_0")]
        [StringLength(5)]
        public string Ver0 { get; set; }
        [Column("STRDAT_0", TypeName = "datetime")]
        public DateTime Strdat0 { get; set; }
        [Column("ENDDAT_0", TypeName = "datetime")]
        public DateTime Enddat0 { get; set; }
        [Column("FIYSTR_0")]
        public short Fiystr0 { get; set; }
        [Column("FIYEND_0")]
        public short Fiyend0 { get; set; }
        [Column("PERDEB_0")]
        public short Perdeb0 { get; set; }
        [Column("PERFIN_0")]
        public short Perfin0 { get; set; }
        [Column("OD_0")]
        public byte Od0 { get; set; }
        [Column("DEL_0")]
        public byte Del0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}