// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("CBLOB", Schema = "TESTPROD")]
    [Index(nameof(Codblb0), nameof(Ident10), nameof(Ident20), Name = "CBLOB_CBB0", IsUnique = true)]
    public partial class Cblob
    {
        [Required]
        [Column("CODBLB_0")]
        [StringLength(10)]
        public string Codblb0 { get; set; }
        [Required]
        [Column("IDENT1_0")]
        [StringLength(80)]
        public string Ident10 { get; set; }
        [Required]
        [Column("IDENT2_0")]
        [StringLength(80)]
        public string Ident20 { get; set; }
        [Required]
        [Column("NAMBLB_0")]
        [StringLength(30)]
        public string Namblb0 { get; set; }
        [Column("TYPBLB_0")]
        public byte Typblb0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CRETIM_0")]
        [StringLength(5)]
        public string Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDTIM_0")]
        [StringLength(5)]
        public string Updtim0 { get; set; }
        [Required]
        [Column("CRESTP_0")]
        [StringLength(14)]
        public string Crestp0 { get; set; }
        [Required]
        [Column("UPDSTP_0")]
        [StringLength(14)]
        public string Updstp0 { get; set; }
        [Required]
        [Column("IDTSGL_0")]
        [StringLength(36)]
        public string Idtsgl0 { get; set; }
        [Required]
        [Column("BLOB_0")]
        public byte[] Blob0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}