// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("DOOBPCLNK", Schema = "TESTPROD")]
    [Index(nameof(Doonum0), nameof(Bpcnum0), Name = "DOOBPCLNK_DBL0", IsUnique = true)]
    [Index(nameof(Doonum0), Name = "DOOBPCLNK_DBL1")]
    [Index(nameof(Bpcnum0), Name = "DOOBPCLNK_DBL2")]
    public partial class Doobpclnk
    {
        [Required]
        [Column("DOONUM_0")]
        [StringLength(15)]
        public string Doonum0 { get; set; }
        [Required]
        [Column("DOONAM_0")]
        [StringLength(35)]
        public string Doonam0 { get; set; }
        [Required]
        [Column("BPCNUM_0")]
        [StringLength(15)]
        public string Bpcnum0 { get; set; }
        [Required]
        [Column("BPCNAM_0")]
        [StringLength(35)]
        public string Bpcnam0 { get; set; }
        [Required]
        [Column("BPCSHO_0")]
        [StringLength(10)]
        public string Bpcsho0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}