// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("DPRMODOPT", Schema = "TESTPROD")]
    [Index(nameof(Stddpm0), nameof(Cpy0), nameof(Numdpm0), Name = "DPRMODOPT_DMO0", IsUnique = true)]
    public partial class Dprmodopt
    {
        [Required]
        [Column("STDDPM_0")]
        [StringLength(2)]
        public string Stddpm0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Column("NUMDPM_0")]
        public short Numdpm0 { get; set; }
        [Column("OPTTYP_0")]
        public byte Opttyp0 { get; set; }
        [Column("OPTCOD_0")]
        public byte Optcod0 { get; set; }
        [Column("OPTRAT_0", TypeName = "numeric(16, 7)")]
        public decimal Optrat0 { get; set; }
        [Column("STRVLYDAT_0", TypeName = "datetime")]
        public DateTime Strvlydat0 { get; set; }
        [Column("ENDVLYDAT_0", TypeName = "datetime")]
        public DateTime Endvlydat0 { get; set; }
        [Column("REFDATTYP_0")]
        public byte Refdattyp0 { get; set; }
        [Required]
        [Column("OPTCPY_0")]
        [StringLength(5)]
        public string Optcpy0 { get; set; }
        [Column("DPRPLN_0")]
        public byte Dprpln0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}