// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("EDISEG", Schema = "TESTPROD")]
    [Index(nameof(Seg0), nameof(Lig0), Name = "EDISEG_EDS0", IsUnique = true)]
    public partial class Ediseg
    {
        [Required]
        [Column("SEG_0")]
        [StringLength(3)]
        public string Seg0 { get; set; }
        [Required]
        [Column("DES_0")]
        [StringLength(50)]
        public string Des0 { get; set; }
        [Column("LIG_0")]
        public short Lig0 { get; set; }
        [Required]
        [Column("DATA_0")]
        [StringLength(4)]
        public string Data0 { get; set; }
        [Required]
        [Column("CPS_0")]
        [StringLength(4)]
        public string Cps0 { get; set; }
        [Column("STA_0")]
        public byte Sta0 { get; set; }
        [Column("FLDTYP_0")]
        public byte Fldtyp0 { get; set; }
        [Column("LONG_0")]
        public short Long0 { get; set; }
        [Required]
        [Column("INTIT_0")]
        [StringLength(50)]
        public string Intit0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}