// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("FUPGRP", Schema = "TESTPROD")]
    [Index(nameof(Grp0), Name = "FUPGRP_FGP0", IsUnique = true)]
    public partial class Fupgrp
    {
        [Required]
        [Column("GRP_0")]
        [StringLength(5)]
        public string Grp0 { get; set; }
        [Required]
        [Column("GRPNAM_0")]
        [StringLength(35)]
        public string Grpnam0 { get; set; }
        [Required]
        [Column("GRPSHO_0")]
        [StringLength(10)]
        public string Grpsho0 { get; set; }
        [Column("FUPTYP_0")]
        public byte Fuptyp0 { get; set; }
        [Column("FUPMINAMT_0", TypeName = "numeric(27, 13)")]
        public decimal Fupminamt0 { get; set; }
        [Column("FUPMAX_0")]
        public short Fupmax0 { get; set; }
        [Column("FUPCUR_0")]
        public byte Fupcur0 { get; set; }
        [Column("FUPCDT_0")]
        public byte Fupcdt0 { get; set; }
        [Column("FUPCTL_0")]
        public byte Fupctl0 { get; set; }
        [Column("FUPFCY_0")]
        public byte Fupfcy0 { get; set; }
        [Column("NBRCOP_0")]
        public short Nbrcop0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("SEUILS_0")]
        public short Seuils0 { get; set; }
        [Column("SEUILS_1")]
        public short Seuils1 { get; set; }
        [Column("SEUILS_2")]
        public short Seuils2 { get; set; }
        [Column("SEUILS_3")]
        public short Seuils3 { get; set; }
        [Column("SEUILS_4")]
        public short Seuils4 { get; set; }
        [Column("FUPMOD_0")]
        public byte Fupmod0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}