// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("FXDMVTD", Schema = "TESTPROD")]
    [Index(nameof(Idmvt0), nameof(Codzone0), nameof(Dime0), nameof(Dprpln0), Name = "FXDMVTD_FXD0", IsUnique = true)]
    public partial class Fxdmvtd
    {
        [Column("IDMVT_0")]
        public int Idmvt0 { get; set; }
        [Required]
        [Column("CODZONE_0")]
        [StringLength(12)]
        public string Codzone0 { get; set; }
        [Required]
        [Column("DIME_0")]
        [StringLength(10)]
        public string Dime0 { get; set; }
        [Column("DPRPLN_0")]
        public short Dprpln0 { get; set; }
        [Required]
        [Column("VALZONE_0")]
        [StringLength(250)]
        public string Valzone0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}