// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("GACCDEF", Schema = "TESTPROD")]
    [Index(nameof(Coaori0), nameof(Coaden0), nameof(Coastr0), Name = "GACCDEF_GCF0", IsUnique = true)]
    public partial class Gaccdef
    {
        [Required]
        [Column("COAORI_0")]
        [StringLength(3)]
        public string Coaori0 { get; set; }
        [Required]
        [Column("COADEN_0")]
        [StringLength(3)]
        public string Coaden0 { get; set; }
        [Required]
        [Column("COASTR_0")]
        [StringLength(10)]
        public string Coastr0 { get; set; }
        [Required]
        [Column("ACC_0")]
        [StringLength(15)]
        public string Acc0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}