// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("GDIE", Schema = "TESTPROD")]
    [Index(nameof(Die0), Name = "GDIE_DIE0", IsUnique = true)]
    public partial class Gdie
    {
        [Required]
        [Column("DIE_0")]
        [StringLength(3)]
        public string Die0 { get; set; }
        [Required]
        [Column("DES_0")]
        [StringLength(30)]
        public string Des0 { get; set; }
        [Required]
        [Column("DESSHO_0")]
        [StringLength(10)]
        public string Dessho0 { get; set; }
        [Required]
        [Column("ACS_0")]
        [StringLength(10)]
        public string Acs0 { get; set; }
        [Required]
        [Column("CCEFMT_0")]
        [StringLength(15)]
        public string Ccefmt0 { get; set; }
        [Column("CREAUT_0")]
        public byte Creaut0 { get; set; }
        [Column("PRJMGT_0")]
        public byte Prjmgt0 { get; set; }
        [Column("FLGMODACE_0")]
        public byte Flgmodace0 { get; set; }
        [Column("ENT_0")]
        public short Ent0 { get; set; }
        [Column("ENV_0")]
        public short Env0 { get; set; }
        [Required]
        [Column("CCEMIS_0")]
        [StringLength(15)]
        public string Ccemis0 { get; set; }
        [Required]
        [Column("CCEMIS_1")]
        [StringLength(15)]
        public string Ccemis1 { get; set; }
        [Required]
        [Column("CCEMIS_2")]
        [StringLength(15)]
        public string Ccemis2 { get; set; }
        [Required]
        [Column("CCEMIS_3")]
        [StringLength(15)]
        public string Ccemis3 { get; set; }
        [Required]
        [Column("CCEMIS_4")]
        [StringLength(15)]
        public string Ccemis4 { get; set; }
        [Required]
        [Column("CCEMIS_5")]
        [StringLength(15)]
        public string Ccemis5 { get; set; }
        [Required]
        [Column("CCEMIS_6")]
        [StringLength(15)]
        public string Ccemis6 { get; set; }
        [Required]
        [Column("CCEMIS_7")]
        [StringLength(15)]
        public string Ccemis7 { get; set; }
        [Required]
        [Column("CCEMIS_8")]
        [StringLength(15)]
        public string Ccemis8 { get; set; }
        [Required]
        [Column("CCEMIS_9")]
        [StringLength(15)]
        public string Ccemis9 { get; set; }
        [Required]
        [Column("CCECRE_0")]
        [StringLength(20)]
        public string Ccecre0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}