// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("HD7CLOB", Schema = "TESTPROD")]
    [Index(nameof(Num0), nameof(Typ0), nameof(Pronum0), Name = "HD7CLOB_HD70", IsUnique = true)]
    [Index(nameof(Pronum0), Name = "HD7CLOB_HD71")]
    public partial class Hd7clob
    {
        [Required]
        [Column("NUM_0")]
        [StringLength(30)]
        public string Num0 { get; set; }
        [Required]
        [Column("TYP_0")]
        [StringLength(10)]
        public string Typ0 { get; set; }
        [Column("PRONUM_0")]
        public int Pronum0 { get; set; }
        [Required]
        [Column("CLOB_0")]
        public string Clob0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}