// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("HISTOOMM", Schema = "TESTPROD")]
    [Index(nameof(Himnum0), Name = "HISTOOMM_HIM0", IsUnique = true)]
    [Index(nameof(Ommnum0), nameof(Ccnnum0), Name = "HISTOOMM_HIM1")]
    [Index(nameof(Ommnum0), nameof(Bprnum0), nameof(Ccnnum0), Name = "HISTOOMM_HIM2")]
    [Index(nameof(Ommnum0), nameof(Bprnum0), Name = "HISTOOMM_HIM3")]
    [Index(nameof(Bprnum0), Name = "HISTOOMM_HIM4")]
    [Index(nameof(Ccnnum0), Name = "HISTOOMM_HIM5")]
    public partial class Histoomm
    {
        [Required]
        [Column("HIMNUM_0")]
        [StringLength(20)]
        public string Himnum0 { get; set; }
        [Required]
        [Column("OMMNUM_0")]
        [StringLength(20)]
        public string Ommnum0 { get; set; }
        [Required]
        [Column("BPRNUM_0")]
        [StringLength(15)]
        public string Bprnum0 { get; set; }
        [Required]
        [Column("CCNNUM_0")]
        [StringLength(15)]
        public string Ccnnum0 { get; set; }
        [Column("DATSND_0", TypeName = "datetime")]
        public DateTime Datsnd0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}