// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("HONPRV", Schema = "TESTPROD")]
    [Index(nameof(Prvnum0), Name = "HONPRV_PRV0", IsUnique = true)]
    public partial class Honprv
    {
        [Required]
        [Column("PRVNUM_0")]
        [StringLength(15)]
        public string Prvnum0 { get; set; }
        [Required]
        [Column("SURNAM_0")]
        [StringLength(30)]
        public string Surnam0 { get; set; }
        [Required]
        [Column("FIRNAM_0")]
        [StringLength(20)]
        public string Firnam0 { get; set; }
        [Required]
        [Column("PRVNAM_0")]
        [StringLength(50)]
        public string Prvnam0 { get; set; }
        [Required]
        [Column("JOB_0")]
        [StringLength(30)]
        public string Job0 { get; set; }
        [Required]
        [Column("CRN_0")]
        [StringLength(20)]
        public string Crn0 { get; set; }
        [Required]
        [Column("ADDCPL_0")]
        [StringLength(40)]
        public string Addcpl0 { get; set; }
        [Required]
        [Column("STREETNUM_0")]
        [StringLength(4)]
        public string Streetnum0 { get; set; }
        [Required]
        [Column("ABC_0")]
        [StringLength(1)]
        public string Abc0 { get; set; }
        [Required]
        [Column("STREET_0")]
        [StringLength(40)]
        public string Street0 { get; set; }
        [Required]
        [Column("POSCTYCOD_0")]
        [StringLength(5)]
        public string Posctycod0 { get; set; }
        [Required]
        [Column("CTYNAM_0")]
        [StringLength(40)]
        public string Ctynam0 { get; set; }
        [Required]
        [Column("POSCOD_0")]
        [StringLength(5)]
        public string Poscod0 { get; set; }
        [Required]
        [Column("POSCTY_0")]
        [StringLength(26)]
        public string Poscty0 { get; set; }
        [Required]
        [Column("CRYCOD_0")]
        [StringLength(3)]
        public string Crycod0 { get; set; }
        [Required]
        [Column("TEL_0")]
        [StringLength(20)]
        public string Tel0 { get; set; }
        [Required]
        [Column("FAX_0")]
        [StringLength(20)]
        public string Fax0 { get; set; }
        [Column("NFLG1_0")]
        public byte Nflg10 { get; set; }
        [Column("LFLG1_0")]
        public byte Lflg10 { get; set; }
        [Column("VFLG1_0")]
        public byte Vflg10 { get; set; }
        [Column("AFLG1_0")]
        public byte Aflg10 { get; set; }
        [Column("FFLG2_0")]
        public byte Fflg20 { get; set; }
        [Column("RFLG2_0")]
        public byte Rflg20 { get; set; }
        [Column("PFLG2_0")]
        public byte Pflg20 { get; set; }
        [Column("RFLG3_0")]
        public byte Rflg30 { get; set; }
        [Column("DFLG3_0")]
        public byte Dflg30 { get; set; }
        [Column("PHYPSL_0")]
        public byte Phypsl0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}