// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ITCDET", Schema = "TESTPROD")]
    [Index(nameof(Uid0), nameof(Codfic0), nameof(Cle0), nameof(Brdcod0), Name = "ITCDET_ICD1", IsUnique = true)]
    [Index(nameof(Itmref0), nameof(Stofcy0), Name = "ITCDET_ICD2")]
    public partial class Itcdet
    {
        [Column("UID_0")]
        public int Uid0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("CODFIC_0")]
        [StringLength(12)]
        public string Codfic0 { get; set; }
        [Required]
        [Column("CLE_0")]
        [StringLength(100)]
        public string Cle0 { get; set; }
        [Column("BRDCOD_0")]
        public short Brdcod0 { get; set; }
        [Column("MATCST_0", TypeName = "numeric(19, 5)")]
        public decimal Matcst0 { get; set; }
        [Column("MACCST_0", TypeName = "numeric(19, 5)")]
        public decimal Maccst0 { get; set; }
        [Column("LABCST_0", TypeName = "numeric(19, 5)")]
        public decimal Labcst0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}