// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("MFGANL", Schema = "TESTPROD")]
    [Index(nameof(Mfgfcy0), nameof(Mfgnum0), nameof(Perend0), Name = "MFGANL_MFA0", IsUnique = true)]
    public partial class Mfganl
    {
        [Required]
        [Column("MFGFCY_0")]
        [StringLength(5)]
        public string Mfgfcy0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Column("MFGLIN_0")]
        public int Mfglin0 { get; set; }
        [Column("PERSTR_0", TypeName = "datetime")]
        public DateTime Perstr0 { get; set; }
        [Column("PEREND_0", TypeName = "datetime")]
        public DateTime Perend0 { get; set; }
        [Column("PERDAYNBR_0")]
        public short Perdaynbr0 { get; set; }
        [Column("OPENBR_0")]
        public short Openbr0 { get; set; }
        [Column("MATNBR_0")]
        public short Matnbr0 { get; set; }
        [Column("DELDAYNBR_0", TypeName = "numeric(14, 3)")]
        public decimal Deldaynbr0 { get; set; }
        [Column("MFGCPLLTI_0", TypeName = "numeric(14, 3)")]
        public decimal Mfgcpllti0 { get; set; }
        [Column("MFGSCDLTI_0", TypeName = "numeric(14, 3)")]
        public decimal Mfgscdlti0 { get; set; }
        [Column("MFGLTI_0", TypeName = "numeric(9, 4)")]
        public decimal Mfglti0 { get; set; }
        [Column("STDTIMSUM_0", TypeName = "numeric(14, 3)")]
        public decimal Stdtimsum0 { get; set; }
        [Column("EXTTIMSUM_0", TypeName = "numeric(14, 3)")]
        public decimal Exttimsum0 { get; set; }
        [Column("CPLTIMSUM_0", TypeName = "numeric(14, 3)")]
        public decimal Cpltimsum0 { get; set; }
        [Column("SHR_0", TypeName = "numeric(10, 4)")]
        public decimal Shr0 { get; set; }
        [Column("CPLSHR_0", TypeName = "numeric(10, 4)")]
        public decimal Cplshr0 { get; set; }
        [Column("OPEQTYEFF_0", TypeName = "numeric(14, 3)")]
        public decimal Opeqtyeff0 { get; set; }
        [Column("OPETIMEFF_0", TypeName = "numeric(14, 3)")]
        public decimal Opetimeff0 { get; set; }
        [Column("MATQTYEFF_0", TypeName = "numeric(14, 3)")]
        public decimal Matqtyeff0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}