// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("MFGBSMWRK", Schema = "TESTPROD")]
    [Index(nameof(Pronum0), nameof(Lin0), Name = "MFGBSMWRK_MBW0", IsUnique = true)]
    public partial class Mfgbsmwrk
    {
        [Column("PRONUM_0")]
        public int Pronum0 { get; set; }
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Column("MFGLIN_0")]
        public int Mfglin0 { get; set; }
        [Column("BOMSEQ_0")]
        public short Bomseq0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("LIN_0")]
        public int Lin0 { get; set; }
        [Column("LINTYP_0")]
        public short Lintyp0 { get; set; }
        [Column("ALLTYP_0")]
        public byte Alltyp0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("LOC_0")]
        [StringLength(10)]
        public string Loc0 { get; set; }
        [Required]
        [Column("LOT_0")]
        [StringLength(15)]
        public string Lot0 { get; set; }
        [Column("QTY_0", TypeName = "numeric(28, 13)")]
        public decimal Qty0 { get; set; }
        [Required]
        [Column("UOM_0")]
        [StringLength(3)]
        public string Uom0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}