// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("MFGOPE", Schema = "TESTPROD")]
    [Index(nameof(Mfgnum0), nameof(Openum0), nameof(Opesplnum0), Name = "MFGOPE_MFO0", IsUnique = true)]
    [Index(nameof(Pohnum0), nameof(Poplin0), nameof(Popseq0), Name = "MFGOPE_MFO1")]
    [Index(nameof(Mfgfcy0), nameof(Extwst0), nameof(Schsbb0), nameof(Mfgnum0), Name = "MFGOPE_MFO2")]
    public partial class Mfgope
    {
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Column("OPENUM_0")]
        public short Openum0 { get; set; }
        [Column("ROUOPENUM_0")]
        public short Rouopenum0 { get; set; }
        [Column("OPESPLNUM_0")]
        public short Opesplnum0 { get; set; }
        [Column("RPLIND_0")]
        public short Rplind0 { get; set; }
        [Column("MFGSTA_0")]
        public byte Mfgsta0 { get; set; }
        [Required]
        [Column("PLNFCY_0")]
        [StringLength(5)]
        public string Plnfcy0 { get; set; }
        [Required]
        [Column("MFGFCY_0")]
        [StringLength(5)]
        public string Mfgfcy0 { get; set; }
        [Required]
        [Column("STDWST_0")]
        [StringLength(8)]
        public string Stdwst0 { get; set; }
        [Required]
        [Column("EXTWST_0")]
        [StringLength(8)]
        public string Extwst0 { get; set; }
        [Required]
        [Column("CPLWST_0")]
        [StringLength(8)]
        public string Cplwst0 { get; set; }
        [Required]
        [Column("STDLAB_0")]
        [StringLength(8)]
        public string Stdlab0 { get; set; }
        [Required]
        [Column("EXTLAB_0")]
        [StringLength(8)]
        public string Extlab0 { get; set; }
        [Required]
        [Column("CPLLAB_0")]
        [StringLength(8)]
        public string Cpllab0 { get; set; }
        [Column("SETLABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Setlabcoe0 { get; set; }
        [Column("OPELABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Opelabcoe0 { get; set; }
        [Column("OPESTA_0")]
        public byte Opesta0 { get; set; }
        [Column("INFCAPSTR_0", TypeName = "datetime")]
        public DateTime Infcapstr0 { get; set; }
        [Column("INFCAPEND_0", TypeName = "datetime")]
        public DateTime Infcapend0 { get; set; }
        [Column("OPESTR_0", TypeName = "datetime")]
        public DateTime Opestr0 { get; set; }
        [Column("OPEEND_0", TypeName = "datetime")]
        public DateTime Opeend0 { get; set; }
        [Column("TRKFIRST_0", TypeName = "datetime")]
        public DateTime Trkfirst0 { get; set; }
        [Column("TRKLAST_0", TypeName = "datetime")]
        public DateTime Trklast0 { get; set; }
        [Column("TRKFIRSTC_0", TypeName = "datetime")]
        public DateTime Trkfirstc0 { get; set; }
        [Column("TRKLASTC_0", TypeName = "datetime")]
        public DateTime Trklastc0 { get; set; }
        [Column("FRCSTRDAT_0", TypeName = "datetime")]
        public DateTime Frcstrdat0 { get; set; }
        [Required]
        [Column("FRCSTRHOU_0")]
        [StringLength(5)]
        public string Frcstrhou0 { get; set; }
        [Required]
        [Column("ROODES_0")]
        [StringLength(30)]
        public string Roodes0 { get; set; }
        [Required]
        [Column("OPEUOM_0")]
        [StringLength(3)]
        public string Opeuom0 { get; set; }
        [Column("OPESTUCOE_0", TypeName = "numeric(18, 7)")]
        public decimal Opestucoe0 { get; set; }
        [Column("TIMUOMCOD_0")]
        public byte Timuomcod0 { get; set; }
        [Column("ROOTIMCOD_0")]
        public byte Rootimcod0 { get; set; }
        [Column("TIMCOD_0")]
        public byte Timcod0 { get; set; }
        [Column("BASQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Basqty0 { get; set; }
        [Column("CAD_0", TypeName = "numeric(15, 5)")]
        public decimal Cad0 { get; set; }
        [Required]
        [Column("OPEPLNNUM_0")]
        [StringLength(20)]
        public string Opeplnnum0 { get; set; }
        [Required]
        [Column("OPEROUPCT_0")]
        [StringLength(20)]
        public string Operoupct0 { get; set; }
        [Required]
        [Column("TECCRD_0")]
        [StringLength(8)]
        public string Teccrd0 { get; set; }
        [Required]
        [Column("EQUNUM_0")]
        [StringLength(20)]
        public string Equnum0 { get; set; }
        [Required]
        [Column("FXGNUM_0")]
        [StringLength(20)]
        public string Fxgnum0 { get; set; }
        [Required]
        [Column("PRGNUM_0")]
        [StringLength(20)]
        public string Prgnum0 { get; set; }
        [Column("EFF_0", TypeName = "numeric(10, 4)")]
        public decimal Eff0 { get; set; }
        [Column("SHR_0", TypeName = "numeric(10, 4)")]
        public decimal Shr0 { get; set; }
        [Column("WSTEFF_0", TypeName = "numeric(10, 4)")]
        public decimal Wsteff0 { get; set; }
        [Column("STDWSTNBR_0")]
        public short Stdwstnbr0 { get; set; }
        [Column("EXTWSTNBR_0")]
        public short Extwstnbr0 { get; set; }
        [Column("CPLWSTNBR_0")]
        public short Cplwstnbr0 { get; set; }
        [Column("STDLABNBR_0")]
        public short Stdlabnbr0 { get; set; }
        [Column("EXTLABNBR_0")]
        public short Extlabnbr0 { get; set; }
        [Column("CPLLABNBR_0")]
        public short Cpllabnbr0 { get; set; }
        [Column("PRPTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Prptim0 { get; set; }
        [Column("STDSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Stdsettim0 { get; set; }
        [Column("EXTSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Extsettim0 { get; set; }
        [Column("CPLSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Cplsettim0 { get; set; }
        [Column("STDUNTTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Stdunttim0 { get; set; }
        [Column("EXTUNTTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Extunttim0 { get; set; }
        [Column("CPLUNTTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Cplunttim0 { get; set; }
        [Column("STDOPETIM_0", TypeName = "numeric(13, 5)")]
        public decimal Stdopetim0 { get; set; }
        [Column("EXTOPETIM_0", TypeName = "numeric(13, 5)")]
        public decimal Extopetim0 { get; set; }
        [Column("CPLOPETIM_0", TypeName = "numeric(13, 5)")]
        public decimal Cplopetim0 { get; set; }
        [Column("WAITIM_0", TypeName = "numeric(13, 5)")]
        public decimal Waitim0 { get; set; }
        [Column("PSPTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Psptim0 { get; set; }
        [Column("EXTSTUQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Extstuqty0 { get; set; }
        [Column("STDQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Stdqty0 { get; set; }
        [Column("EXTQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Extqty0 { get; set; }
        [Column("CPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Cplqty0 { get; set; }
        [Column("REJCPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Rejcplqty0 { get; set; }
        [Column("QUACPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Quacplqty0 { get; set; }
        [Column("SCOCOD_0")]
        public byte Scocod0 { get; set; }
        [Required]
        [Column("SCOWST_0")]
        [StringLength(8)]
        public string Scowst0 { get; set; }
        [Required]
        [Column("SCOITMREF_0")]
        [StringLength(20)]
        public string Scoitmref0 { get; set; }
        [Column("SCOLTI_0", TypeName = "numeric(9, 4)")]
        public decimal Scolti0 { get; set; }
        [Required]
        [Column("SCOPUU_0")]
        [StringLength(3)]
        public string Scopuu0 { get; set; }
        [Column("OPESTRCOE_0", TypeName = "numeric(18, 7)")]
        public decimal Opestrcoe0 { get; set; }
        [Column("EXTSTRQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Extstrqty0 { get; set; }
        [Required]
        [Column("OPSNUM_0")]
        [StringLength(20)]
        public string Opsnum0 { get; set; }
        [Required]
        [Column("WIPNUM_0")]
        [StringLength(20)]
        public string Wipnum0 { get; set; }
        [Required]
        [Column("POHNUM_0")]
        [StringLength(20)]
        public string Pohnum0 { get; set; }
        [Column("POPLIN_0")]
        public int Poplin0 { get; set; }
        [Column("POPSEQ_0")]
        public int Popseq0 { get; set; }
        [Required]
        [Column("BPRNUM_0")]
        [StringLength(15)]
        public string Bprnum0 { get; set; }
        [Required]
        [Column("BPAADD_0")]
        [StringLength(7)]
        public string Bpaadd0 { get; set; }
        [Column("REFPRI_0", TypeName = "numeric(19, 5)")]
        public decimal Refpri0 { get; set; }
        [Column("EXTPRI_0", TypeName = "numeric(19, 5)")]
        public decimal Extpri0 { get; set; }
        [Column("CPLPRI_0", TypeName = "numeric(19, 5)")]
        public decimal Cplpri0 { get; set; }
        [Column("CPLCRG_0", TypeName = "numeric(19, 5)")]
        public decimal Cplcrg0 { get; set; }
        [Column("INVQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Invqty0 { get; set; }
        [Column("SPLCOD_0")]
        public byte Splcod0 { get; set; }
        [Column("SPLMAXNBR_0")]
        public short Splmaxnbr0 { get; set; }
        [Column("FITCAPSTR_0", TypeName = "datetime")]
        public DateTime Fitcapstr0 { get; set; }
        [Column("FITCAPEND_0", TypeName = "datetime")]
        public DateTime Fitcapend0 { get; set; }
        [Column("OPENUMLEV_0")]
        public short Openumlev0 { get; set; }
        [Column("ALTOPECOD_0")]
        public byte Altopecod0 { get; set; }
        [Required]
        [Column("RSTMAC_0")]
        [StringLength(5)]
        public string Rstmac0 { get; set; }
        [Required]
        [Column("SCHGRP_0")]
        [StringLength(15)]
        public string Schgrp0 { get; set; }
        [Required]
        [Column("SCHSBB_0")]
        [StringLength(15)]
        public string Schsbb0 { get; set; }
        [Column("GRPSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Grpsettim0 { get; set; }
        [Column("MFGPIO_0")]
        public byte Mfgpio0 { get; set; }
        [Column("MFOTRKFLG_0")]
        public byte Mfotrkflg0 { get; set; }
        [Required]
        [Column("MFOTEX_0")]
        [StringLength(12)]
        public string Mfotex0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}