// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("OPERATIONS", Schema = "TESTPROD")]
    [Index(nameof(Opsnum0), Name = "OPERATIONS_OPS0", IsUnique = true)]
    [Index(nameof(Mfgnum0), nameof(Openum0), nameof(Opesplnum0), Name = "OPERATIONS_OPS1", IsUnique = true)]
    [Index(nameof(Pohnum0), nameof(Poplin0), nameof(Popseq0), Name = "OPERATIONS_OPS2")]
    [Index(nameof(Mfgfcy0), nameof(Opestr0), nameof(Mfgnum0), Name = "OPERATIONS_OPS3")]
    public partial class Operation
    {
        [Column("OPSTYP_0")]
        public byte Opstyp0 { get; set; }
        [Column("OPSSTA_0")]
        public byte Opssta0 { get; set; }
        [Required]
        [Column("OPSNUM_0")]
        [StringLength(20)]
        public string Opsnum0 { get; set; }
        [Required]
        [Column("PLNFCY_0")]
        [StringLength(5)]
        public string Plnfcy0 { get; set; }
        [Required]
        [Column("MFGFCY_0")]
        [StringLength(5)]
        public string Mfgfcy0 { get; set; }
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Required]
        [Column("PJT_0")]
        [StringLength(20)]
        public string Pjt0 { get; set; }
        [Column("OPENUM_0")]
        public short Openum0 { get; set; }
        [Column("ROUOPENUM_0")]
        public short Rouopenum0 { get; set; }
        [Column("OPESPLNUM_0")]
        public short Opesplnum0 { get; set; }
        [Column("OPESTR_0", TypeName = "datetime")]
        public DateTime Opestr0 { get; set; }
        [Column("OPEEND_0", TypeName = "datetime")]
        public DateTime Opeend0 { get; set; }
        [Column("INFCAPSTR_0", TypeName = "datetime")]
        public DateTime Infcapstr0 { get; set; }
        [Column("INFCAPEND_0", TypeName = "datetime")]
        public DateTime Infcapend0 { get; set; }
        [Column("FITCAPSTR_0", TypeName = "datetime")]
        public DateTime Fitcapstr0 { get; set; }
        [Column("FITCAPEND_0", TypeName = "datetime")]
        public DateTime Fitcapend0 { get; set; }
        [Column("OPESTA_0")]
        public byte Opesta0 { get; set; }
        [Column("EXTWSTTYP_0")]
        public byte Extwsttyp0 { get; set; }
        [Required]
        [Column("EXTWST_0")]
        [StringLength(8)]
        public string Extwst0 { get; set; }
        [Required]
        [Column("CPLWST_0")]
        [StringLength(8)]
        public string Cplwst0 { get; set; }
        [Required]
        [Column("OPEUOM_0")]
        [StringLength(3)]
        public string Opeuom0 { get; set; }
        [Column("OPESTUCOE_0", TypeName = "numeric(18, 7)")]
        public decimal Opestucoe0 { get; set; }
        [Column("EXTQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Extqty0 { get; set; }
        [Column("CPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Cplqty0 { get; set; }
        [Column("QUACPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Quacplqty0 { get; set; }
        [Column("REJCPLQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Rejcplqty0 { get; set; }
        [Column("ROOTIMCOD_0")]
        public byte Rootimcod0 { get; set; }
        [Column("TIMUOMCOD_0")]
        public byte Timuomcod0 { get; set; }
        [Column("PRPTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Prptim0 { get; set; }
        [Column("EXTSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Extsettim0 { get; set; }
        [Column("CPLSETTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Cplsettim0 { get; set; }
        [Column("EXTOPETIM_0", TypeName = "numeric(13, 5)")]
        public decimal Extopetim0 { get; set; }
        [Column("CPLOPETIM_0", TypeName = "numeric(13, 5)")]
        public decimal Cplopetim0 { get; set; }
        [Column("WAITIM_0", TypeName = "numeric(13, 5)")]
        public decimal Waitim0 { get; set; }
        [Column("PSPTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Psptim0 { get; set; }
        [Required]
        [Column("EXTLAB_0")]
        [StringLength(8)]
        public string Extlab0 { get; set; }
        [Required]
        [Column("CPLLAB_0")]
        [StringLength(8)]
        public string Cpllab0 { get; set; }
        [Column("EXTWSTNBR_0")]
        public short Extwstnbr0 { get; set; }
        [Column("CPLWSTNBR_0")]
        public short Cplwstnbr0 { get; set; }
        [Column("EXTLABNBR_0")]
        public short Extlabnbr0 { get; set; }
        [Column("CPLLABNBR_0")]
        public short Cpllabnbr0 { get; set; }
        [Column("SETLABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Setlabcoe0 { get; set; }
        [Column("OPELABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Opelabcoe0 { get; set; }
        [Column("SCOFLG_0")]
        public byte Scoflg0 { get; set; }
        [Required]
        [Column("SCOWST_0")]
        [StringLength(8)]
        public string Scowst0 { get; set; }
        [Required]
        [Column("SCOITMREF_0")]
        [StringLength(20)]
        public string Scoitmref0 { get; set; }
        [Column("SCOLTI_0", TypeName = "numeric(9, 4)")]
        public decimal Scolti0 { get; set; }
        [Required]
        [Column("BPSNUM_0")]
        [StringLength(15)]
        public string Bpsnum0 { get; set; }
        [Required]
        [Column("POHNUM_0")]
        [StringLength(20)]
        public string Pohnum0 { get; set; }
        [Column("POPLIN_0")]
        public int Poplin0 { get; set; }
        [Column("POPSEQ_0")]
        public int Popseq0 { get; set; }
        [Required]
        [Column("WIPNUM_0")]
        [StringLength(20)]
        public string Wipnum0 { get; set; }
        [Column("ORI_0")]
        public byte Ori0 { get; set; }
        [Required]
        [Column("SCHGRP_0")]
        [StringLength(15)]
        public string Schgrp0 { get; set; }
        [Required]
        [Column("SCHSBB_0")]
        [StringLength(15)]
        public string Schsbb0 { get; set; }
        [Required]
        [Column("ABBFIL_0")]
        [StringLength(3)]
        public string Abbfil0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}