// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ORDCOV", Schema = "TESTPROD")]
    [Index(nameof(Vcrtypdst0), nameof(Vcrnumdst0), nameof(Vcrlindst0), nameof(Vcrseqdst0), nameof(Wipstadst0), Name = "ORDCOV_ORC0")]
    [Index(nameof(Vcrtyp0), nameof(Vcrnum0), nameof(Vcrlin0), nameof(Vcrseq0), Name = "ORDCOV_ORC1")]
    public partial class Ordcov
    {
        [Column("WIPTYP_0")]
        public byte Wiptyp0 { get; set; }
        [Column("WIPSTA_0")]
        public byte Wipsta0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Required]
        [Column("ORIFCY_0")]
        [StringLength(5)]
        public string Orifcy0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("PJT_0")]
        [StringLength(20)]
        public string Pjt0 { get; set; }
        [Required]
        [Column("BPRNUM_0")]
        [StringLength(15)]
        public string Bprnum0 { get; set; }
        [Column("VCRTYP_0")]
        public byte Vcrtyp0 { get; set; }
        [Required]
        [Column("VCRNUM_0")]
        [StringLength(20)]
        public string Vcrnum0 { get; set; }
        [Column("VCRLIN_0")]
        public int Vcrlin0 { get; set; }
        [Column("VCRSEQ_0")]
        public int Vcrseq0 { get; set; }
        [Column("STRDAT_0", TypeName = "datetime")]
        public DateTime Strdat0 { get; set; }
        [Column("ENDDAT_0", TypeName = "datetime")]
        public DateTime Enddat0 { get; set; }
        [Column("EXTQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Extqty0 { get; set; }
        [Column("COVQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Covqty0 { get; set; }
        [Column("FMI_0")]
        public byte Fmi0 { get; set; }
        [Column("VCRTYPORI_0")]
        public byte Vcrtypori0 { get; set; }
        [Required]
        [Column("VCRNUMORI_0")]
        [StringLength(20)]
        public string Vcrnumori0 { get; set; }
        [Column("VCRLINORI_0")]
        public int Vcrlinori0 { get; set; }
        [Column("VCRSEQORI_0")]
        public int Vcrseqori0 { get; set; }
        [Required]
        [Column("ITMREFORI_0")]
        [StringLength(20)]
        public string Itmrefori0 { get; set; }
        [Column("BOMALT_0")]
        public short Bomalt0 { get; set; }
        [Column("BOMOPE_0")]
        public short Bomope0 { get; set; }
        [Column("PIO_0")]
        public byte Pio0 { get; set; }
        [Column("ORI_0")]
        public byte Ori0 { get; set; }
        [Required]
        [Column("ABBFIL_0")]
        [StringLength(3)]
        public string Abbfil0 { get; set; }
        [Column("VCRTYPDST_0")]
        public byte Vcrtypdst0 { get; set; }
        [Required]
        [Column("VCRNUMDST_0")]
        [StringLength(20)]
        public string Vcrnumdst0 { get; set; }
        [Column("VCRLINDST_0")]
        public int Vcrlindst0 { get; set; }
        [Column("VCRSEQDST_0")]
        public int Vcrseqdst0 { get; set; }
        [Column("WIPSTADST_0")]
        public byte Wipstadst0 { get; set; }
        [Column("WIPTYPDST_0")]
        public byte Wiptypdst0 { get; set; }
        [Required]
        [Column("ROUNUM_0")]
        [StringLength(20)]
        public string Rounum0 { get; set; }
        [Column("ROUALT_0")]
        public short Roualt0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}