using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace com.orthofeet.Entities
{
    [Table("SORDER", Schema = "PROD")]
    public class OrderHeader
    {
        [Key]
        public int ROWID { get; set;}
        public short ALLLINNBR_0 { get; set;}
        public byte ALLSTA_0 { get; set;}
        public byte ALLTYP_0 { get; set;}
        public decimal AMTTAX_0 { get; set;}
        public byte APPFLG_0 { get; set;}
        public decimal BASTAX_0 { get; set;}
        public byte BETCPY_0 { get; set;}
        public byte BETFCY_0 { get; set;}
        public string BPAADD_0 { get; set;}
        public string BPAINV_0 { get; set;}
        public string BPAORD_0 { get; set;}
        public string BPAPYR_0 { get; set;}
        public string BPCADDLIG_0 { get; set;}
        public string BPCADDLIG_1 { get; set;}
        public string BPCADDLIG_2 { get; set;}
        public string BPCCRY_0 { get; set;}
        public string BPCCRYNAM_0 { get; set;}
        public string BPCCTY_0 { get; set;}
        public string BPCGRU_0 { get; set;}
        public string BPCINV_0 { get; set;}
        public string BPCNAM_0 { get; set;}
        public string BPCNAM_1 { get; set;}
        public string BPCORD_0 { get; set;}
        public string BPCPOSCOD_0 { get; set;}
        public string BPCPYR_0 { get; set;}
        public string BPCSAT_0 { get; set;}
        public string BPDADDLIG_0 { get; set;}
        public string BPDADDLIG_1 { get; set;}
        public string BPDADDLIG_2 { get; set;}
        public string BPDCRY_0 { get; set;}
        public string BPDCRYNAM_0 { get; set;}
        public string BPDCTY_0 { get; set;}
        public string BPDNAM_0 { get; set;}
        public string BPDNAM_1 { get; set;}
        public string BPDPOSCOD_0 { get; set;}
        public string BPDSAT_0 { get; set;}
        public string BPIADDLIG_0 { get; set;}
        public string BPIADDLIG_1 { get; set;}
        public string BPIADDLIG_2 { get; set;}
        public string BPICRY_0 { get; set;}
        public string BPICRYNAM_0 { get; set;}
        public string BPICTY_0 { get; set;}
        public string BPIEECNUM_0 { get; set;}
        public string BPINAM_0 { get; set;}
        public string BPINAM_1 { get; set;}
        public string BPIPOSCOD_0 { get; set;}
        public string BPISAT_0 { get; set;}
        public string BPTNUM_0 { get; set;}
        public string CCE_0 { get; set;}
        public string CCE_1 { get; set;}
        public string CCE_10 { get; set;}
        public string CCE_11 { get; set;}
        public string CCE_12 { get; set;}
        public string CCE_13 { get; set;}
        public string CCE_14 { get; set;}
        public string CCE_15 { get; set;}
        public string CCE_16 { get; set;}
        public string CCE_17 { get; set;}
        public string CCE_18 { get; set;}
        public string CCE_19 { get; set;}
        public string CCE_2 { get; set;}
        public string CCE_3 { get; set;}
        public string CCE_4 { get; set;}
        public string CCE_5 { get; set;}
        public string CCE_6 { get; set;}
        public string CCE_7 { get; set;}
        public string CCE_8 { get; set;}
        public string CCE_9 { get; set;}
        public DateTime CCLDAT_0 { get; set;}
        public string CCLREN_0 { get; set;}
        public byte CDTSTA_0 { get; set;}
        public decimal CHGRAT_0 { get; set;}
        public byte CHGTYP_0 { get; set;}
        public short CLELINNBR_0 { get; set;}
        public string CMGNUM_0 { get; set;}
        public string CNDNAM_0 { get; set;}
        public string CNINAM_0 { get; set;}
        public string CNTNAM_0 { get; set;}
        public short COPNBR_0 { get; set;}
        public string CPY_0 { get; set;}
        public DateTime CREDAT_0 { get; set;}
        public string CREUSR_0 { get; set;}
        public string CUR_0 { get; set;}
        public string CUSORDREF_0 { get; set;}
        public short DAYLTI_0 { get; set;}
        public DateTime DEMDLVDAT_0 { get; set;}
        public string DEP_0 { get; set;}
        public string DIE_0 { get; set;}
        public string DIE_1 { get; set;}
        public string DIE_10 { get; set;}
        public string DIE_11 { get; set;}
        public string DIE_12 { get; set;}
        public string DIE_13 { get; set;}
        public string DIE_14 { get; set;}
        public string DIE_15 { get; set;}
        public string DIE_16 { get; set;}
        public string DIE_17 { get; set;}
        public string DIE_18 { get; set;}
        public string DIE_19 { get; set;}
        public string DIE_2 { get; set;}
        public string DIE_3 { get; set;}
        public string DIE_4 { get; set;}
        public string DIE_5 { get; set;}
        public string DIE_6 { get; set;}
        public string DIE_7 { get; set;}
        public string DIE_8 { get; set;}
        public string DIE_9 { get; set;}
        public byte DISCRGTYP_0 { get; set;}
        public byte DISCRGTYP_1 { get; set;}
        public byte DISCRGTYP_2 { get; set;}
        public byte DISCRGTYP_3 { get; set;}
        public byte DISCRGTYP_4 { get; set;}
        public byte DISCRGTYP_5 { get; set;}
        public byte DISCRGTYP_6 { get; set;}
        public byte DISCRGTYP_7 { get; set;}
        public byte DISCRGTYP_8 { get; set;}
        public decimal DLRATI_0 { get; set;}
        public decimal DLRNOT_0 { get; set;}
        public short DLVLINNBR_0 { get; set;}
        public byte DLVPIO_0 { get; set;}
        public byte DLVSTA_0 { get; set;}
        public byte DME_0 { get; set;}
        public byte DRN_0 { get; set;}
        public decimal DSPTOTQTY_0 { get; set;}
        public decimal DSPTOTVOL_0 { get; set;}
        public decimal DSPTOTWEI_0 { get; set;}
        public string DSPVOU_0 { get; set;}
        public string DSPWEU_0 { get; set;}
        public string EECICT_0 { get; set;}
        public byte EECLOC_0 { get; set;}
        public int EXPNUM_0 { get; set;}
        public string FFWADD_0 { get; set;}
        public string FFWNUM_0 { get; set;}
        public string GEOCOD_0 { get; set;}
        public string ICTCTY_0 { get; set;}
        public byte IME_0 { get; set;}
        public string INSCTYFLG_0 { get; set;}
        public short INVDTA_0 { get; set;}
        public short INVDTA_1 { get; set;}
        public short INVDTA_10 { get; set;}
        public short INVDTA_11 { get; set;}
        public short INVDTA_12 { get; set;}
        public short INVDTA_13 { get; set;}
        public short INVDTA_14 { get; set;}
        public short INVDTA_15 { get; set;}
        public short INVDTA_16 { get; set;}
        public short INVDTA_17 { get; set;}
        public short INVDTA_18 { get; set;}
        public short INVDTA_19 { get; set;}
        public short INVDTA_2 { get; set;}
        public short INVDTA_20 { get; set;}
        public short INVDTA_21 { get; set;}
        public short INVDTA_22 { get; set;}
        public short INVDTA_23 { get; set;}
        public short INVDTA_24 { get; set;}
        public short INVDTA_25 { get; set;}
        public short INVDTA_26 { get; set;}
        public short INVDTA_27 { get; set;}
        public short INVDTA_28 { get; set;}
        public short INVDTA_29 { get; set;}
        public short INVDTA_3 { get; set;}
        public short INVDTA_4 { get; set;}
        public short INVDTA_5 { get; set;}
        public short INVDTA_6 { get; set;}
        public short INVDTA_7 { get; set;}
        public short INVDTA_8 { get; set;}
        public short INVDTA_9 { get; set;}
        public decimal INVDTAAMT_0 { get; set;}
        public decimal INVDTAAMT_1 { get; set;}
        public decimal INVDTAAMT_10 { get; set;}
        public decimal INVDTAAMT_11 { get; set;}
        public decimal INVDTAAMT_12 { get; set;}
        public decimal INVDTAAMT_13 { get; set;}
        public decimal INVDTAAMT_14 { get; set;}
        public decimal INVDTAAMT_15 { get; set;}
        public decimal INVDTAAMT_16 { get; set;}
        public decimal INVDTAAMT_17 { get; set;}
        public decimal INVDTAAMT_18 { get; set;}
        public decimal INVDTAAMT_19 { get; set;}
        public decimal INVDTAAMT_2 { get; set;}
        public decimal INVDTAAMT_20 { get; set;}
        public decimal INVDTAAMT_21 { get; set;}
        public decimal INVDTAAMT_22 { get; set;}
        public decimal INVDTAAMT_23 { get; set;}
        public decimal INVDTAAMT_24 { get; set;}
        public decimal INVDTAAMT_25 { get; set;}
        public decimal INVDTAAMT_26 { get; set;}
        public decimal INVDTAAMT_27 { get; set;}
        public decimal INVDTAAMT_28 { get; set;}
        public decimal INVDTAAMT_29 { get; set;}
        public decimal INVDTAAMT_3 { get; set;}
        public decimal INVDTAAMT_4 { get; set;}
        public decimal INVDTAAMT_5 { get; set;}
        public decimal INVDTAAMT_6 { get; set;}
        public decimal INVDTAAMT_7 { get; set;}
        public decimal INVDTAAMT_8 { get; set;}
        public decimal INVDTAAMT_9 { get; set;}
        public string INVDTADSP_0 { get; set;}
        public string INVDTADSP_1 { get; set;}
        public string INVDTADSP_10 { get; set;}
        public string INVDTADSP_11 { get; set;}
        public string INVDTADSP_12 { get; set;}
        public string INVDTADSP_13 { get; set;}
        public string INVDTADSP_14 { get; set;}
        public string INVDTADSP_15 { get; set;}
        public string INVDTADSP_16 { get; set;}
        public string INVDTADSP_17 { get; set;}
        public string INVDTADSP_18 { get; set;}
        public string INVDTADSP_19 { get; set;}
        public string INVDTADSP_2 { get; set;}
        public string INVDTADSP_20 { get; set;}
        public string INVDTADSP_21 { get; set;}
        public string INVDTADSP_22 { get; set;}
        public string INVDTADSP_23 { get; set;}
        public string INVDTADSP_24 { get; set;}
        public string INVDTADSP_25 { get; set;}
        public string INVDTADSP_26 { get; set;}
        public string INVDTADSP_27 { get; set;}
        public string INVDTADSP_28 { get; set;}
        public string INVDTADSP_29 { get; set;}
        public string INVDTADSP_3 { get; set;}
        public string INVDTADSP_4 { get; set;}
        public string INVDTADSP_5 { get; set;}
        public string INVDTADSP_6 { get; set;}
        public string INVDTADSP_7 { get; set;}
        public string INVDTADSP_8 { get; set;}
        public string INVDTADSP_9 { get; set;}
        public short INVDTALIN_0 { get; set;}
        public short INVDTALIN_1 { get; set;}
        public short INVDTALIN_2 { get; set;}
        public short INVDTALIN_3 { get; set;}
        public short INVDTALIN_4 { get; set;}
        public short INVDTALIN_5 { get; set;}
        public short INVDTALIN_6 { get; set;}
        public short INVDTALIN_7 { get; set;}
        public short INVDTALIN_8 { get; set;}
        public byte INVDTATYP_0 { get; set;}
        public byte INVDTATYP_1 { get; set;}
        public byte INVDTATYP_10 { get; set;}
        public byte INVDTATYP_11 { get; set;}
        public byte INVDTATYP_12 { get; set;}
        public byte INVDTATYP_13 { get; set;}
        public byte INVDTATYP_14 { get; set;}
        public byte INVDTATYP_15 { get; set;}
        public byte INVDTATYP_16 { get; set;}
        public byte INVDTATYP_17 { get; set;}
        public byte INVDTATYP_18 { get; set;}
        public byte INVDTATYP_19 { get; set;}
        public byte INVDTATYP_2 { get; set;}
        public byte INVDTATYP_20 { get; set;}
        public byte INVDTATYP_21 { get; set;}
        public byte INVDTATYP_22 { get; set;}
        public byte INVDTATYP_23 { get; set;}
        public byte INVDTATYP_24 { get; set;}
        public byte INVDTATYP_25 { get; set;}
        public byte INVDTATYP_26 { get; set;}
        public byte INVDTATYP_27 { get; set;}
        public byte INVDTATYP_28 { get; set;}
        public byte INVDTATYP_29 { get; set;}
        public byte INVDTATYP_3 { get; set;}
        public byte INVDTATYP_4 { get; set;}
        public byte INVDTATYP_5 { get; set;}
        public byte INVDTATYP_6 { get; set;}
        public byte INVDTATYP_7 { get; set;}
        public byte INVDTATYP_8 { get; set;}
        public byte INVDTATYP_9 { get; set;}
        public short INVLINNBR_0 { get; set;}
        public byte INVSTA_0 { get; set;}
        public string LAN_0 { get; set;}
        public DateTime LASDLVDAT_0 { get; set;}
        public string LASDLVNUM_0 { get; set;}
        public DateTime LASINVDAT_0 { get; set;}
        public string LASINVNUM_0 { get; set;}
        public short LINNBR_0 { get; set;}
        public DateTime LNDRTNDAT_0 { get; set;}
        public string MDL_0 { get; set;}
        public byte OCNFLG_0 { get; set;}
        public byte OCNPRN_0 { get; set;}
        public byte ODL_0 { get; set;}
        public string OPGNUM_0 { get; set;}
        public string OPGTYP_0 { get; set;}
        public decimal ORDATI_0 { get; set;}
        public decimal ORDATIL_0 { get; set;}
        public byte ORDCLE_0 { get; set;}
        public DateTime ORDDAT_0 { get; set;}
        public decimal ORDINVATI_0 { get; set;}
        public decimal ORDINVATIL_0 { get; set;}
        public decimal ORDINVNOT_0 { get; set;}
        public decimal ORDINVNOTL_0 { get; set;}
        public decimal ORDNOT_0 { get; set;}
        public decimal ORDNOTL_0 { get; set;}
        public byte ORDSTA_0 { get; set;}
        public string ORIFCY_0 { get; set;}
        public decimal PFMTOT_0 { get; set;}
        public string PJT_0 { get; set;}
        public string PLISTC_0 { get; set;}
        public string PRFNUM_0 { get; set;}
        public byte PRITYP_0 { get; set;}
        public string PTE_0 { get; set;}
        public string REP_0 { get; set;}
        public string REP_1 { get; set;}
        public short REVNUM_0 { get; set;}
        public string SALFCY_0 { get; set;}
        public string SHIADECOD_0 { get; set;}
        public DateTime SHIDAT_0 { get; set;}
        public string SINUM_0 { get; set;}
        public byte SOHCAT_0 { get; set;}
        public string SOHNUM_0 { get; set;}
        public string SOHTEX1_0 { get; set;}
        public string SOHTEX2_0 { get; set;}
        public string SOHTYP_0 { get; set;}
        public string SQHNUM_0 { get; set;}
        public string SRENUM_0 { get; set;}
        public string STOFCY_0 { get; set;}
        public string TSCCOD_0 { get; set;}
        public string TSCCOD_1 { get; set;}
        public string TSCCOD_2 { get; set;}
        public string TSCCOD_3 { get; set;}
        public string TSCCOD_4 { get; set;}
        public byte UNL_0 { get; set;}
        public DateTime UPDDAT_0 { get; set;}
        public string UPDUSR_0 { get; set;}
        public string VACBPR_0 { get; set;}
        public DateTime VLYDATCON_0 { get; set;}
        public string VTT_0 { get; set;}
        public string XA_CONTACT2_0 { get; set;}
        public string XA_FAX_0 { get; set;}
        public short XA_NORM_0 { get; set;}
        public short XA_OUTTYP2_0 { get; set;}
        public short XA_RPTTYP2_0 { get; set;}
        public byte XA_TENDTYP_0 { get; set;}
        public string XA_WEB_0 { get; set;}
        public byte XB_855STA_0 { get; set;}
        public string XB_BACCT_0 { get; set;}
        public decimal XB_GMRELPCT_0 { get; set;}
        public string XB_HLDCOD_0 { get; set;}
        public DateTime XB_HLDDAT_0 { get; set;}
        public string XB_HLDLGN_0 { get; set;}
        public byte XB_HLDSTA_0 { get; set;}
        public string XB_HLDTIM_0 { get; set;}
        public byte XB_HLDTYP_0 { get; set;}
        public string XB_HLDUSR_0 { get; set;}
        public short XB_RESFLG_0 { get; set;}
        public string XB_TPBADD_0 { get; set;}
        public string XB_TPBCRY_0 { get; set;}
        public string XB_TPBCTY_0 { get; set;}
        public string XB_TPBNAM_0 { get; set;}
        public string XB_TPBSAT_0 { get; set;}
        public string XB_TPBZIP_0 { get; set;}
        public decimal XC_FCLCKWGT_0 { get; set;}
        public short XC_FREEFRT_0 { get; set;}
        public decimal XC_FRTEST_0 { get; set;}
        public string XC_LCCAR_0 { get; set;}
        public decimal XC_LCFRAT_0 { get; set;}
        public short XC_MANBPTNUM_0 { get; set;}
        public short XC_OVRFR_0 { get; set;}
        public short XC_POBOX_0 { get; set;}
        public string XT_ID_0 { get; set;}
        public string XT_WEBID_0 { get; set;}
        public string XT_WEBSITEID_0 { get; set;}
        public string YBPCTEL_0 { get; set;}
        public string YBPCWEB_0 { get; set;}
        public string YBPDTEL_0 { get; set;}
        public string YBPDWEB_0 { get; set;}
        public string YEDI_NOTES_0 { get; set;}
        public byte YORDER_RECVD_0 { get; set;}
        public string YORDERED_BY_0 { get; set;}
        public string YORDERED_EML_0 { get; set;}
        public string YORDERED_FAX_0 { get; set;}
        public virtual ICollection<OrderLine> Lines { get; set;}
    }
}