// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PAYACCNUMD", Schema = "TESTPROD")]
    [Index(nameof(Num0), nameof(Accsta0), nameof(Accnum0), Name = "PAYACCNUMD_PMD0", IsUnique = true)]
    public partial class Payaccnumd
    {
        [Required]
        [Column("NUM_0")]
        [StringLength(20)]
        public string Num0 { get; set; }
        [Column("ACCSTA_0")]
        public short Accsta0 { get; set; }
        [Column("ACCNUM_0")]
        public int Accnum0 { get; set; }
        [Required]
        [Column("TYP_0")]
        [StringLength(5)]
        public string Typ0 { get; set; }
        [Required]
        [Column("VCRNUM_0")]
        [StringLength(20)]
        public string Vcrnum0 { get; set; }
        [Column("SNS_0")]
        public short Sns0 { get; set; }
        [Column("AMTCUR_0", TypeName = "numeric(27, 13)")]
        public decimal Amtcur0 { get; set; }
        [Column("RVSACCNUM_0")]
        public int Rvsaccnum0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}