// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PAYFRM", Schema = "TESTPROD")]
    [Index(nameof(Frmflg0), nameof(Frmnum0), Name = "PAYFRM_FRM0", IsUnique = true)]
    public partial class Payfrm
    {
        [Required]
        [Column("FRMNUM_0")]
        [StringLength(20)]
        public string Frmnum0 { get; set; }
        [Column("FRMFLG_0")]
        public byte Frmflg0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Required]
        [Column("FRMFCY_0")]
        [StringLength(5)]
        public string Frmfcy0 { get; set; }
        [Required]
        [Column("PAYTYP_0")]
        [StringLength(5)]
        public string Paytyp0 { get; set; }
        [Required]
        [Column("BAN_0")]
        [StringLength(5)]
        public string Ban0 { get; set; }
        [Column("FRMTYP_0")]
        public byte Frmtyp0 { get; set; }
        [Column("CHQTYP_0")]
        public byte Chqtyp0 { get; set; }
        [Column("STA_0")]
        public byte Sta0 { get; set; }
        [Required]
        [Column("TFBFIL_0")]
        [StringLength(15)]
        public string Tfbfil0 { get; set; }
        [Column("TFBDAT_0", TypeName = "datetime")]
        public DateTime Tfbdat0 { get; set; }
        [Column("EXEDAT_0", TypeName = "datetime")]
        public DateTime Exedat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}