// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PAYORDER", Schema = "TESTPROD")]
    [Index(nameof(Dudnum0), nameof(Dudlig0), nameof(Paynum0), Name = "PAYORDER_PYO0", IsUnique = true)]
    public partial class Payorder
    {
        [Column("DUDNUM_0")]
        public int Dudnum0 { get; set; }
        [Column("DUDLIG_0")]
        public short Dudlig0 { get; set; }
        [Column("DUDPAYAMT_0", TypeName = "numeric(27, 13)")]
        public decimal Dudpayamt0 { get; set; }
        [Required]
        [Column("PAYVCR_0")]
        [StringLength(20)]
        public string Payvcr0 { get; set; }
        [Column("PAYNUM_0")]
        public int Paynum0 { get; set; }
        [Column("INVNUM_0")]
        public int Invnum0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}