// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PDPHEA", Schema = "TESTPROD")]
    [Index(nameof(Stofcy0), nameof(Itmref0), Name = "PDPHEA_CBH0", IsUnique = true)]
    [Index(nameof(Stofcy0), nameof(Llc0), nameof(Itmref0), Name = "PDPHEA_CBH1", IsUnique = true)]
    public partial class Pdphea
    {
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Column("LLC_0")]
        public short Llc0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Required]
        [Column("ITMDES1_0")]
        [StringLength(30)]
        public string Itmdes10 { get; set; }
        [Column("STDFLG_0")]
        public byte Stdflg0 { get; set; }
        [Column("EXYSTOFLG_0")]
        public byte Exystoflg0 { get; set; }
        [Column("LIFSTRDAT_0", TypeName = "datetime")]
        public DateTime Lifstrdat0 { get; set; }
        [Column("LIFENDDAT_0", TypeName = "datetime")]
        public DateTime Lifenddat0 { get; set; }
        [Column("PLHENDDAT_0", TypeName = "datetime")]
        public DateTime Plhenddat0 { get; set; }
        [Column("FOHENDDAT_0", TypeName = "datetime")]
        public DateTime Fohenddat0 { get; set; }
        [Column("FOHUOT_0")]
        public byte Fohuot0 { get; set; }
        [Column("BPRSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Bprsto0 { get; set; }
        [Column("PHYSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Physto0 { get; set; }
        [Column("CTLSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Ctlsto0 { get; set; }
        [Column("REJSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Rejsto0 { get; set; }
        [Column("INTSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Intsto0 { get; set; }
        [Column("PLFSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Plfsto0 { get; set; }
        [Column("SCOSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Scosto0 { get; set; }
        [Column("ALLSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Allsto0 { get; set; }
        [Column("DETSHT_0", TypeName = "numeric(28, 13)")]
        public decimal Detsht0 { get; set; }
        [Column("GLOALL_0", TypeName = "numeric(28, 13)")]
        public decimal Gloall0 { get; set; }
        [Column("GLOSHT_0", TypeName = "numeric(28, 13)")]
        public decimal Glosht0 { get; set; }
        [Column("TRFSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Trfsto0 { get; set; }
        [Column("TRASTO_0", TypeName = "numeric(28, 13)")]
        public decimal Trasto0 { get; set; }
        [Column("ORDSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Ordsto0 { get; set; }
        [Column("SALSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Salsto0 { get; set; }
        [Column("WAISTO_0", TypeName = "numeric(28, 13)")]
        public decimal Waisto0 { get; set; }
        [Column("STRSTO_0", TypeName = "numeric(28, 13)")]
        public decimal Strsto0 { get; set; }
        [Required]
        [Column("STU_0")]
        [StringLength(3)]
        public string Stu0 { get; set; }
        [Column("STUDEC_0")]
        public short Studec0 { get; set; }
        [Column("PROFLG_0")]
        public short Proflg0 { get; set; }
        [Column("REOMGTCOD_0")]
        public byte Reomgtcod0 { get; set; }
        [Column("REOCOD_0")]
        public byte Reocod0 { get; set; }
        [Required]
        [Column("REOFCY_0")]
        [StringLength(5)]
        public string Reofcy0 { get; set; }
        [Required]
        [Column("REOPOL_0")]
        [StringLength(3)]
        public string Reopol0 { get; set; }
        [Column("SUGTYP_0")]
        public byte Sugtyp0 { get; set; }
        [Column("STOTIAFLG_0")]
        public byte Stotiaflg0 { get; set; }
        [Column("REOQTYCOD_0")]
        public byte Reoqtycod0 { get; set; }
        [Column("SPLCOD_0")]
        public byte Splcod0 { get; set; }
        [Column("SAFSTOCOD_0")]
        public byte Safstocod0 { get; set; }
        [Column("PLNANYCOD_0")]
        public byte Plnanycod0 { get; set; }
        [Column("DAYCOV_0")]
        public short Daycov0 { get; set; }
        [Column("SHR_0", TypeName = "numeric(10, 4)")]
        public decimal Shr0 { get; set; }
        [Column("BOMALTTYP_0")]
        public byte Bomalttyp0 { get; set; }
        [Column("BOMALT_0")]
        public short Bomalt0 { get; set; }
        [Column("ORDFLG_0")]
        public byte Ordflg0 { get; set; }
        [Column("QUAFLG_0")]
        public byte Quaflg0 { get; set; }
        [Column("QUALTI_0", TypeName = "numeric(9, 4)")]
        public decimal Qualti0 { get; set; }
        [Column("WIPPRO_0")]
        public byte Wippro0 { get; set; }
        [Column("PURFLG_0")]
        public byte Purflg0 { get; set; }
        [Column("MFGFLG_0")]
        public byte Mfgflg0 { get; set; }
        [Column("SCPFLG_0")]
        public byte Scpflg0 { get; set; }
        [Column("SCSFLG_0")]
        public byte Scsflg0 { get; set; }
        [Column("PHAFLG_0")]
        public byte Phaflg0 { get; set; }
        [Column("GENFLG_0")]
        public byte Genflg0 { get; set; }
        [Column("TOOFLG_0")]
        public byte Tooflg0 { get; set; }
        [Column("DLVFLG_0")]
        public byte Dlvflg0 { get; set; }
        [Column("SALFLG_0")]
        public byte Salflg0 { get; set; }
        [Column("INTFLG_0")]
        public byte Intflg0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}