// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PITDEBD", Schema = "TESTPROD")]
    [Index(nameof(Bpr0), nameof(Itmref0), nameof(Pbl0), nameof(Pbdlin0), Name = "PITDEBD_PBD0", IsUnique = true)]
    public partial class Pitdebd
    {
        [Required]
        [Column("BPR_0")]
        [StringLength(15)]
        public string Bpr0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Required]
        [Column("PBL_0")]
        [StringLength(20)]
        public string Pbl0 { get; set; }
        [Column("PBDLIN_0")]
        public int Pbdlin0 { get; set; }
        [Required]
        [Column("ITM_0")]
        [StringLength(20)]
        public string Itm0 { get; set; }
        [Column("NBRPIT_0")]
        public int Nbrpit0 { get; set; }
        [Column("NULPIOVAL_0")]
        public byte Nulpioval0 { get; set; }
        [Column("DEBFRY_0", TypeName = "numeric(28, 13)")]
        public decimal Debfry0 { get; set; }
        [Required]
        [Column("DEBFRYBAS_0")]
        [StringLength(3)]
        public string Debfrybas0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}