// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PIVZON", Schema = "TESTPROD")]
    [Index(nameof(Id0), nameof(Lin0), Name = "PIVZON_PIZ0", IsUnique = true)]
    [Index(nameof(Id0), nameof(Codfic0), nameof(Codzone0), Name = "PIVZON_PIZ1", IsUnique = true)]
    public partial class Pivzon
    {
        [Required]
        [Column("ID_0")]
        [StringLength(10)]
        public string Id0 { get; set; }
        [Column("LIN_0")]
        public short Lin0 { get; set; }
        [Required]
        [Column("CODFIC_0")]
        [StringLength(12)]
        public string Codfic0 { get; set; }
        [Required]
        [Column("CODZONE_0")]
        [StringLength(12)]
        public string Codzone0 { get; set; }
        [Required]
        [Column("DES_0")]
        [StringLength(30)]
        public string Des0 { get; set; }
        [Required]
        [Column("FRM_0")]
        [StringLength(150)]
        public string Frm0 { get; set; }
        [Column("WRKZON_0")]
        public byte Wrkzon0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}