// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PLMPAR", Schema = "TESTPROD")]
    [Index(nameof(Id0), Name = "PLMPAR_PPA0", IsUnique = true)]
    public partial class Plmpar
    {
        [Required]
        [Column("ID_0")]
        [StringLength(10)]
        public string Id0 { get; set; }
        [Required]
        [Column("INTIT_0")]
        [StringLength(30)]
        public string Intit0 { get; set; }
        [Required]
        [Column("ITMPIT_0")]
        [StringLength(10)]
        public string Itmpit0 { get; set; }
        [Required]
        [Column("BOMPIT_0")]
        [StringLength(10)]
        public string Bompit0 { get; set; }
        [Column("BOMALT_0")]
        public short Bomalt0 { get; set; }
        [Required]
        [Column("ADDEML1_0")]
        [StringLength(80)]
        public string Addeml10 { get; set; }
        [Required]
        [Column("ADDEML2_0")]
        [StringLength(80)]
        public string Addeml20 { get; set; }
        [Required]
        [Column("DRTRCP_0")]
        [StringLength(250)]
        public string Drtrcp0 { get; set; }
        [Required]
        [Column("DRTISS_0")]
        [StringLength(250)]
        public string Drtiss0 { get; set; }
        [Required]
        [Column("DRTSTO_0")]
        [StringLength(250)]
        public string Drtsto0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}