// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("POSCOD", Schema = "TESTPROD")]
    [Index(nameof(Cry0), nameof(Poscod0), nameof(Poscty0), nameof(Posctycod0), Name = "POSCOD_POS0", IsUnique = true)]
    [Index(nameof(Cry0), nameof(Poscty0), nameof(Poscod0), Name = "POSCOD_POS1")]
    [Index(nameof(Poscod0), Name = "POSCOD_POS2")]
    public partial class Poscod
    {
        [Required]
        [Column("CRY_0")]
        [StringLength(3)]
        public string Cry0 { get; set; }
        [Required]
        [Column("POSCOD_0")]
        [StringLength(10)]
        public string Poscod0 { get; set; }
        [Required]
        [Column("POSCTYCOD_0")]
        [StringLength(10)]
        public string Posctycod0 { get; set; }
        [Required]
        [Column("POSUPDFLG_0")]
        [StringLength(1)]
        public string Posupdflg0 { get; set; }
        [Required]
        [Column("POSCTY_0")]
        [StringLength(40)]
        public string Poscty0 { get; set; }
        [Required]
        [Column("SATCOD_0")]
        [StringLength(35)]
        public string Satcod0 { get; set; }
        [Required]
        [Column("GEOCOD_0")]
        [StringLength(9)]
        public string Geocod0 { get; set; }
        [Required]
        [Column("BURDIS_0")]
        [StringLength(1)]
        public string Burdis0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}