// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("PWRKPNH", Schema = "TESTPROD")]
    [Index(nameof(Pronum0), nameof(Pnhnum0), Name = "PWRKPNH_PWE0", IsUnique = true)]
    [Index(nameof(Pronum0), nameof(Cpy0), nameof(Pnhfcy0), nameof(Bpsinv0), nameof(Cur0), nameof(Pnhnum0), Name = "PWRKPNH_PWE1", IsUnique = true)]
    public partial class Pwrkpnh
    {
        [Column("PRONUM_0")]
        public int Pronum0 { get; set; }
        [Required]
        [Column("PNHNUM_0")]
        [StringLength(20)]
        public string Pnhnum0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Required]
        [Column("PNHFCY_0")]
        [StringLength(5)]
        public string Pnhfcy0 { get; set; }
        [Column("PURTYP_0")]
        public byte Purtyp0 { get; set; }
        [Column("RTNDAT_0", TypeName = "datetime")]
        public DateTime Rtndat0 { get; set; }
        [Required]
        [Column("BUY_0")]
        [StringLength(5)]
        public string Buy0 { get; set; }
        [Required]
        [Column("BPSNUM_0")]
        [StringLength(15)]
        public string Bpsnum0 { get; set; }
        [Required]
        [Column("BPAADD_0")]
        [StringLength(7)]
        public string Bpaadd0 { get; set; }
        [Required]
        [Column("BPAADDLIG_0")]
        [StringLength(40)]
        public string Bpaaddlig0 { get; set; }
        [Required]
        [Column("BPAADDLIG_1")]
        [StringLength(40)]
        public string Bpaaddlig1 { get; set; }
        [Required]
        [Column("BPAADDLIG_2")]
        [StringLength(40)]
        public string Bpaaddlig2 { get; set; }
        [Required]
        [Column("BPRNAM_0")]
        [StringLength(35)]
        public string Bprnam0 { get; set; }
        [Required]
        [Column("BPRNAM_1")]
        [StringLength(35)]
        public string Bprnam1 { get; set; }
        [Required]
        [Column("SAT_0")]
        [StringLength(35)]
        public string Sat0 { get; set; }
        [Required]
        [Column("CRY_0")]
        [StringLength(3)]
        public string Cry0 { get; set; }
        [Required]
        [Column("CRYNAM_0")]
        [StringLength(40)]
        public string Crynam0 { get; set; }
        [Required]
        [Column("CTY_0")]
        [StringLength(40)]
        public string Cty0 { get; set; }
        [Required]
        [Column("POSCOD_0")]
        [StringLength(10)]
        public string Poscod0 { get; set; }
        [Required]
        [Column("BPSINV_0")]
        [StringLength(15)]
        public string Bpsinv0 { get; set; }
        [Required]
        [Column("BPAINV_0")]
        [StringLength(7)]
        public string Bpainv0 { get; set; }
        [Required]
        [Column("BPRPAY_0")]
        [StringLength(15)]
        public string Bprpay0 { get; set; }
        [Required]
        [Column("BPAPAY_0")]
        [StringLength(7)]
        public string Bpapay0 { get; set; }
        [Required]
        [Column("AUZNUM_0")]
        [StringLength(15)]
        public string Auznum0 { get; set; }
        [Required]
        [Column("TSSCOD_0")]
        [StringLength(20)]
        public string Tsscod0 { get; set; }
        [Required]
        [Column("TSSCOD_1")]
        [StringLength(20)]
        public string Tsscod1 { get; set; }
        [Required]
        [Column("TSSCOD_2")]
        [StringLength(20)]
        public string Tsscod2 { get; set; }
        [Required]
        [Column("TSSCOD_3")]
        [StringLength(20)]
        public string Tsscod3 { get; set; }
        [Required]
        [Column("TSSCOD_4")]
        [StringLength(20)]
        public string Tsscod4 { get; set; }
        [Required]
        [Column("VACBPR_0")]
        [StringLength(20)]
        public string Vacbpr0 { get; set; }
        [Column("VACTYP_0")]
        public short Vactyp0 { get; set; }
        [Required]
        [Column("REM_0")]
        [StringLength(250)]
        public string Rem0 { get; set; }
        [Required]
        [Column("BPTNUM_0")]
        [StringLength(15)]
        public string Bptnum0 { get; set; }
        [Required]
        [Column("FFWNUM_0")]
        [StringLength(15)]
        public string Ffwnum0 { get; set; }
        [Required]
        [Column("FFWADD_0")]
        [StringLength(7)]
        public string Ffwadd0 { get; set; }
        [Required]
        [Column("MDL_0")]
        [StringLength(5)]
        public string Mdl0 { get; set; }
        [Required]
        [Column("EECNAT_0")]
        [StringLength(1)]
        public string Eecnat0 { get; set; }
        [Required]
        [Column("EECSCH_0")]
        [StringLength(1)]
        public string Eecsch0 { get; set; }
        [Column("EECTRN_0")]
        public short Eectrn0 { get; set; }
        [Required]
        [Column("EECICT_0")]
        [StringLength(20)]
        public string Eecict0 { get; set; }
        [Required]
        [Column("ICTCTY_0")]
        [StringLength(40)]
        public string Ictcty0 { get; set; }
        [Column("EECLOC_0")]
        public short Eecloc0 { get; set; }
        [Required]
        [Column("EECNUM_0")]
        [StringLength(1)]
        public string Eecnum0 { get; set; }
        [Column("EECNUMDEB_0")]
        public short Eecnumdeb0 { get; set; }
        [Required]
        [Column("WEU_0")]
        [StringLength(3)]
        public string Weu0 { get; set; }
        [Required]
        [Column("VOU_0")]
        [StringLength(3)]
        public string Vou0 { get; set; }
        [Column("TOTGROWEI_0", TypeName = "numeric(20, 5)")]
        public decimal Totgrowei0 { get; set; }
        [Column("TOTNETWEI_0", TypeName = "numeric(20, 5)")]
        public decimal Totnetwei0 { get; set; }
        [Column("TOTVOL_0", TypeName = "numeric(20, 5)")]
        public decimal Totvol0 { get; set; }
        [Column("LINNBR_0")]
        public short Linnbr0 { get; set; }
        [Column("PRNFLG_0")]
        public byte Prnflg0 { get; set; }
        [Column("CFMFLG_0")]
        public byte Cfmflg0 { get; set; }
        [Column("PSTFLG_0")]
        public byte Pstflg0 { get; set; }
        [Column("PSTDAT_0", TypeName = "datetime")]
        public DateTime Pstdat0 { get; set; }
        [Column("PSTLINNBR_0")]
        public short Pstlinnbr0 { get; set; }
        [Column("INVFLG_0")]
        public byte Invflg0 { get; set; }
        [Column("INVLINNBR_0")]
        public short Invlinnbr0 { get; set; }
        [Required]
        [Column("TEX1_0")]
        [StringLength(12)]
        public string Tex10 { get; set; }
        [Required]
        [Column("TEX2_0")]
        [StringLength(12)]
        public string Tex20 { get; set; }
        [Required]
        [Column("TRSCOD_0")]
        [StringLength(20)]
        public string Trscod0 { get; set; }
        [Required]
        [Column("ENTCOD_0")]
        [StringLength(5)]
        public string Entcod0 { get; set; }
        [Column("BETFCY_0")]
        public byte Betfcy0 { get; set; }
        [Column("BETCPY_0")]
        public byte Betcpy0 { get; set; }
        [Required]
        [Column("DIE_0")]
        [StringLength(3)]
        public string Die0 { get; set; }
        [Required]
        [Column("DIE_1")]
        [StringLength(3)]
        public string Die1 { get; set; }
        [Required]
        [Column("DIE_2")]
        [StringLength(3)]
        public string Die2 { get; set; }
        [Required]
        [Column("DIE_3")]
        [StringLength(3)]
        public string Die3 { get; set; }
        [Required]
        [Column("DIE_4")]
        [StringLength(3)]
        public string Die4 { get; set; }
        [Required]
        [Column("DIE_5")]
        [StringLength(3)]
        public string Die5 { get; set; }
        [Required]
        [Column("DIE_6")]
        [StringLength(3)]
        public string Die6 { get; set; }
        [Required]
        [Column("DIE_7")]
        [StringLength(3)]
        public string Die7 { get; set; }
        [Required]
        [Column("DIE_8")]
        [StringLength(3)]
        public string Die8 { get; set; }
        [Required]
        [Column("DIE_9")]
        [StringLength(3)]
        public string Die9 { get; set; }
        [Required]
        [Column("DIE_10")]
        [StringLength(3)]
        public string Die10 { get; set; }
        [Required]
        [Column("DIE_11")]
        [StringLength(3)]
        public string Die11 { get; set; }
        [Required]
        [Column("DIE_12")]
        [StringLength(3)]
        public string Die12 { get; set; }
        [Required]
        [Column("DIE_13")]
        [StringLength(3)]
        public string Die13 { get; set; }
        [Required]
        [Column("DIE_14")]
        [StringLength(3)]
        public string Die14 { get; set; }
        [Required]
        [Column("DIE_15")]
        [StringLength(3)]
        public string Die15 { get; set; }
        [Required]
        [Column("DIE_16")]
        [StringLength(3)]
        public string Die16 { get; set; }
        [Required]
        [Column("DIE_17")]
        [StringLength(3)]
        public string Die17 { get; set; }
        [Required]
        [Column("DIE_18")]
        [StringLength(3)]
        public string Die18 { get; set; }
        [Required]
        [Column("DIE_19")]
        [StringLength(3)]
        public string Die19 { get; set; }
        [Required]
        [Column("CCE_0")]
        [StringLength(15)]
        public string Cce0 { get; set; }
        [Required]
        [Column("CCE_1")]
        [StringLength(15)]
        public string Cce1 { get; set; }
        [Required]
        [Column("CCE_2")]
        [StringLength(15)]
        public string Cce2 { get; set; }
        [Required]
        [Column("CCE_3")]
        [StringLength(15)]
        public string Cce3 { get; set; }
        [Required]
        [Column("CCE_4")]
        [StringLength(15)]
        public string Cce4 { get; set; }
        [Required]
        [Column("CCE_5")]
        [StringLength(15)]
        public string Cce5 { get; set; }
        [Required]
        [Column("CCE_6")]
        [StringLength(15)]
        public string Cce6 { get; set; }
        [Required]
        [Column("CCE_7")]
        [StringLength(15)]
        public string Cce7 { get; set; }
        [Required]
        [Column("CCE_8")]
        [StringLength(15)]
        public string Cce8 { get; set; }
        [Required]
        [Column("CCE_9")]
        [StringLength(15)]
        public string Cce9 { get; set; }
        [Required]
        [Column("CCE_10")]
        [StringLength(15)]
        public string Cce10 { get; set; }
        [Required]
        [Column("CCE_11")]
        [StringLength(15)]
        public string Cce11 { get; set; }
        [Required]
        [Column("CCE_12")]
        [StringLength(15)]
        public string Cce12 { get; set; }
        [Required]
        [Column("CCE_13")]
        [StringLength(15)]
        public string Cce13 { get; set; }
        [Required]
        [Column("CCE_14")]
        [StringLength(15)]
        public string Cce14 { get; set; }
        [Required]
        [Column("CCE_15")]
        [StringLength(15)]
        public string Cce15 { get; set; }
        [Required]
        [Column("CCE_16")]
        [StringLength(15)]
        public string Cce16 { get; set; }
        [Required]
        [Column("CCE_17")]
        [StringLength(15)]
        public string Cce17 { get; set; }
        [Required]
        [Column("CCE_18")]
        [StringLength(15)]
        public string Cce18 { get; set; }
        [Required]
        [Column("CCE_19")]
        [StringLength(15)]
        public string Cce19 { get; set; }
        [Required]
        [Column("CUR_0")]
        [StringLength(3)]
        public string Cur0 { get; set; }
        [Required]
        [Column("CURLEDANA_0")]
        [StringLength(3)]
        public string Curledana0 { get; set; }
        [Column("CHGTYP_0")]
        public byte Chgtyp0 { get; set; }
        [Column("AMTATI_0", TypeName = "numeric(27, 13)")]
        public decimal Amtati0 { get; set; }
        [Column("AMTNOT_0", TypeName = "numeric(27, 13)")]
        public decimal Amtnot0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}