// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("REACHPAR", Schema = "TESTPROD")]
    [Index(nameof(Id0), Name = "REACHPAR_RPA0", IsUnique = true)]
    public partial class Reachpar
    {
        [Required]
        [Column("ID_0")]
        [StringLength(10)]
        public string Id0 { get; set; }
        [Required]
        [Column("INTIT_0")]
        [StringLength(30)]
        public string Intit0 { get; set; }
        [Required]
        [Column("ITMPIT_0")]
        [StringLength(10)]
        public string Itmpit0 { get; set; }
        [Required]
        [Column("ITMFOR_0")]
        [StringLength(3)]
        public string Itmfor0 { get; set; }
        [Column("ITMSRT_0")]
        public byte Itmsrt0 { get; set; }
        [Required]
        [Column("BPSPIT_0")]
        [StringLength(10)]
        public string Bpspit0 { get; set; }
        [Required]
        [Column("BPSFOR_0")]
        [StringLength(3)]
        public string Bpsfor0 { get; set; }
        [Required]
        [Column("DRTWRK_0")]
        [StringLength(250)]
        public string Drtwrk0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}