// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("RELBANKREM", Schema = "TESTPROD")]
    [Index(nameof(Ban0), nameof(Rbknum0), nameof(Rbklin0), nameof(Remnum0), Name = "RELBANKREM_CRR0", IsUnique = true)]
    public partial class Relbankrem
    {
        [Required]
        [Column("RBKNUM_0")]
        [StringLength(20)]
        public string Rbknum0 { get; set; }
        [Required]
        [Column("BAN_0")]
        [StringLength(5)]
        public string Ban0 { get; set; }
        [Column("RBKLIN_0")]
        public int Rbklin0 { get; set; }
        [Column("REMNUM_0")]
        public short Remnum0 { get; set; }
        [Required]
        [Column("REM_0")]
        [StringLength(80)]
        public string Rem0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}