// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("SCHEDULING", Schema = "TESTPROD")]
    [Index(nameof(Mfgnum0), nameof(Openum0), nameof(Opesplnum0), Name = "SCHEDULING_SCH0", IsUnique = true)]
    public partial class Scheduling
    {
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Required]
        [Column("PLNFCY_0")]
        [StringLength(5)]
        public string Plnfcy0 { get; set; }
        [Required]
        [Column("MFGFCY_0")]
        [StringLength(5)]
        public string Mfgfcy0 { get; set; }
        [Required]
        [Column("ROUNUM_0")]
        [StringLength(20)]
        public string Rounum0 { get; set; }
        [Column("ROUALT_0")]
        public short Roualt0 { get; set; }
        [Column("OPENUM_0")]
        public short Openum0 { get; set; }
        [Column("OPESPLNUM_0")]
        public short Opesplnum0 { get; set; }
        [Column("NEXOPENUM_0")]
        public short Nexopenum0 { get; set; }
        [Column("SCDCOD_0")]
        public byte Scdcod0 { get; set; }
        [Column("SCDTIM_0", TypeName = "numeric(13, 5)")]
        public decimal Scdtim0 { get; set; }
        [Column("SCDQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Scdqty0 { get; set; }
        [Column("SCDLOT_0", TypeName = "numeric(10, 3)")]
        public decimal Scdlot0 { get; set; }
        [Column("LOTQTY_0", TypeName = "numeric(28, 13)")]
        public decimal Lotqty0 { get; set; }
        [Column("INFCAPSTR_0", TypeName = "datetime")]
        public DateTime Infcapstr0 { get; set; }
        [Column("INFCAPEND_0", TypeName = "datetime")]
        public DateTime Infcapend0 { get; set; }
        [Column("DACMST_0")]
        public byte Dacmst0 { get; set; }
        [Column("MFGMST_0")]
        public byte Mfgmst0 { get; set; }
        [Required]
        [Column("CLCWST_0")]
        [StringLength(8)]
        public string Clcwst0 { get; set; }
        [Required]
        [Column("CLCLAB_0")]
        [StringLength(8)]
        public string Clclab0 { get; set; }
        [Column("CLCEXTTIM_0", TypeName = "numeric(14, 3)")]
        public decimal Clcexttim0 { get; set; }
        [Column("CLCPRPDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcprpdur0 { get; set; }
        [Column("CLCSETDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcsetdur0 { get; set; }
        [Column("CLCOPEDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcopedur0 { get; set; }
        [Column("CLCWORDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcwordur0 { get; set; }
        [Column("CLCPSTDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcpstdur0 { get; set; }
        [Column("CLCWAIDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcwaidur0 { get; set; }
        [Column("CLCAFTDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Clcaftdur0 { get; set; }
        [Column("SETLABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Setlabcoe0 { get; set; }
        [Column("OPELABCOE_0", TypeName = "numeric(10, 4)")]
        public decimal Opelabcoe0 { get; set; }
        [Column("INFCAPSTF_0", TypeName = "numeric(10, 5)")]
        public decimal Infcapstf0 { get; set; }
        [Column("INFCAPENF_0", TypeName = "numeric(10, 5)")]
        public decimal Infcapenf0 { get; set; }
        [Column("SETENDDAT_0", TypeName = "datetime")]
        public DateTime Setenddat0 { get; set; }
        [Column("SETENDFRD_0", TypeName = "numeric(10, 5)")]
        public decimal Setendfrd0 { get; set; }
        [Column("OPESTRDAT_0", TypeName = "datetime")]
        public DateTime Opestrdat0 { get; set; }
        [Column("OPESTRFRD_0", TypeName = "numeric(10, 5)")]
        public decimal Opestrfrd0 { get; set; }
        [Column("OPEENDDAT_0", TypeName = "datetime")]
        public DateTime Opeenddat0 { get; set; }
        [Column("OPEENDFRD_0", TypeName = "numeric(10, 5)")]
        public decimal Opeendfrd0 { get; set; }
        [Column("OPEFITSTD_0", TypeName = "datetime")]
        public DateTime Opefitstd0 { get; set; }
        [Column("OPEFITSTF_0", TypeName = "numeric(10, 5)")]
        public decimal Opefitstf0 { get; set; }
        [Column("FITCAPSTR_0", TypeName = "datetime")]
        public DateTime Fitcapstr0 { get; set; }
        [Column("FITCAPSTF_0", TypeName = "numeric(10, 5)")]
        public decimal Fitcapstf0 { get; set; }
        [Column("FITCAPEND_0", TypeName = "datetime")]
        public DateTime Fitcapend0 { get; set; }
        [Column("FITCAPENF_0", TypeName = "numeric(10, 5)")]
        public decimal Fitcapenf0 { get; set; }
        [Column("FITOPEEND_0", TypeName = "datetime")]
        public DateTime Fitopeend0 { get; set; }
        [Column("FITOPEENF_0", TypeName = "numeric(10, 5)")]
        public decimal Fitopeenf0 { get; set; }
        [Column("FITPRPDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Fitprpdur0 { get; set; }
        [Column("FITWORDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Fitwordur0 { get; set; }
        [Column("FITPSTDUR_0", TypeName = "numeric(14, 3)")]
        public decimal Fitpstdur0 { get; set; }
        [Column("FITDELAY_0", TypeName = "numeric(14, 3)")]
        public decimal Fitdelay0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}