// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("SCMAPAR", Schema = "TESTPROD")]
    [Index(nameof(Id0), Name = "SCMAPAR_SZP0", IsUnique = true)]
    public partial class Scmapar
    {
        [Required]
        [Column("ID_0")]
        [StringLength(10)]
        public string Id0 { get; set; }
        [Required]
        [Column("INTIT_0")]
        [StringLength(30)]
        public string Intit0 { get; set; }
        [Required]
        [Column("ITMPIT_0")]
        [StringLength(10)]
        public string Itmpit0 { get; set; }
        [Required]
        [Column("ITMFOR_0")]
        [StringLength(3)]
        public string Itmfor0 { get; set; }
        [Required]
        [Column("ITMTCOPIT_0")]
        [StringLength(10)]
        public string Itmtcopit0 { get; set; }
        [Column("PCU0FLG_0")]
        public byte Pcu0flg0 { get; set; }
        [Column("PCU1FLG_0")]
        public byte Pcu1flg0 { get; set; }
        [Column("PCU2FLG_0")]
        public byte Pcu2flg0 { get; set; }
        [Column("PCU3FLG_0")]
        public byte Pcu3flg0 { get; set; }
        [Required]
        [Column("ITMCRIPIT_0")]
        [StringLength(10)]
        public string Itmcripit0 { get; set; }
        [Column("ITMCRITYP_0")]
        public byte Itmcrityp0 { get; set; }
        [Column("TSICOD0FLG_0")]
        public byte Tsicod0flg0 { get; set; }
        [Column("TSICOD1FLG_0")]
        public byte Tsicod1flg0 { get; set; }
        [Column("TSICOD2FLG_0")]
        public byte Tsicod2flg0 { get; set; }
        [Column("TSICOD3FLG_0")]
        public byte Tsicod3flg0 { get; set; }
        [Column("TSICOD4FLG_0")]
        public byte Tsicod4flg0 { get; set; }
        [Column("TCLCODFLG_0")]
        public byte Tclcodflg0 { get; set; }
        [Column("CFGLINFLG_0")]
        public byte Cfglinflg0 { get; set; }
        [Column("PLANNERFLG_0")]
        public byte Plannerflg0 { get; set; }
        [Required]
        [Column("FCYPIT_0")]
        [StringLength(10)]
        public string Fcypit0 { get; set; }
        [Required]
        [Column("FCYCRIPIT_0")]
        [StringLength(10)]
        public string Fcycripit0 { get; set; }
        [Column("FCYCRITYP_0")]
        public byte Fcycrityp0 { get; set; }
        [Column("CRYFLG_0")]
        public byte Cryflg0 { get; set; }
        [Column("BCGCODFLG_0")]
        public byte Bcgcodflg0 { get; set; }
        [Column("TSCCOD0FLG_0")]
        public byte Tsccod0flg0 { get; set; }
        [Column("TSCCOD1FLG_0")]
        public byte Tsccod1flg0 { get; set; }
        [Column("TSCCOD2FLG_0")]
        public byte Tsccod2flg0 { get; set; }
        [Column("TSCCOD3FLG_0")]
        public byte Tsccod3flg0 { get; set; }
        [Column("TSCCOD4FLG_0")]
        public byte Tsccod4flg0 { get; set; }
        [Column("BPCINVFLG_0")]
        public byte Bpcinvflg0 { get; set; }
        [Column("BPCGRUFLG_0")]
        public byte Bpcgruflg0 { get; set; }
        [Column("SOHGRU_0")]
        public byte Sohgru0 { get; set; }
        [Required]
        [Column("SOHFOR_0")]
        [StringLength(3)]
        public string Sohfor0 { get; set; }
        [Required]
        [Column("HISSOHPIT_0")]
        [StringLength(10)]
        public string Hissohpit0 { get; set; }
        [Column("HISSOHFLG_0")]
        public byte Hissohflg0 { get; set; }
        [Column("HISSDHFLG_0")]
        public byte Hissdhflg0 { get; set; }
        [Required]
        [Column("SDHFOR_0")]
        [StringLength(3)]
        public string Sdhfor0 { get; set; }
        [Required]
        [Column("SOHPIT_0")]
        [StringLength(10)]
        public string Sohpit0 { get; set; }
        [Column("SOSRAZFLG_0")]
        public byte Sosrazflg0 { get; set; }
        [Column("SOSDLTFLG_0")]
        public byte Sosdltflg0 { get; set; }
        [Required]
        [Column("SOSPIT_0")]
        [StringLength(10)]
        public string Sospit0 { get; set; }
        [Required]
        [Column("DRTWRK_0")]
        [StringLength(250)]
        public string Drtwrk0 { get; set; }
        [Required]
        [Column("DRTSTO_0")]
        [StringLength(250)]
        public string Drtsto0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}