// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("SINVOICEV", Schema = "TESTPROD")]
    [Index(nameof(Num0), Name = "SINVOICEV_SIV0", IsUnique = true)]
    [Index(nameof(Sihori0), nameof(Sihorinum0), Name = "SINVOICEV_SIV1")]
    [Index(nameof(Invtyp0), nameof(Num0), Name = "SINVOICEV_SIV2", IsUnique = true)]
    public partial class Sinvoicev
    {
        [Required]
        [Column("NUM_0")]
        [StringLength(20)]
        public string Num0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Required]
        [Column("SALFCY_0")]
        [StringLength(5)]
        public string Salfcy0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("BPCINV_0")]
        [StringLength(15)]
        public string Bpcinv0 { get; set; }
        [Required]
        [Column("BPCORD_0")]
        [StringLength(15)]
        public string Bpcord0 { get; set; }
        [Required]
        [Column("BPCGRU_0")]
        [StringLength(15)]
        public string Bpcgru0 { get; set; }
        [Required]
        [Column("BPAADD_0")]
        [StringLength(7)]
        public string Bpaadd0 { get; set; }
        [Required]
        [Column("BPINAM_0")]
        [StringLength(35)]
        public string Bpinam0 { get; set; }
        [Required]
        [Column("BPINAM_1")]
        [StringLength(35)]
        public string Bpinam1 { get; set; }
        [Required]
        [Column("BPIEECNUM_0")]
        [StringLength(20)]
        public string Bpieecnum0 { get; set; }
        [Required]
        [Column("CNINAM_0")]
        [StringLength(15)]
        public string Cninam0 { get; set; }
        [Required]
        [Column("BPDNAM_0")]
        [StringLength(35)]
        public string Bpdnam0 { get; set; }
        [Required]
        [Column("BPDNAM_1")]
        [StringLength(35)]
        public string Bpdnam1 { get; set; }
        [Required]
        [Column("BPDADDLIG_0")]
        [StringLength(40)]
        public string Bpdaddlig0 { get; set; }
        [Required]
        [Column("BPDADDLIG_1")]
        [StringLength(40)]
        public string Bpdaddlig1 { get; set; }
        [Required]
        [Column("BPDADDLIG_2")]
        [StringLength(40)]
        public string Bpdaddlig2 { get; set; }
        [Required]
        [Column("BPDPOSCOD_0")]
        [StringLength(10)]
        public string Bpdposcod0 { get; set; }
        [Required]
        [Column("BPDCTY_0")]
        [StringLength(40)]
        public string Bpdcty0 { get; set; }
        [Required]
        [Column("BPDSAT_0")]
        [StringLength(35)]
        public string Bpdsat0 { get; set; }
        [Required]
        [Column("BPDCRY_0")]
        [StringLength(3)]
        public string Bpdcry0 { get; set; }
        [Required]
        [Column("BPDCRYNAM_0")]
        [StringLength(40)]
        public string Bpdcrynam0 { get; set; }
        [Required]
        [Column("CNDNAM_0")]
        [StringLength(15)]
        public string Cndnam0 { get; set; }
        [Required]
        [Column("BPRPAY_0")]
        [StringLength(15)]
        public string Bprpay0 { get; set; }
        [Required]
        [Column("BPRFCT_0")]
        [StringLength(1)]
        public string Bprfct0 { get; set; }
        [Required]
        [Column("SIVTYP_0")]
        [StringLength(5)]
        public string Sivtyp0 { get; set; }
        [Column("INVTYP_0")]
        public byte Invtyp0 { get; set; }
        [Column("SIHORI_0")]
        public byte Sihori0 { get; set; }
        [Required]
        [Column("SIHORINUM_0")]
        [StringLength(20)]
        public string Sihorinum0 { get; set; }
        [Column("SIHORIDAT_0", TypeName = "datetime")]
        public DateTime Sihoridat0 { get; set; }
        [Column("INVDAT_0", TypeName = "datetime")]
        public DateTime Invdat0 { get; set; }
        [Required]
        [Column("CUR_0")]
        [StringLength(3)]
        public string Cur0 { get; set; }
        [Column("INVSTA_0")]
        public byte Invsta0 { get; set; }
        [Column("INVCNOSTA_0")]
        public byte Invcnosta0 { get; set; }
        [Column("STOMVTFLG_0")]
        public byte Stomvtflg0 { get; set; }
        [Required]
        [Column("INVREF_0")]
        [StringLength(30)]
        public string Invref0 { get; set; }
        [Required]
        [Column("PJT_0")]
        [StringLength(20)]
        public string Pjt0 { get; set; }
        [Column("PRITYP_0")]
        public byte Prityp0 { get; set; }
        [Required]
        [Column("REP_0")]
        [StringLength(15)]
        public string Rep0 { get; set; }
        [Required]
        [Column("REP_1")]
        [StringLength(15)]
        public string Rep1 { get; set; }
        [Required]
        [Column("CNOREN_0")]
        [StringLength(20)]
        public string Cnoren0 { get; set; }
        [Required]
        [Column("DEP_0")]
        [StringLength(3)]
        public string Dep0 { get; set; }
        [Required]
        [Column("LAN_0")]
        [StringLength(3)]
        public string Lan0 { get; set; }
        [Required]
        [Column("TSCCOD_0")]
        [StringLength(20)]
        public string Tsccod0 { get; set; }
        [Required]
        [Column("TSCCOD_1")]
        [StringLength(20)]
        public string Tsccod1 { get; set; }
        [Required]
        [Column("TSCCOD_2")]
        [StringLength(20)]
        public string Tsccod2 { get; set; }
        [Required]
        [Column("TSCCOD_3")]
        [StringLength(20)]
        public string Tsccod3 { get; set; }
        [Required]
        [Column("TSCCOD_4")]
        [StringLength(20)]
        public string Tsccod4 { get; set; }
        [Required]
        [Column("SIHTEX1_0")]
        [StringLength(12)]
        public string Sihtex10 { get; set; }
        [Required]
        [Column("SIHTEX2_0")]
        [StringLength(12)]
        public string Sihtex20 { get; set; }
        [Column("BETFCY_0")]
        public byte Betfcy0 { get; set; }
        [Column("BETCPY_0")]
        public byte Betcpy0 { get; set; }
        [Required]
        [Column("ORIFCY_0")]
        [StringLength(5)]
        public string Orifcy0 { get; set; }
        [Required]
        [Column("PIHNUM_0")]
        [StringLength(20)]
        public string Pihnum0 { get; set; }
        [Column("DISCRGTYP_0")]
        public byte Discrgtyp0 { get; set; }
        [Column("DISCRGTYP_1")]
        public byte Discrgtyp1 { get; set; }
        [Column("DISCRGTYP_2")]
        public byte Discrgtyp2 { get; set; }
        [Column("DISCRGTYP_3")]
        public byte Discrgtyp3 { get; set; }
        [Column("DISCRGTYP_4")]
        public byte Discrgtyp4 { get; set; }
        [Column("DISCRGTYP_5")]
        public byte Discrgtyp5 { get; set; }
        [Column("DISCRGTYP_6")]
        public byte Discrgtyp6 { get; set; }
        [Column("DISCRGTYP_7")]
        public byte Discrgtyp7 { get; set; }
        [Column("DISCRGTYP_8")]
        public byte Discrgtyp8 { get; set; }
        [Column("INVDTALIN_0")]
        public short Invdtalin0 { get; set; }
        [Column("INVDTALIN_1")]
        public short Invdtalin1 { get; set; }
        [Column("INVDTALIN_2")]
        public short Invdtalin2 { get; set; }
        [Column("INVDTALIN_3")]
        public short Invdtalin3 { get; set; }
        [Column("INVDTALIN_4")]
        public short Invdtalin4 { get; set; }
        [Column("INVDTALIN_5")]
        public short Invdtalin5 { get; set; }
        [Column("INVDTALIN_6")]
        public short Invdtalin6 { get; set; }
        [Column("INVDTALIN_7")]
        public short Invdtalin7 { get; set; }
        [Column("INVDTALIN_8")]
        public short Invdtalin8 { get; set; }
        [Column("LINNBR_0")]
        public short Linnbr0 { get; set; }
        [Column("INVDTA_0")]
        public short Invdta0 { get; set; }
        [Column("INVDTA_1")]
        public short Invdta1 { get; set; }
        [Column("INVDTA_2")]
        public short Invdta2 { get; set; }
        [Column("INVDTA_3")]
        public short Invdta3 { get; set; }
        [Column("INVDTA_4")]
        public short Invdta4 { get; set; }
        [Column("INVDTA_5")]
        public short Invdta5 { get; set; }
        [Column("INVDTA_6")]
        public short Invdta6 { get; set; }
        [Column("INVDTA_7")]
        public short Invdta7 { get; set; }
        [Column("INVDTA_8")]
        public short Invdta8 { get; set; }
        [Column("INVDTA_9")]
        public short Invdta9 { get; set; }
        [Column("INVDTA_10")]
        public short Invdta10 { get; set; }
        [Column("INVDTA_11")]
        public short Invdta11 { get; set; }
        [Column("INVDTA_12")]
        public short Invdta12 { get; set; }
        [Column("INVDTA_13")]
        public short Invdta13 { get; set; }
        [Column("INVDTA_14")]
        public short Invdta14 { get; set; }
        [Column("INVDTA_15")]
        public short Invdta15 { get; set; }
        [Column("INVDTA_16")]
        public short Invdta16 { get; set; }
        [Column("INVDTA_17")]
        public short Invdta17 { get; set; }
        [Column("INVDTA_18")]
        public short Invdta18 { get; set; }
        [Column("INVDTA_19")]
        public short Invdta19 { get; set; }
        [Column("INVDTA_20")]
        public short Invdta20 { get; set; }
        [Column("INVDTA_21")]
        public short Invdta21 { get; set; }
        [Column("INVDTA_22")]
        public short Invdta22 { get; set; }
        [Column("INVDTA_23")]
        public short Invdta23 { get; set; }
        [Column("INVDTA_24")]
        public short Invdta24 { get; set; }
        [Column("INVDTA_25")]
        public short Invdta25 { get; set; }
        [Column("INVDTA_26")]
        public short Invdta26 { get; set; }
        [Column("INVDTA_27")]
        public short Invdta27 { get; set; }
        [Column("INVDTA_28")]
        public short Invdta28 { get; set; }
        [Column("INVDTA_29")]
        public short Invdta29 { get; set; }
        [Column("INVDTAAMT_0", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt0 { get; set; }
        [Column("INVDTAAMT_1", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt1 { get; set; }
        [Column("INVDTAAMT_2", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt2 { get; set; }
        [Column("INVDTAAMT_3", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt3 { get; set; }
        [Column("INVDTAAMT_4", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt4 { get; set; }
        [Column("INVDTAAMT_5", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt5 { get; set; }
        [Column("INVDTAAMT_6", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt6 { get; set; }
        [Column("INVDTAAMT_7", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt7 { get; set; }
        [Column("INVDTAAMT_8", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt8 { get; set; }
        [Column("INVDTAAMT_9", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt9 { get; set; }
        [Column("INVDTAAMT_10", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt10 { get; set; }
        [Column("INVDTAAMT_11", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt11 { get; set; }
        [Column("INVDTAAMT_12", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt12 { get; set; }
        [Column("INVDTAAMT_13", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt13 { get; set; }
        [Column("INVDTAAMT_14", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt14 { get; set; }
        [Column("INVDTAAMT_15", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt15 { get; set; }
        [Column("INVDTAAMT_16", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt16 { get; set; }
        [Column("INVDTAAMT_17", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt17 { get; set; }
        [Column("INVDTAAMT_18", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt18 { get; set; }
        [Column("INVDTAAMT_19", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt19 { get; set; }
        [Column("INVDTAAMT_20", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt20 { get; set; }
        [Column("INVDTAAMT_21", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt21 { get; set; }
        [Column("INVDTAAMT_22", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt22 { get; set; }
        [Column("INVDTAAMT_23", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt23 { get; set; }
        [Column("INVDTAAMT_24", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt24 { get; set; }
        [Column("INVDTAAMT_25", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt25 { get; set; }
        [Column("INVDTAAMT_26", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt26 { get; set; }
        [Column("INVDTAAMT_27", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt27 { get; set; }
        [Column("INVDTAAMT_28", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt28 { get; set; }
        [Column("INVDTAAMT_29", TypeName = "numeric(20, 5)")]
        public decimal Invdtaamt29 { get; set; }
        [Column("INVDTATYP_0")]
        public byte Invdtatyp0 { get; set; }
        [Column("INVDTATYP_1")]
        public byte Invdtatyp1 { get; set; }
        [Column("INVDTATYP_2")]
        public byte Invdtatyp2 { get; set; }
        [Column("INVDTATYP_3")]
        public byte Invdtatyp3 { get; set; }
        [Column("INVDTATYP_4")]
        public byte Invdtatyp4 { get; set; }
        [Column("INVDTATYP_5")]
        public byte Invdtatyp5 { get; set; }
        [Column("INVDTATYP_6")]
        public byte Invdtatyp6 { get; set; }
        [Column("INVDTATYP_7")]
        public byte Invdtatyp7 { get; set; }
        [Column("INVDTATYP_8")]
        public byte Invdtatyp8 { get; set; }
        [Column("INVDTATYP_9")]
        public byte Invdtatyp9 { get; set; }
        [Column("INVDTATYP_10")]
        public byte Invdtatyp10 { get; set; }
        [Column("INVDTATYP_11")]
        public byte Invdtatyp11 { get; set; }
        [Column("INVDTATYP_12")]
        public byte Invdtatyp12 { get; set; }
        [Column("INVDTATYP_13")]
        public byte Invdtatyp13 { get; set; }
        [Column("INVDTATYP_14")]
        public byte Invdtatyp14 { get; set; }
        [Column("INVDTATYP_15")]
        public byte Invdtatyp15 { get; set; }
        [Column("INVDTATYP_16")]
        public byte Invdtatyp16 { get; set; }
        [Column("INVDTATYP_17")]
        public byte Invdtatyp17 { get; set; }
        [Column("INVDTATYP_18")]
        public byte Invdtatyp18 { get; set; }
        [Column("INVDTATYP_19")]
        public byte Invdtatyp19 { get; set; }
        [Column("INVDTATYP_20")]
        public byte Invdtatyp20 { get; set; }
        [Column("INVDTATYP_21")]
        public byte Invdtatyp21 { get; set; }
        [Column("INVDTATYP_22")]
        public byte Invdtatyp22 { get; set; }
        [Column("INVDTATYP_23")]
        public byte Invdtatyp23 { get; set; }
        [Column("INVDTATYP_24")]
        public byte Invdtatyp24 { get; set; }
        [Column("INVDTATYP_25")]
        public byte Invdtatyp25 { get; set; }
        [Column("INVDTATYP_26")]
        public byte Invdtatyp26 { get; set; }
        [Column("INVDTATYP_27")]
        public byte Invdtatyp27 { get; set; }
        [Column("INVDTATYP_28")]
        public byte Invdtatyp28 { get; set; }
        [Column("INVDTATYP_29")]
        public byte Invdtatyp29 { get; set; }
        [Required]
        [Column("INVDTADSP_0")]
        [StringLength(10)]
        public string Invdtadsp0 { get; set; }
        [Required]
        [Column("INVDTADSP_1")]
        [StringLength(10)]
        public string Invdtadsp1 { get; set; }
        [Required]
        [Column("INVDTADSP_2")]
        [StringLength(10)]
        public string Invdtadsp2 { get; set; }
        [Required]
        [Column("INVDTADSP_3")]
        [StringLength(10)]
        public string Invdtadsp3 { get; set; }
        [Required]
        [Column("INVDTADSP_4")]
        [StringLength(10)]
        public string Invdtadsp4 { get; set; }
        [Required]
        [Column("INVDTADSP_5")]
        [StringLength(10)]
        public string Invdtadsp5 { get; set; }
        [Required]
        [Column("INVDTADSP_6")]
        [StringLength(10)]
        public string Invdtadsp6 { get; set; }
        [Required]
        [Column("INVDTADSP_7")]
        [StringLength(10)]
        public string Invdtadsp7 { get; set; }
        [Required]
        [Column("INVDTADSP_8")]
        [StringLength(10)]
        public string Invdtadsp8 { get; set; }
        [Required]
        [Column("INVDTADSP_9")]
        [StringLength(10)]
        public string Invdtadsp9 { get; set; }
        [Required]
        [Column("INVDTADSP_10")]
        [StringLength(10)]
        public string Invdtadsp10 { get; set; }
        [Required]
        [Column("INVDTADSP_11")]
        [StringLength(10)]
        public string Invdtadsp11 { get; set; }
        [Required]
        [Column("INVDTADSP_12")]
        [StringLength(10)]
        public string Invdtadsp12 { get; set; }
        [Required]
        [Column("INVDTADSP_13")]
        [StringLength(10)]
        public string Invdtadsp13 { get; set; }
        [Required]
        [Column("INVDTADSP_14")]
        [StringLength(10)]
        public string Invdtadsp14 { get; set; }
        [Required]
        [Column("INVDTADSP_15")]
        [StringLength(10)]
        public string Invdtadsp15 { get; set; }
        [Required]
        [Column("INVDTADSP_16")]
        [StringLength(10)]
        public string Invdtadsp16 { get; set; }
        [Required]
        [Column("INVDTADSP_17")]
        [StringLength(10)]
        public string Invdtadsp17 { get; set; }
        [Required]
        [Column("INVDTADSP_18")]
        [StringLength(10)]
        public string Invdtadsp18 { get; set; }
        [Required]
        [Column("INVDTADSP_19")]
        [StringLength(10)]
        public string Invdtadsp19 { get; set; }
        [Required]
        [Column("INVDTADSP_20")]
        [StringLength(10)]
        public string Invdtadsp20 { get; set; }
        [Required]
        [Column("INVDTADSP_21")]
        [StringLength(10)]
        public string Invdtadsp21 { get; set; }
        [Required]
        [Column("INVDTADSP_22")]
        [StringLength(10)]
        public string Invdtadsp22 { get; set; }
        [Required]
        [Column("INVDTADSP_23")]
        [StringLength(10)]
        public string Invdtadsp23 { get; set; }
        [Required]
        [Column("INVDTADSP_24")]
        [StringLength(10)]
        public string Invdtadsp24 { get; set; }
        [Required]
        [Column("INVDTADSP_25")]
        [StringLength(10)]
        public string Invdtadsp25 { get; set; }
        [Required]
        [Column("INVDTADSP_26")]
        [StringLength(10)]
        public string Invdtadsp26 { get; set; }
        [Required]
        [Column("INVDTADSP_27")]
        [StringLength(10)]
        public string Invdtadsp27 { get; set; }
        [Required]
        [Column("INVDTADSP_28")]
        [StringLength(10)]
        public string Invdtadsp28 { get; set; }
        [Required]
        [Column("INVDTADSP_29")]
        [StringLength(10)]
        public string Invdtadsp29 { get; set; }
        [Required]
        [Column("PAM_0")]
        [StringLength(20)]
        public string Pam0 { get; set; }
        [Required]
        [Column("PAM_1")]
        [StringLength(20)]
        public string Pam1 { get; set; }
        [Required]
        [Column("PAM_2")]
        [StringLength(20)]
        public string Pam2 { get; set; }
        [Required]
        [Column("PAM_3")]
        [StringLength(20)]
        public string Pam3 { get; set; }
        [Column("INSATI_0", TypeName = "numeric(27, 13)")]
        public decimal Insati0 { get; set; }
        [Column("INSATI_1", TypeName = "numeric(27, 13)")]
        public decimal Insati1 { get; set; }
        [Column("INSATI_2", TypeName = "numeric(27, 13)")]
        public decimal Insati2 { get; set; }
        [Column("INSATI_3", TypeName = "numeric(27, 13)")]
        public decimal Insati3 { get; set; }
        [Required]
        [Column("INSORDNUM_0")]
        [StringLength(20)]
        public string Insordnum0 { get; set; }
        [Required]
        [Column("INSORDNUM_1")]
        [StringLength(20)]
        public string Insordnum1 { get; set; }
        [Required]
        [Column("INSORDNUM_2")]
        [StringLength(20)]
        public string Insordnum2 { get; set; }
        [Required]
        [Column("INSORDNUM_3")]
        [StringLength(20)]
        public string Insordnum3 { get; set; }
        [Column("INSLIN_0")]
        public short Inslin0 { get; set; }
        [Column("INSLIN_1")]
        public short Inslin1 { get; set; }
        [Column("INSLIN_2")]
        public short Inslin2 { get; set; }
        [Column("INSLIN_3")]
        public short Inslin3 { get; set; }
        [Column("COPNBR_0")]
        public short Copnbr0 { get; set; }
        [Column("COPNBE_0")]
        public short Copnbe0 { get; set; }
        [Required]
        [Column("TRSCOD_0")]
        [StringLength(20)]
        public string Trscod0 { get; set; }
        [Required]
        [Column("ENTCOD_0")]
        [StringLength(5)]
        public string Entcod0 { get; set; }
        [Required]
        [Column("SRGLOCDEF_0")]
        [StringLength(10)]
        public string Srglocdef0 { get; set; }
        [Required]
        [Column("EECNAT_0")]
        [StringLength(20)]
        public string Eecnat0 { get; set; }
        [Required]
        [Column("EECNATR_0")]
        [StringLength(20)]
        public string Eecnatr0 { get; set; }
        [Required]
        [Column("EECSCH_0")]
        [StringLength(20)]
        public string Eecsch0 { get; set; }
        [Required]
        [Column("EECSCHR_0")]
        [StringLength(20)]
        public string Eecschr0 { get; set; }
        [Column("EECLOC_0")]
        public byte Eecloc0 { get; set; }
        [Column("EECTRN_0")]
        public byte Eectrn0 { get; set; }
        [Required]
        [Column("EECICT_0")]
        [StringLength(20)]
        public string Eecict0 { get; set; }
        [Required]
        [Column("ICTCTY_0")]
        [StringLength(40)]
        public string Ictcty0 { get; set; }
        [Required]
        [Column("FFWNUM_0")]
        [StringLength(15)]
        public string Ffwnum0 { get; set; }
        [Required]
        [Column("FFWADD_0")]
        [StringLength(7)]
        public string Ffwadd0 { get; set; }
        [Required]
        [Column("GEOCOD_0")]
        [StringLength(9)]
        public string Geocod0 { get; set; }
        [Required]
        [Column("INSCTYFLG_0")]
        [StringLength(1)]
        public string Insctyflg0 { get; set; }
        [Required]
        [Column("VTT_0")]
        [StringLength(1)]
        public string Vtt0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Required]
        [Column("CMGNUM_0")]
        [StringLength(20)]
        public string Cmgnum0 { get; set; }
        [Required]
        [Column("OPGNUM_0")]
        [StringLength(20)]
        public string Opgnum0 { get; set; }
        [Required]
        [Column("OPGTYP_0")]
        [StringLength(3)]
        public string Opgtyp0 { get; set; }
        [Required]
        [Column("PLISTC_0")]
        [StringLength(10)]
        public string Plistc0 { get; set; }
        [Column("DSPTOTQTY_0", TypeName = "numeric(22, 7)")]
        public decimal Dsptotqty0 { get; set; }
        [Column("DSPTOTWEI_0", TypeName = "numeric(28, 13)")]
        public decimal Dsptotwei0 { get; set; }
        [Column("DSPTOTVOL_0", TypeName = "numeric(28, 13)")]
        public decimal Dsptotvol0 { get; set; }
        [Required]
        [Column("DSPWEU_0")]
        [StringLength(3)]
        public string Dspweu0 { get; set; }
        [Required]
        [Column("DSPVOU_0")]
        [StringLength(3)]
        public string Dspvou0 { get; set; }
        [Column("STARPT_0")]
        public byte Starpt0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("XA_RPTTYP4_0")]
        public short XaRpttyp40 { get; set; }
        [Column("XA_OUTTYP4_0")]
        public short XaOuttyp40 { get; set; }
        [Required]
        [Column("XA_CONTACT4_0")]
        [StringLength(1)]
        public string XaContact40 { get; set; }
        [Required]
        [Column("XA_FAX_0")]
        [StringLength(1)]
        public string XaFax0 { get; set; }
        [Required]
        [Column("XA_WEB_0")]
        [StringLength(1)]
        public string XaWeb0 { get; set; }
        [Column("XB_810STA_0")]
        public byte Xb810sta0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}