// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("STATPRV", Schema = "TESTPROD")]
    [Index(nameof(Cod0), nameof(Cpy0), nameof(Fcy0), nameof(Dat0), nameof(Cri10), nameof(Cri20), nameof(Cri30), nameof(Cri40), nameof(Cri50), Name = "STATPRV_SAP0", IsUnique = true)]
    public partial class Statprv
    {
        [Required]
        [Column("COD_0")]
        [StringLength(5)]
        public string Cod0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Required]
        [Column("FCY_0")]
        [StringLength(5)]
        public string Fcy0 { get; set; }
        [Column("DAT_0", TypeName = "datetime")]
        public DateTime Dat0 { get; set; }
        [Required]
        [Column("CRI1_0")]
        [StringLength(20)]
        public string Cri10 { get; set; }
        [Required]
        [Column("CRI2_0")]
        [StringLength(20)]
        public string Cri20 { get; set; }
        [Required]
        [Column("CRI3_0")]
        [StringLength(20)]
        public string Cri30 { get; set; }
        [Required]
        [Column("CRI4_0")]
        [StringLength(20)]
        public string Cri40 { get; set; }
        [Required]
        [Column("CRI5_0")]
        [StringLength(20)]
        public string Cri50 { get; set; }
        [Required]
        [Column("CRI6_0")]
        [StringLength(1)]
        public string Cri60 { get; set; }
        [Required]
        [Column("CRI7_0")]
        [StringLength(1)]
        public string Cri70 { get; set; }
        [Required]
        [Column("CRI8_0")]
        [StringLength(1)]
        public string Cri80 { get; set; }
        [Column("AMT_0", TypeName = "numeric(25, 12)")]
        public decimal Amt0 { get; set; }
        [Column("AMT_1", TypeName = "numeric(25, 12)")]
        public decimal Amt1 { get; set; }
        [Column("AMT_2", TypeName = "numeric(25, 12)")]
        public decimal Amt2 { get; set; }
        [Column("AMT_3", TypeName = "numeric(25, 12)")]
        public decimal Amt3 { get; set; }
        [Column("AMT_4", TypeName = "numeric(25, 12)")]
        public decimal Amt4 { get; set; }
        [Column("AMT_5", TypeName = "numeric(25, 12)")]
        public decimal Amt5 { get; set; }
        [Column("AMT_6", TypeName = "numeric(25, 12)")]
        public decimal Amt6 { get; set; }
        [Column("AMT_7", TypeName = "numeric(25, 12)")]
        public decimal Amt7 { get; set; }
        [Column("AMT_8", TypeName = "numeric(25, 12)")]
        public decimal Amt8 { get; set; }
        [Column("AMT_9", TypeName = "numeric(25, 12)")]
        public decimal Amt9 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}