// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("STJTMP", Schema = "TESTPROD")]
    [Index(nameof(Entcod0), nameof(Cpy0), nameof(Key10), nameof(Key20), nameof(Key30), nameof(Key40), nameof(Key50), nameof(Stofcy0), nameof(Updcod0), nameof(Itmref0), nameof(Iptdat0), nameof(Mvtseq0), nameof(Mvtind0), Name = "STJTMP_SJT0", IsUnique = true)]
    public partial class Stjtmp
    {
        [Required]
        [Column("ENTCOD_0")]
        [StringLength(5)]
        public string Entcod0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Column("PSTOJOU_0")]
        public int Pstojou0 { get; set; }
        [Required]
        [Column("KEY1_0")]
        [StringLength(30)]
        public string Key10 { get; set; }
        [Required]
        [Column("KEY2_0")]
        [StringLength(30)]
        public string Key20 { get; set; }
        [Required]
        [Column("KEY3_0")]
        [StringLength(30)]
        public string Key30 { get; set; }
        [Required]
        [Column("KEY4_0")]
        [StringLength(30)]
        public string Key40 { get; set; }
        [Required]
        [Column("KEY5_0")]
        [StringLength(30)]
        public string Key50 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Column("UPDCOD_0")]
        public byte Updcod0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("IPTDAT_0", TypeName = "datetime")]
        public DateTime Iptdat0 { get; set; }
        [Column("MVTSEQ_0")]
        public int Mvtseq0 { get; set; }
        [Column("MVTIND_0")]
        public int Mvtind0 { get; set; }
        [Column("VCRTYP_0")]
        public byte Vcrtyp0 { get; set; }
        [Column("TRSTYP_0")]
        public byte Trstyp0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}