// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("STKMVTITC", Schema = "TESTPROD")]
    [Index(nameof(Itcstrdat0), nameof(Itmref0), nameof(Stofcy0), nameof(Csttyp0), Name = "STKMVTITC_SMI0", IsUnique = true)]
    public partial class Stkmvtitc
    {
        [Column("ITCSTRDAT_0", TypeName = "datetime")]
        public DateTime Itcstrdat0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("CSTTYP_0")]
        public byte Csttyp0 { get; set; }
        [Column("ITCSEQ_0")]
        public int Itcseq0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}