// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("STOJOUOVE", Schema = "TESTPROD")]
    [Index(nameof(Stofcy0), nameof(Updcod0), nameof(Itmref0), nameof(Iptdat0), nameof(Mvtseq0), nameof(Mvtind0), nameof(Ovenat0), Name = "STOJOUOVE_SJV0", IsUnique = true)]
    public partial class Stojouove
    {
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Column("UPDCOD_0")]
        public byte Updcod0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("IPTDAT_0", TypeName = "datetime")]
        public DateTime Iptdat0 { get; set; }
        [Column("MVTSEQ_0")]
        public int Mvtseq0 { get; set; }
        [Column("MVTIND_0")]
        public int Mvtind0 { get; set; }
        [Required]
        [Column("OVENAT_0")]
        [StringLength(3)]
        public string Ovenat0 { get; set; }
        [Column("TYPCST_0")]
        public byte Typcst0 { get; set; }
        [Column("ONAAMT_0", TypeName = "numeric(27, 13)")]
        public decimal Onaamt0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}