// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("STOPREH", Schema = "TESTPROD")]
    [Index(nameof(Prhnum0), Name = "STOPREH_PRH0", IsUnique = true)]
    [Index(nameof(Stofcy0), nameof(Dlvflg0), nameof(Prhnum0), Name = "STOPREH_PRH1", IsUnique = true)]
    [Index(nameof(Stofcy0), nameof(Prlnum0), nameof(Dlvflg0), nameof(Prhnum0), Name = "STOPREH_PRH2", IsUnique = true)]
    [Index(nameof(Sdhnum0), nameof(Prhnum0), Name = "STOPREH_PRH3", IsUnique = true)]
    public partial class Stopreh
    {
        [Required]
        [Column("PRHNUM_0")]
        [StringLength(20)]
        public string Prhnum0 { get; set; }
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("CPY_0")]
        [StringLength(5)]
        public string Cpy0 { get; set; }
        [Column("ORIPRH_0")]
        public byte Oriprh0 { get; set; }
        [Required]
        [Column("PRLNUM_0")]
        [StringLength(20)]
        public string Prlnum0 { get; set; }
        [Required]
        [Column("SDHNUM_0")]
        [StringLength(20)]
        public string Sdhnum0 { get; set; }
        [Required]
        [Column("BPCORD_0")]
        [StringLength(15)]
        public string Bpcord0 { get; set; }
        [Required]
        [Column("BPAADD_0")]
        [StringLength(7)]
        public string Bpaadd0 { get; set; }
        [Column("SHIDAT_0", TypeName = "datetime")]
        public DateTime Shidat0 { get; set; }
        [Column("DLVDAT_0", TypeName = "datetime")]
        public DateTime Dlvdat0 { get; set; }
        [Required]
        [Column("BPTNUM_0")]
        [StringLength(15)]
        public string Bptnum0 { get; set; }
        [Column("DRN_0")]
        public byte Drn0 { get; set; }
        [Required]
        [Column("PRECOD_0")]
        [StringLength(5)]
        public string Precod0 { get; set; }
        [Column("DLVFLG_0")]
        public byte Dlvflg0 { get; set; }
        [Column("PACFLG_0")]
        public byte Pacflg0 { get; set; }
        [Column("PACNBR_0")]
        public short Pacnbr0 { get; set; }
        [Column("PRNNPR_0")]
        public byte Prnnpr0 { get; set; }
        [Required]
        [Column("TRSCOD_0")]
        [StringLength(20)]
        public string Trscod0 { get; set; }
        [Required]
        [Column("WEU_0")]
        [StringLength(3)]
        public string Weu0 { get; set; }
        [Column("GROWEI_0", TypeName = "numeric(13, 4)")]
        public decimal Growei0 { get; set; }
        [Column("NETWEI_0", TypeName = "numeric(13, 4)")]
        public decimal Netwei0 { get; set; }
        [Required]
        [Column("PRPTEX1_0")]
        [StringLength(12)]
        public string Prptex10 { get; set; }
        [Required]
        [Column("PRPTEX2_0")]
        [StringLength(12)]
        public string Prptex20 { get; set; }
        [Required]
        [Column("PREUSR_0")]
        [StringLength(5)]
        public string Preusr0 { get; set; }
        [Column("EXPNUM_0")]
        public int Expnum0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}