// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("TABMSG", Schema = "TESTPROD")]
    [Index(nameof(Msgnum0), Name = "TABMSG_TMS0", IsUnique = true)]
    public partial class Tabmsg
    {
        [Column("MSGNUM_0")]
        public short Msgnum0 { get; set; }
        [Required]
        [Column("MSGDES_0")]
        [StringLength(70)]
        public string Msgdes0 { get; set; }
        [Required]
        [Column("MSGSHO_0")]
        [StringLength(10)]
        public string Msgsho0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}