// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("TXSV", Schema = "TESTPROD")]
    [Index(nameof(Txsnam0), nameof(Version0), nameof(Varnam0), Name = "TXSV_TXX0", IsUnique = true)]
    public partial class Txsv
    {
        [Required]
        [Column("TXSNAM_0")]
        [StringLength(10)]
        public string Txsnam0 { get; set; }
        [Required]
        [Column("VERSION_0")]
        [StringLength(15)]
        public string Version0 { get; set; }
        [Required]
        [Column("LSTGRP_0")]
        [StringLength(8)]
        public string Lstgrp0 { get; set; }
        [Required]
        [Column("VARNAM_0")]
        [StringLength(10)]
        public string Varnam0 { get; set; }
        [Required]
        [Column("VARTYP_0")]
        [StringLength(3)]
        public string Vartyp0 { get; set; }
        [Required]
        [Column("VARPAR_0")]
        [StringLength(10)]
        public string Varpar0 { get; set; }
        [Required]
        [Column("VARDES_0")]
        [StringLength(40)]
        public string Vardes0 { get; set; }
        [Required]
        [Column("VARDEF_0")]
        [StringLength(30)]
        public string Vardef0 { get; set; }
        [Required]
        [Column("VARVAL_0")]
        [StringLength(30)]
        public string Varval0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}