// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("XAMYTMP", Schema = "TESTPROD")]
    [Index(nameof(Stofcy0), nameof(Mfgnum0), nameof(Stocou0), Name = "XAMYTMP_XA10", IsUnique = true)]
    [Index(nameof(Stofcy0), nameof(Ptysts0), Name = "XAMYTMP_XA11")]
    public partial class Xamytmp
    {
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Required]
        [Column("ADCUSER_0")]
        [StringLength(10)]
        public string Adcuser0 { get; set; }
        [Required]
        [Column("MFGNUM_0")]
        [StringLength(20)]
        public string Mfgnum0 { get; set; }
        [Required]
        [Column("STU_0")]
        [StringLength(3)]
        public string Stu0 { get; set; }
        [Required]
        [Column("LOC_0")]
        [StringLength(10)]
        public string Loc0 { get; set; }
        [Required]
        [Column("STA_0")]
        [StringLength(3)]
        public string Sta0 { get; set; }
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("PTYSTS_0")]
        public byte Ptysts0 { get; set; }
        [Column("QTYSTU_0", TypeName = "numeric(28, 13)")]
        public decimal Qtystu0 { get; set; }
        [Required]
        [Column("PCKUSRLIST_0")]
        [StringLength(128)]
        public string Pckusrlist0 { get; set; }
        [Column("STOCOU_0", TypeName = "numeric(11, 1)")]
        public decimal Stocou0 { get; set; }
        [Required]
        [Column("BATCH_0")]
        [StringLength(20)]
        public string Batch0 { get; set; }
        [Required]
        [Column("LOT_0")]
        [StringLength(15)]
        public string Lot0 { get; set; }
        [Required]
        [Column("SLO_0")]
        [StringLength(5)]
        public string Slo0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}