// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("XANAPAR", Schema = "TESTPROD")]
    [Index(nameof(Stofcy0), Name = "XANAPAR_XA00", IsUnique = true)]
    public partial class Xanapar
    {
        [Required]
        [Column("STOFCY_0")]
        [StringLength(5)]
        public string Stofcy0 { get; set; }
        [Column("DEFPAR_0")]
        public byte Defpar0 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Column("CRETIM_0")]
        public int Cretim0 { get; set; }
        [Required]
        [Column("CREUSR_0")]
        [StringLength(5)]
        public string Creusr0 { get; set; }
        [Column("UPDDAT_0", TypeName = "datetime")]
        public DateTime Upddat0 { get; set; }
        [Column("UPDTIM_0")]
        public int Updtim0 { get; set; }
        [Required]
        [Column("UPDUSR_0")]
        [StringLength(5)]
        public string Updusr0 { get; set; }
        [Required]
        [Column("TRSORD_0")]
        [StringLength(1)]
        public string Trsord0 { get; set; }
        [Required]
        [Column("TRSQUO_0")]
        [StringLength(1)]
        public string Trsquo0 { get; set; }
        [Required]
        [Column("TRSRET_0")]
        [StringLength(1)]
        public string Trsret0 { get; set; }
        [Column("GROMAR_0", TypeName = "numeric(14, 3)")]
        public decimal Gromar0 { get; set; }
        [Required]
        [Column("WGTUNT_0")]
        [StringLength(3)]
        public string Wgtunt0 { get; set; }
        [Required]
        [Column("XSVCTYPMF_0")]
        [StringLength(1)]
        public string Xsvctypmf0 { get; set; }
        [Required]
        [Column("VOLUNT_0")]
        [StringLength(3)]
        public string Volunt0 { get; set; }
        [Required]
        [Column("XSVCTYPDEF_0")]
        [StringLength(1)]
        public string Xsvctypdef0 { get; set; }
        [Required]
        [Column("SVCSPEDEF_0")]
        [StringLength(1)]
        public string Svcspedef0 { get; set; }
        [Required]
        [Column("EECICTDEF_0")]
        [StringLength(1)]
        public string Eecictdef0 { get; set; }
        [Column("XFRTZONTYP_0")]
        public short Xfrtzontyp0 { get; set; }
        [Column("XFRTBASIS_0")]
        public short Xfrtbasis0 { get; set; }
        [Column("XFRTALLELE_0")]
        public short Xfrtallele0 { get; set; }
        [Column("XFRTPCTSPS_0")]
        public short Xfrtpctsps0 { get; set; }
        [Required]
        [Column("PRIORITY_0")]
        [StringLength(1)]
        public string Priority0 { get; set; }
        [Column("SMCINT_0")]
        public short Smcint0 { get; set; }
        [Column("SPSINT_0")]
        public short Spsint0 { get; set; }
        [Column("SPSFOB_0")]
        public short Spsfob0 { get; set; }
        [Column("AMTPLUS_0")]
        public short Amtplus0 { get; set; }
        [Column("XFRTCLSPRD_0")]
        public short Xfrtclsprd0 { get; set; }
        [Column("XPMTAPTCAR_0")]
        public short Xpmtaptcar0 { get; set; }
        [Column("XSMCPARSHP_0")]
        public short Xsmcparshp0 { get; set; }
        [Column("XFRTPRSAL_0")]
        public short Xfrtprsal0 { get; set; }
        [Column("NUMCARDS_0")]
        public short Numcards0 { get; set; }
        [Column("CPROCESSOR_0")]
        public byte Cprocessor0 { get; set; }
        [Column("AUTPAY_0")]
        public byte Autpay0 { get; set; }
        [Column("AUTDAYS_0")]
        public int Autdays0 { get; set; }
        [Required]
        [Column("CLSREA_0")]
        [StringLength(20)]
        public string Clsrea0 { get; set; }
        [Column("CCMINAMT_0", TypeName = "numeric(14, 3)")]
        public decimal Ccminamt0 { get; set; }
        [Column("DEFTENDTYP_0")]
        public byte Deftendtyp0 { get; set; }
        [Column("TENDTYP_0")]
        public byte Tendtyp0 { get; set; }
        [Column("TENDTYP_1")]
        public byte Tendtyp1 { get; set; }
        [Column("TENDTYP_2")]
        public byte Tendtyp2 { get; set; }
        [Column("TENDTYP_3")]
        public byte Tendtyp3 { get; set; }
        [Column("TENDTYP_4")]
        public byte Tendtyp4 { get; set; }
        [Column("TENDTYP_5")]
        public byte Tendtyp5 { get; set; }
        [Column("TENDTYP_6")]
        public byte Tendtyp6 { get; set; }
        [Column("TENDTYP_7")]
        public byte Tendtyp7 { get; set; }
        [Column("TENDTYP_8")]
        public byte Tendtyp8 { get; set; }
        [Column("TENDTYP_9")]
        public byte Tendtyp9 { get; set; }
        [Column("TENDTYP_10")]
        public byte Tendtyp10 { get; set; }
        [Column("TENDTYP_11")]
        public byte Tendtyp11 { get; set; }
        [Column("TENDTYP_12")]
        public byte Tendtyp12 { get; set; }
        [Column("TENDTYP_13")]
        public byte Tendtyp13 { get; set; }
        [Column("TENDTYP_14")]
        public byte Tendtyp14 { get; set; }
        [Column("TENDTYP_15")]
        public byte Tendtyp15 { get; set; }
        [Column("TENDTYP_16")]
        public byte Tendtyp16 { get; set; }
        [Column("TENDTYP_17")]
        public byte Tendtyp17 { get; set; }
        [Column("TENDTYP_18")]
        public byte Tendtyp18 { get; set; }
        [Column("TENDTYP_19")]
        public byte Tendtyp19 { get; set; }
        [Required]
        [Column("TBANK_0")]
        [StringLength(5)]
        public string Tbank0 { get; set; }
        [Required]
        [Column("TBANK_1")]
        [StringLength(5)]
        public string Tbank1 { get; set; }
        [Required]
        [Column("TBANK_2")]
        [StringLength(5)]
        public string Tbank2 { get; set; }
        [Required]
        [Column("TBANK_3")]
        [StringLength(5)]
        public string Tbank3 { get; set; }
        [Required]
        [Column("TBANK_4")]
        [StringLength(5)]
        public string Tbank4 { get; set; }
        [Required]
        [Column("TBANK_5")]
        [StringLength(5)]
        public string Tbank5 { get; set; }
        [Required]
        [Column("TBANK_6")]
        [StringLength(5)]
        public string Tbank6 { get; set; }
        [Required]
        [Column("TBANK_7")]
        [StringLength(5)]
        public string Tbank7 { get; set; }
        [Required]
        [Column("TBANK_8")]
        [StringLength(5)]
        public string Tbank8 { get; set; }
        [Required]
        [Column("TBANK_9")]
        [StringLength(5)]
        public string Tbank9 { get; set; }
        [Required]
        [Column("TBANK_10")]
        [StringLength(5)]
        public string Tbank10 { get; set; }
        [Required]
        [Column("TBANK_11")]
        [StringLength(5)]
        public string Tbank11 { get; set; }
        [Required]
        [Column("TBANK_12")]
        [StringLength(5)]
        public string Tbank12 { get; set; }
        [Required]
        [Column("TBANK_13")]
        [StringLength(5)]
        public string Tbank13 { get; set; }
        [Required]
        [Column("TBANK_14")]
        [StringLength(5)]
        public string Tbank14 { get; set; }
        [Required]
        [Column("TBANK_15")]
        [StringLength(5)]
        public string Tbank15 { get; set; }
        [Required]
        [Column("TBANK_16")]
        [StringLength(5)]
        public string Tbank16 { get; set; }
        [Required]
        [Column("TBANK_17")]
        [StringLength(5)]
        public string Tbank17 { get; set; }
        [Required]
        [Column("TBANK_18")]
        [StringLength(5)]
        public string Tbank18 { get; set; }
        [Required]
        [Column("TBANK_19")]
        [StringLength(5)]
        public string Tbank19 { get; set; }
        [Required]
        [Column("TPTE_0")]
        [StringLength(15)]
        public string Tpte0 { get; set; }
        [Required]
        [Column("TPTE_1")]
        [StringLength(15)]
        public string Tpte1 { get; set; }
        [Required]
        [Column("TPTE_2")]
        [StringLength(15)]
        public string Tpte2 { get; set; }
        [Required]
        [Column("TPTE_3")]
        [StringLength(15)]
        public string Tpte3 { get; set; }
        [Required]
        [Column("TPTE_4")]
        [StringLength(15)]
        public string Tpte4 { get; set; }
        [Required]
        [Column("TPTE_5")]
        [StringLength(15)]
        public string Tpte5 { get; set; }
        [Required]
        [Column("TPTE_6")]
        [StringLength(15)]
        public string Tpte6 { get; set; }
        [Required]
        [Column("TPTE_7")]
        [StringLength(15)]
        public string Tpte7 { get; set; }
        [Required]
        [Column("TPTE_8")]
        [StringLength(15)]
        public string Tpte8 { get; set; }
        [Required]
        [Column("TPTE_9")]
        [StringLength(15)]
        public string Tpte9 { get; set; }
        [Required]
        [Column("TPTE_10")]
        [StringLength(15)]
        public string Tpte10 { get; set; }
        [Required]
        [Column("TPTE_11")]
        [StringLength(15)]
        public string Tpte11 { get; set; }
        [Required]
        [Column("TPTE_12")]
        [StringLength(15)]
        public string Tpte12 { get; set; }
        [Required]
        [Column("TPTE_13")]
        [StringLength(15)]
        public string Tpte13 { get; set; }
        [Required]
        [Column("TPTE_14")]
        [StringLength(15)]
        public string Tpte14 { get; set; }
        [Required]
        [Column("TPTE_15")]
        [StringLength(15)]
        public string Tpte15 { get; set; }
        [Required]
        [Column("TPTE_16")]
        [StringLength(15)]
        public string Tpte16 { get; set; }
        [Required]
        [Column("TPTE_17")]
        [StringLength(15)]
        public string Tpte17 { get; set; }
        [Required]
        [Column("TPTE_18")]
        [StringLength(15)]
        public string Tpte18 { get; set; }
        [Required]
        [Column("TPTE_19")]
        [StringLength(15)]
        public string Tpte19 { get; set; }
        [Required]
        [Column("TPAM_0")]
        [StringLength(20)]
        public string Tpam0 { get; set; }
        [Required]
        [Column("TPAM_1")]
        [StringLength(20)]
        public string Tpam1 { get; set; }
        [Required]
        [Column("TPAM_2")]
        [StringLength(20)]
        public string Tpam2 { get; set; }
        [Required]
        [Column("TPAM_3")]
        [StringLength(20)]
        public string Tpam3 { get; set; }
        [Required]
        [Column("TPAM_4")]
        [StringLength(20)]
        public string Tpam4 { get; set; }
        [Required]
        [Column("TPAM_5")]
        [StringLength(20)]
        public string Tpam5 { get; set; }
        [Required]
        [Column("TPAM_6")]
        [StringLength(20)]
        public string Tpam6 { get; set; }
        [Required]
        [Column("TPAM_7")]
        [StringLength(20)]
        public string Tpam7 { get; set; }
        [Required]
        [Column("TPAM_8")]
        [StringLength(20)]
        public string Tpam8 { get; set; }
        [Required]
        [Column("TPAM_9")]
        [StringLength(20)]
        public string Tpam9 { get; set; }
        [Required]
        [Column("TPAM_10")]
        [StringLength(20)]
        public string Tpam10 { get; set; }
        [Required]
        [Column("TPAM_11")]
        [StringLength(20)]
        public string Tpam11 { get; set; }
        [Required]
        [Column("TPAM_12")]
        [StringLength(20)]
        public string Tpam12 { get; set; }
        [Required]
        [Column("TPAM_13")]
        [StringLength(20)]
        public string Tpam13 { get; set; }
        [Required]
        [Column("TPAM_14")]
        [StringLength(20)]
        public string Tpam14 { get; set; }
        [Required]
        [Column("TPAM_15")]
        [StringLength(20)]
        public string Tpam15 { get; set; }
        [Required]
        [Column("TPAM_16")]
        [StringLength(20)]
        public string Tpam16 { get; set; }
        [Required]
        [Column("TPAM_17")]
        [StringLength(20)]
        public string Tpam17 { get; set; }
        [Required]
        [Column("TPAM_18")]
        [StringLength(20)]
        public string Tpam18 { get; set; }
        [Required]
        [Column("TPAM_19")]
        [StringLength(20)]
        public string Tpam19 { get; set; }
        [Required]
        [Column("TPAYTYP_0")]
        [StringLength(5)]
        public string Tpaytyp0 { get; set; }
        [Required]
        [Column("TPAYTYP_1")]
        [StringLength(5)]
        public string Tpaytyp1 { get; set; }
        [Required]
        [Column("TPAYTYP_2")]
        [StringLength(5)]
        public string Tpaytyp2 { get; set; }
        [Required]
        [Column("TPAYTYP_3")]
        [StringLength(5)]
        public string Tpaytyp3 { get; set; }
        [Required]
        [Column("TPAYTYP_4")]
        [StringLength(5)]
        public string Tpaytyp4 { get; set; }
        [Required]
        [Column("TPAYTYP_5")]
        [StringLength(5)]
        public string Tpaytyp5 { get; set; }
        [Required]
        [Column("TPAYTYP_6")]
        [StringLength(5)]
        public string Tpaytyp6 { get; set; }
        [Required]
        [Column("TPAYTYP_7")]
        [StringLength(5)]
        public string Tpaytyp7 { get; set; }
        [Required]
        [Column("TPAYTYP_8")]
        [StringLength(5)]
        public string Tpaytyp8 { get; set; }
        [Required]
        [Column("TPAYTYP_9")]
        [StringLength(5)]
        public string Tpaytyp9 { get; set; }
        [Required]
        [Column("TPAYTYP_10")]
        [StringLength(5)]
        public string Tpaytyp10 { get; set; }
        [Required]
        [Column("TPAYTYP_11")]
        [StringLength(5)]
        public string Tpaytyp11 { get; set; }
        [Required]
        [Column("TPAYTYP_12")]
        [StringLength(5)]
        public string Tpaytyp12 { get; set; }
        [Required]
        [Column("TPAYTYP_13")]
        [StringLength(5)]
        public string Tpaytyp13 { get; set; }
        [Required]
        [Column("TPAYTYP_14")]
        [StringLength(5)]
        public string Tpaytyp14 { get; set; }
        [Required]
        [Column("TPAYTYP_15")]
        [StringLength(5)]
        public string Tpaytyp15 { get; set; }
        [Required]
        [Column("TPAYTYP_16")]
        [StringLength(5)]
        public string Tpaytyp16 { get; set; }
        [Required]
        [Column("TPAYTYP_17")]
        [StringLength(5)]
        public string Tpaytyp17 { get; set; }
        [Required]
        [Column("TPAYTYP_18")]
        [StringLength(5)]
        public string Tpaytyp18 { get; set; }
        [Required]
        [Column("TPAYTYP_19")]
        [StringLength(5)]
        public string Tpaytyp19 { get; set; }
        [Required]
        [Column("TCRDTYP_0")]
        [StringLength(5)]
        public string Tcrdtyp0 { get; set; }
        [Required]
        [Column("TCRDTYP_1")]
        [StringLength(5)]
        public string Tcrdtyp1 { get; set; }
        [Required]
        [Column("TCRDTYP_2")]
        [StringLength(5)]
        public string Tcrdtyp2 { get; set; }
        [Required]
        [Column("TCRDTYP_3")]
        [StringLength(5)]
        public string Tcrdtyp3 { get; set; }
        [Required]
        [Column("TCRDTYP_4")]
        [StringLength(5)]
        public string Tcrdtyp4 { get; set; }
        [Required]
        [Column("TCRDTYP_5")]
        [StringLength(5)]
        public string Tcrdtyp5 { get; set; }
        [Required]
        [Column("TCRDTYP_6")]
        [StringLength(5)]
        public string Tcrdtyp6 { get; set; }
        [Required]
        [Column("TCRDTYP_7")]
        [StringLength(5)]
        public string Tcrdtyp7 { get; set; }
        [Required]
        [Column("TCRDTYP_8")]
        [StringLength(5)]
        public string Tcrdtyp8 { get; set; }
        [Required]
        [Column("TCRDTYP_9")]
        [StringLength(5)]
        public string Tcrdtyp9 { get; set; }
        [Required]
        [Column("TCRDTYP_10")]
        [StringLength(5)]
        public string Tcrdtyp10 { get; set; }
        [Required]
        [Column("TCRDTYP_11")]
        [StringLength(5)]
        public string Tcrdtyp11 { get; set; }
        [Required]
        [Column("TCRDTYP_12")]
        [StringLength(5)]
        public string Tcrdtyp12 { get; set; }
        [Required]
        [Column("TCRDTYP_13")]
        [StringLength(5)]
        public string Tcrdtyp13 { get; set; }
        [Required]
        [Column("TCRDTYP_14")]
        [StringLength(5)]
        public string Tcrdtyp14 { get; set; }
        [Required]
        [Column("TCRDTYP_15")]
        [StringLength(5)]
        public string Tcrdtyp15 { get; set; }
        [Required]
        [Column("TCRDTYP_16")]
        [StringLength(5)]
        public string Tcrdtyp16 { get; set; }
        [Required]
        [Column("TCRDTYP_17")]
        [StringLength(5)]
        public string Tcrdtyp17 { get; set; }
        [Required]
        [Column("TCRDTYP_18")]
        [StringLength(5)]
        public string Tcrdtyp18 { get; set; }
        [Required]
        [Column("TCRDTYP_19")]
        [StringLength(5)]
        public string Tcrdtyp19 { get; set; }
        [Required]
        [Column("TCPY_0")]
        [StringLength(5)]
        public string Tcpy0 { get; set; }
        [Required]
        [Column("TCPY_1")]
        [StringLength(5)]
        public string Tcpy1 { get; set; }
        [Required]
        [Column("TCPY_2")]
        [StringLength(5)]
        public string Tcpy2 { get; set; }
        [Required]
        [Column("TCPY_3")]
        [StringLength(5)]
        public string Tcpy3 { get; set; }
        [Required]
        [Column("TCPY_4")]
        [StringLength(5)]
        public string Tcpy4 { get; set; }
        [Required]
        [Column("TCPY_5")]
        [StringLength(5)]
        public string Tcpy5 { get; set; }
        [Required]
        [Column("TCPY_6")]
        [StringLength(5)]
        public string Tcpy6 { get; set; }
        [Required]
        [Column("TCPY_7")]
        [StringLength(5)]
        public string Tcpy7 { get; set; }
        [Required]
        [Column("TCPY_8")]
        [StringLength(5)]
        public string Tcpy8 { get; set; }
        [Required]
        [Column("TCPY_9")]
        [StringLength(5)]
        public string Tcpy9 { get; set; }
        [Required]
        [Column("TCPY_10")]
        [StringLength(5)]
        public string Tcpy10 { get; set; }
        [Required]
        [Column("TCPY_11")]
        [StringLength(5)]
        public string Tcpy11 { get; set; }
        [Required]
        [Column("TCPY_12")]
        [StringLength(5)]
        public string Tcpy12 { get; set; }
        [Required]
        [Column("TCPY_13")]
        [StringLength(5)]
        public string Tcpy13 { get; set; }
        [Required]
        [Column("TCPY_14")]
        [StringLength(5)]
        public string Tcpy14 { get; set; }
        [Required]
        [Column("TCPY_15")]
        [StringLength(5)]
        public string Tcpy15 { get; set; }
        [Required]
        [Column("TCPY_16")]
        [StringLength(5)]
        public string Tcpy16 { get; set; }
        [Required]
        [Column("TCPY_17")]
        [StringLength(5)]
        public string Tcpy17 { get; set; }
        [Required]
        [Column("TCPY_18")]
        [StringLength(5)]
        public string Tcpy18 { get; set; }
        [Required]
        [Column("TCPY_19")]
        [StringLength(5)]
        public string Tcpy19 { get; set; }
        [Column("AUTSTP_0")]
        public byte Autstp0 { get; set; }
        [Column("AUTPCT_0", TypeName = "numeric(7, 3)")]
        public decimal Autpct0 { get; set; }
        [Column("AUTADD_0")]
        public byte Autadd0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}