// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("XASHIFTS", Schema = "TESTPROD")]
    [Index(nameof(Shfcod0), Name = "XASHIFTS_XAH0", IsUnique = true)]
    public partial class Xashift
    {
        [Required]
        [Column("SHFCOD_0")]
        [StringLength(6)]
        public string Shfcod0 { get; set; }
        [Required]
        [Column("SHFDES_0")]
        [StringLength(30)]
        public string Shfdes0 { get; set; }
        [Required]
        [Column("BRKCOD_0")]
        [StringLength(3)]
        public string Brkcod0 { get; set; }
        [Required]
        [Column("BRKCOD_1")]
        [StringLength(3)]
        public string Brkcod1 { get; set; }
        [Required]
        [Column("BRKCOD_2")]
        [StringLength(3)]
        public string Brkcod2 { get; set; }
        [Required]
        [Column("BRKSTR_0")]
        [StringLength(5)]
        public string Brkstr0 { get; set; }
        [Required]
        [Column("BRKSTR_1")]
        [StringLength(5)]
        public string Brkstr1 { get; set; }
        [Required]
        [Column("BRKSTR_2")]
        [StringLength(5)]
        public string Brkstr2 { get; set; }
        [Required]
        [Column("BRKEND_0")]
        [StringLength(5)]
        public string Brkend0 { get; set; }
        [Required]
        [Column("BRKEND_1")]
        [StringLength(5)]
        public string Brkend1 { get; set; }
        [Required]
        [Column("BRKEND_2")]
        [StringLength(5)]
        public string Brkend2 { get; set; }
        [Required]
        [Column("SHFSTR_0")]
        [StringLength(5)]
        public string Shfstr0 { get; set; }
        [Required]
        [Column("SHFEND_0")]
        [StringLength(5)]
        public string Shfend0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}