// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("XCCRPT1", Schema = "TESTPROD")]
    [Index(nameof(Numedt0), nameof(Autid0), Name = "XCCRPT1_XC10", IsUnique = true)]
    public partial class Xccrpt1
    {
        [Column("NUMEDT_0")]
        public int Numedt0 { get; set; }
        [Required]
        [Column("AUTID_0")]
        [StringLength(15)]
        public string Autid0 { get; set; }
        [Column("AUTAMT_0", TypeName = "numeric(27, 13)")]
        public decimal Autamt0 { get; set; }
        [Column("AUTDAT_0", TypeName = "datetime")]
        public DateTime Autdat0 { get; set; }
        [Column("EXPDAYS_0")]
        public int Expdays0 { get; set; }
        [Required]
        [Column("DOCTYP_0")]
        [StringLength(3)]
        public string Doctyp0 { get; set; }
        [Required]
        [Column("NUM_0")]
        [StringLength(20)]
        public string Num0 { get; set; }
        [Required]
        [Column("BPR_0")]
        [StringLength(15)]
        public string Bpr0 { get; set; }
        [Required]
        [Column("BPRNAM_0")]
        [StringLength(35)]
        public string Bprnam0 { get; set; }
        [Required]
        [Column("BPRNAM_1")]
        [StringLength(35)]
        public string Bprnam1 { get; set; }
        [Column("CREDAT_0", TypeName = "datetime")]
        public DateTime Credat0 { get; set; }
        [Required]
        [Column("FCY_0")]
        [StringLength(5)]
        public string Fcy0 { get; set; }
        [Column("AUTDAYS_0")]
        public int Autdays0 { get; set; }
        [Required]
        [Column("LANMES_0")]
        [StringLength(123)]
        public string Lanmes0 { get; set; }
        [Column("CAPAMT_0", TypeName = "numeric(27, 13)")]
        public decimal Capamt0 { get; set; }
        [Column("STAFLG_0")]
        public byte Staflg0 { get; set; }
        [Column("CPROCESSOR_0")]
        public byte Cprocessor0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}