// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("XCMERPAR", Schema = "TESTPROD")]
    [Index(nameof(Merid0), Name = "XCMERPAR_XC90", IsUnique = true)]
    public partial class Xcmerpar
    {
        [Required]
        [Column("MERID_0")]
        [StringLength(100)]
        public string Merid0 { get; set; }
        [Required]
        [Column("DBANAM_0")]
        [StringLength(50)]
        public string Dbanam0 { get; set; }
        [Required]
        [Column("VTID_MID_0")]
        [StringLength(100)]
        public string VtidMid0 { get; set; }
        [Required]
        [Column("USRID_0")]
        [StringLength(100)]
        public string Usrid0 { get; set; }
        [Required]
        [Column("MKEY_0")]
        [StringLength(100)]
        public string Mkey0 { get; set; }
        [Required]
        [Column("OUTURL_0")]
        [StringLength(250)]
        public string Outurl0 { get; set; }
        [Required]
        [Column("INURL_0")]
        [StringLength(250)]
        public string Inurl0 { get; set; }
        [Required]
        [Column("JAVB_0")]
        [StringLength(100)]
        public string Javb0 { get; set; }
        [Column("JAVBPORT_0")]
        public int Javbport0 { get; set; }
        [Required]
        [Column("POOL_0")]
        [StringLength(50)]
        public string Pool0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}