// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ZADDRESS", Schema = "TESTPROD")]
    [Index(nameof(Codadr0), Name = "ZADDRESS_ZAD0", IsUnique = true)]
    public partial class Zaddress
    {
        [Required]
        [Column("CODADR_0")]
        [StringLength(10)]
        public string Codadr0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}