// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace com.orthofeet.Entities
{
    [Table("ZINVENTWHO", Schema = "TESTPROD")]
    [Index(nameof(Itmref0), Name = "ZINVENTWHO_ZINV0")]
    public partial class Zinventwho
    {
        [Required]
        [Column("ITMREF_0")]
        [StringLength(20)]
        public string Itmref0 { get; set; }
        [Column("GENL_0")]
        public byte Genl0 { get; set; }
        [Column("BENCHMARK_0")]
        public byte Benchmark0 { get; set; }
        [Column("FOOTSMART_0")]
        public byte Footsmart0 { get; set; }
        [Column("SAFESTEP_0")]
        public byte Safestep0 { get; set; }
        [Column("SHOEBUY_0")]
        public byte Shoebuy0 { get; set; }
        [Column("WEBWHOLE_0")]
        public byte Webwhole0 { get; set; }
        [Column("WEBRETL_0")]
        public byte Webretl0 { get; set; }
        [Key]
        [Column("ROWID")]
        public int Rowid { get; set; }
    }
}