using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace com.orthofeet.Entities
{
    [Table("BPCUSTOMER", Schema = "PROD")]
    public class Customer
    {
        [Key]
        public int ROWID { get; set; }
        public byte ABCCLS_0 { get; set; }
        public string ACCCOD_0 { get; set; }
        public short AGTPCP_0 { get; set; }
        public short AGTSATTAX_0 { get; set; }
        public string BCGCOD_0 { get; set; }
        public string BPAADD_0 { get; set; }
        public string BPAINV_0 { get; set; }
        public string BPAPYR_0 { get; set; }
        public string BPCBPSNUM_0 { get; set; }
        public string BPCCDTISR_0 { get; set; }
        public string BPCGRU_0 { get; set; }
        public string BPCINV_0 { get; set; }
        public string BPCNAM_0 { get; set; }
        public string BPCNUM_0 { get; set; }
        public string BPCPYR_0 { get; set; }
        public string BPCREM_0 { get; set; }
        public string BPCRSK_0 { get; set; }
        public string BPCSHO_0 { get; set; }
        public DateTime BPCSNCDAT_0 { get; set; }
        public byte BPCSTA_0 { get; set; }
        public byte BPCTYP_0 { get; set; }
        public string BPDADD_0 { get; set; }
        public string BUS_0 { get; set; }
        public string CCE_0 { get; set; }
        public string CCE_1 { get; set; }
        public string CCE_10 { get; set; }
        public string CCE_11 { get; set; }
        public string CCE_12 { get; set; }
        public string CCE_13 { get; set; }
        public string CCE_14 { get; set; }
        public string CCE_15 { get; set; }
        public string CCE_16 { get; set; }
        public string CCE_17 { get; set; }
        public string CCE_18 { get; set; }
        public string CCE_19 { get; set; }
        public string CCE_2 { get; set; }
        public string CCE_3 { get; set; }
        public string CCE_4 { get; set; }
        public string CCE_5 { get; set; }
        public string CCE_6 { get; set; }
        public string CCE_7 { get; set; }
        public string CCE_8 { get; set; }
        public string CCE_9 { get; set; }
        public decimal CDTISR_0 { get; set; }
        public DateTime CDTISRDAT_0 { get; set; }
        public byte CHGTYP_0 { get; set; }
        public DateTime CNTFIRDAT_0 { get; set; }
        public DateTime CNTLASDAT_0 { get; set; }
        public byte CNTLASTYP_0 { get; set; }
        public string CNTNAM_0 { get; set; }
        public DateTime CNTNEXDAT_0 { get; set; }
        public byte CNTNEXTYP_0 { get; set; }
        public byte COMCAT_0 { get; set; }
        public string COTCHX_0 { get; set; }
        public int COTPITRQD_0 { get; set; }
        public DateTime CREDAT_0 { get; set; }
        public string CRESTP_0 { get; set; }
        public string CREUSR_0 { get; set; }
        public string CUR_0 { get; set; }
        public string DEP_0 { get; set; }
        public string DIA_0 { get; set; }
        public string DIE_0 { get; set; }
        public string DIE_1 { get; set; }
        public string DIE_10 { get; set; }
        public string DIE_11 { get; set; }
        public string DIE_12 { get; set; }
        public string DIE_13 { get; set; }
        public string DIE_14 { get; set; }
        public string DIE_15 { get; set; }
        public string DIE_16 { get; set; }
        public string DIE_17 { get; set; }
        public string DIE_18 { get; set; }
        public string DIE_19 { get; set; }
        public string DIE_2 { get; set; }
        public string DIE_3 { get; set; }
        public string DIE_4 { get; set; }
        public string DIE_5 { get; set; }
        public string DIE_6 { get; set; }
        public string DIE_7 { get; set; }
        public string DIE_8 { get; set; }
        public string DIE_9 { get; set; }
        public byte DME_0 { get; set; }
        public byte DUDCLC_0 { get; set; }
        public int EXPNUM_0 { get; set; }
        public string FCTNUM_0 { get; set; }
        public short FLGSATTAX_0 { get; set; }
        public byte FREINV_0 { get; set; }
        public decimal FUPMINAMT_0 { get; set; }
        public byte FUPTYP_0 { get; set; }
        public string GRP_0 { get; set; }
        public string IDTSGL_0 { get; set; }
        public byte IME_0 { get; set; }
        public short INVDTA_0 { get; set; }
        public short INVDTA_1 { get; set; }
        public short INVDTA_10 { get; set; }
        public short INVDTA_11 { get; set; }
        public short INVDTA_12 { get; set; }
        public short INVDTA_13 { get; set; }
        public short INVDTA_14 { get; set; }
        public short INVDTA_15 { get; set; }
        public short INVDTA_16 { get; set; }
        public short INVDTA_17 { get; set; }
        public short INVDTA_18 { get; set; }
        public short INVDTA_19 { get; set; }
        public short INVDTA_2 { get; set; }
        public short INVDTA_20 { get; set; }
        public short INVDTA_21 { get; set; }
        public short INVDTA_22 { get; set; }
        public short INVDTA_23 { get; set; }
        public short INVDTA_24 { get; set; }
        public short INVDTA_25 { get; set; }
        public short INVDTA_26 { get; set; }
        public short INVDTA_27 { get; set; }
        public short INVDTA_28 { get; set; }
        public short INVDTA_29 { get; set; }
        public short INVDTA_3 { get; set; }
        public short INVDTA_4 { get; set; }
        public short INVDTA_5 { get; set; }
        public short INVDTA_6 { get; set; }
        public short INVDTA_7 { get; set; }
        public short INVDTA_8 { get; set; }
        public short INVDTA_9 { get; set; }
        public decimal INVDTAAMT_0 { get; set; }
        public decimal INVDTAAMT_1 { get; set; }
        public decimal INVDTAAMT_10 { get; set; }
        public decimal INVDTAAMT_11 { get; set; }
        public decimal INVDTAAMT_12 { get; set; }
        public decimal INVDTAAMT_13 { get; set; }
        public decimal INVDTAAMT_14 { get; set; }
        public decimal INVDTAAMT_15 { get; set; }
        public decimal INVDTAAMT_16 { get; set; }
        public decimal INVDTAAMT_17 { get; set; }
        public decimal INVDTAAMT_18 { get; set; }
        public decimal INVDTAAMT_19 { get; set; }
        public decimal INVDTAAMT_2 { get; set; }
        public decimal INVDTAAMT_20 { get; set; }
        public decimal INVDTAAMT_21 { get; set; }
        public decimal INVDTAAMT_22 { get; set; }
        public decimal INVDTAAMT_23 { get; set; }
        public decimal INVDTAAMT_24 { get; set; }
        public decimal INVDTAAMT_25 { get; set; }
        public decimal INVDTAAMT_26 { get; set; }
        public decimal INVDTAAMT_27 { get; set; }
        public decimal INVDTAAMT_28 { get; set; }
        public decimal INVDTAAMT_29 { get; set; }
        public decimal INVDTAAMT_3 { get; set; }
        public decimal INVDTAAMT_4 { get; set; }
        public decimal INVDTAAMT_5 { get; set; }
        public decimal INVDTAAMT_6 { get; set; }
        public decimal INVDTAAMT_7 { get; set; }
        public decimal INVDTAAMT_8 { get; set; }
        public decimal INVDTAAMT_9 { get; set; }
        public byte INVPER_0 { get; set; }
        public string INVTEX_0 { get; set; }
        public short LNDAUZ_0 { get; set; }
        public byte MTCFLG_0 { get; set; }
        public byte OCNFLG_0 { get; set; }
        public byte ODL_0 { get; set; }
        public byte ORDCLE_0 { get; set; }
        public DateTime ORDFIRDAT_0 { get; set; }
        public decimal ORDMINAMT_0 { get; set; }
        public string ORDTEX_0 { get; set; }
        public string ORIPPT_0 { get; set; }
        public decimal OSTAUZ_0 { get; set; }
        public byte OSTCTL_0 { get; set; }
        public string PAYBAN_0 { get; set; }
        public int PITCDT_0 { get; set; }
        public int PITCPT_0 { get; set; }
        public byte PPTFLG_0 { get; set; }
        public byte PRITYP_0 { get; set; }
        public string PTE_0 { get; set; }
        public DateTime QUOLASDAT_0 { get; set; }
        public string REP_0 { get; set; }
        public string REP_1 { get; set; }
        public string SATTAX_0 { get; set; }
        public byte SOIPER_0 { get; set; }
        public int TOTPIT_0 { get; set; }
        public string TPMCOD_0 { get; set; }
        public string TSCCOD_0 { get; set; }
        public string TSCCOD_1 { get; set; }
        public string TSCCOD_2 { get; set; }
        public string TSCCOD_3 { get; set; }
        public string TSCCOD_4 { get; set; }
        public DateTime UPDDAT_0 { get; set; }
        public string UPDSTP_0 { get; set; }
        public string UPDUSR_0 { get; set; }
        public string VACBPR_0 { get; set; }
        public string VATEXN_0 { get; set; }
        public byte ZARRESPONSIB_0 { get; set; }
        public byte ZARSTATUS_0 { get; set; }
        public DateTime ZHLDLSTOFFDT_0 { get; set; }
        public string ZHOLDCOUNT_0 { get; set; }
        public string ZNOTE_0 { get; set; }
        public byte ZORIPPT2_0 { get; set; }
        public byte ZWEBDENY_0 { get; set; }
    }
}